module.exports = {
  _: {
    bad_password: 'Contraseña incorrecta, inténtelo de nuevo ',
    cancel: 'Cancelar ',
    click: 'Haga clic en ',
    confirm: 'Confirmar ',
    continue: 'Continuar ',
    copied: '¡Copiado! ',
    copy: 'Copiado ',
    created: 'Creado en ',
    delete: 'Borrar ',
    details: 'Detalles ',
    enter_password: 'Introduzca la contraseña ',
    here: 'aquí ',
    invalid: 'inválido ',
    languageCode: 'en ',
    never: 'nunca ',
    next: 'Siguiente ',
    ok: 'OK ',
    or: 'o ',
    satoshi: 'Sat ',
    save: 'Guardar ',
    scan: 'Escanear ',
    storage_is_encrypted: 'Su almacenamiento está encriptado. Se requiere una contraseña para descifrarlo ',
    skip: 'Omitir este paso ',
    add: 'Añadir',
    undo: 'Deshacer',
    yes: 'Sí',
    no: 'No',
  },
  order: {
    first: 'primero',
    second: 'segundo',
    third: 'tercero',
    fourth: 'cuarto',
    fifth: 'quinto',
    sixth: 'sexto',
  },
  time: {
    days: 'Días',
    hours: 'Horas',
    minutes: 'Minutos',
  },
  airdrop: {
    title: 'Airdrop',
    dateOfAirdrop: 'Fecha del Airdrop:',
    readableCommunityGoals: {
      first: 'El primer objetivo',
      second: 'El segundo objetivo',
      third: 'El tercer objetivo',
      fourth: 'El cuarto objetivo',
    },
    readableGoals: {
      first: 'Su primer objetivo',
      second: 'Su segundo objetivo',
      third: 'Su tercer objetivo',
      fourth: 'Su cuarto objetivo',
    },
    community: {
      header: 'Recompensas Airdrop',
      name: 'Comunidad',
      description: 'Compruebe las recompensas y el progreso de la comunidad',
      carouselItemHeader: 'Progreso de la comunidad',
      wallet: 'monedero',
      wallets: 'monederos',
      airdropParticipants: 'Participantes del Airdrop',
      goal: 'El objetivo de la {orden}:',
      unlockToIncrease: 'Desbloquear para aumentar Airdrop a {reward}$',
      thresholdWallets: '{threshold} monederos',
    },
    circularWalletBalance: {
      yourBalance: 'Su saldo',
    },
    createWallet: {
      doYouWantToTakePart: '¿Quiere participar en el Airdrop?',
      title: '¡Airdrop ya está en marcha!',
    },
    dashboard: {
      createNewWallet: 'Crear un nuevo monedero',
      desc1: 'Añada sus monederos antes de que se acabe el tiempo.',
      desc1WithWallets: 'Controle su progreso y registre más monederos.',
      desc2: 'Cree o añada un monedero para participar en el Airdrop.',
      cantConnectToServerLine1: 'No se ha podido conectar con el servidor.',
      cantConnectToServerLine2: 'Por favor, inténtelo de nuevo en unos minutos.',
      loading1: 'Esperando al servidor.',
      loading2: 'Puede tardar unos segundos.',
      availableWallets: 'Monederos disponibles',
      registeredWallets: 'Monederos registrados',
    },
    itIsAlive: {
      subtitle: '¡Airdrop ya está en marcha!',
      description: 'Nuestro primer airdrop de BTCV está aquí.\n¡Compruébelo para obtener recompensas!',
      notNow: 'Ahora no',
      learnMore: 'Más información',
    },
    requirements: {
      soundsGreat: '¡Suena muy bien!',
      subtitle: 'Gracias por formar parte de Bitcoin Vault',
      description:
        '¡Queremos compartir {airdropTotalDollarsToShare} $ en BTCV para recompensarle por estar con nosotros!',
      listHeader: 'Requisitos para el Airdrop:',
      points: {
        '0': 'Cualquier monedero BTCV',
        '1': 'Al menos {airdropMinimumBTCVRequired} BTCV almacenados en el monedero*',
      },
      rewardExplanation: '*Su recompensa depende de la cantidad de monedas que tenga en la reserva general.',
      termsAndConditions: {
        read: 'Leer',
        termsAndConditions: 'Términos y Condiciones',
      },
    },
    walletsCarousel: {
      shrimp: 'Gamba',
      crab: 'Cangrejo',
      shark: 'Tiburón',
      whale: 'Ballena',
      yourNextGoal: 'Su {order}:',
      avatarTeaser: 'Conviértase en {goalName}: {goalThreshold} {unit}',
      youReachedGoal: 'Ha conseguido el objetivo:',
    },
    finished: {
      subtitle: '¡Airdrop se acabó!',
      stayTuned: 'Esté atento a más información en {period}',
      shareIt: 'Compártalo con otros',
      checkOutData: '¿Quiere saber más al respecto?',
      readFullReport: 'Lea nuestro informe completo sobre',
      medium: 'Medio',
      registeredWallets: 'Monederos registrados',
    },
    createWalletSuccess: {
      success: '¡Felicidades! \n  ¡Se ha registrado con éxito en Airdrop!',
      successWithNotifications: '¡Felicidades! \n  Se ha suscrito a las notificaciones y se ha registrado en Airdrop.',
      shareIt: '¡Compártalo con otros y obtenga una recompensa de {rewardValue} BTCV!*',
      maxReward: '*La recompensa máxima para un monedero es de {rewardValue} BTCV.',
      successCompletedButton: 'Vaya a {routeName}',
    },
  },
  termsConditions: {
    header: 'Términos y Condiciones ',
    title: 'Aceptación de los Términos ',
    text: '',
    readTermsConditions: 'He leído la Política de Privacidad ',
    readPrivacyPolicy: 'Estoy de acuerdo ',
    buttons: {
      agree: 'Está de acuerdo',
      disagree: 'No estoy de acuerdo',
    },
    modal: {
      header:
        'Tenga en cuenta que si no está de acuerdo con nuestros Términos y Condiciones no podrá utilizar la aplicación Gold Wallet.',
      text: '¿Está seguro de que quiere estar en desacuerdo?" ',
      noButton: 'No, he cambiado de opinión ',
      yesButton: 'Sí, no estoy de acuerdo ',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: 'Haga siempre una copia de seguridad de sus claves ',
    buildWithAwesome: 'Construya con impresionante: ',
    goToOurGithub: 'Vaya a nuestro Github ',
    header: 'Sobre nosotros ',
    rateGoldWallet: 'Valore GoldWallet ',
    releaseNotes: 'Notas de la versión ',
    runSelfTest: 'Ejecutar la autocomprobación ',
    title: 'Gold Wallet es un monedero de Bitcoin Vault gratuito y de código abierto. Con licencia MIT. ',
  },
  developer: {
    config: 'Configuración local',
    firebase: 'Base de fuego',
    FCMToken: 'FCMToken',
    copied: 'Copiado',
    header: 'Desarrollador',
    api: 'API',
    environment: 'Entorno',
  },
  advancedOptions: {
    description:
      'El activar las opciones avanzadas le permitirá elegir entre los tipos de monedero que se indican a continuación:\n P2SH, HD P2SH, HD segwit. ',
    title: 'Configurar las opciones avanzadas',
  },
  authenticators: {
    add: {
      description:
        'Lo necesitará para emparejar Gold Wallet con la aplicación de escritorio Electrum Vault. Servirá como autenticación de dos factores. ',
      subdescription: 'También puede importar su autenticador eligiendo la opción siguiente. ',
      subtitle: 'Crear un nuevo autentificador ',
      successDescription:
        'Anote esta frase semilla en algún lugar seguro. Es su copia de seguridad en caso de que necesite restaurar su autentificador. Recuerde que el autentificador es necesario para confirmar las transacciones Rápidas y de Cancelación. ',
      successTitle: '¡Su autentificador está listo! ',
      title: 'Añadir un nuevo autentificador ',
    },
    delete: {
      subtitle: 'Eliminar su autentificador ',
      success: 'Su autentificador ha sido eliminado con éxito. Siempre puede crear uno nuevo. ',
      title: 'Eliminar el autentificador ',
    },
    enterPIN: {
      description:
        'Introduzca este PIN en la aplicación de escritorio de Electrum Vault para finalizar el proceso de emparejamiento. ',
      subtitle: 'Introduzca el PIN ',
    },
    errors: {
      noEmpty: 'El campo no puede estar vacío ',
    },
    export: {
      title: 'Exportar el autentificador ',
    },
    import: {
      code: 'Código: ',
      desc1: 'Escriba la frase semilla o escanee el código QR del autenticador que desea importar.',
      desc2: 'Escanee el código QR haciendo clic en "o escanear el código QR" a continuación ',
      inUseValidationError: 'El nombre debe ser único. Por favor, introduzca un nombre válido. ',
      mnemonicLength: 'El mnemónico debe tener 12 palabras ',
      multipleQrCodesDescription:
        'Algunas transacciones generan múltiples códigos QR. Asegúrese de escanearlos todos desde la aplicación Electrum Vault. ',
      multipleQrCodesTitle: 'Escanee otro código QR ',
      scanNext: 'Escanee el siguiente ',
      subtitle: 'Importe su autentificador ',
      success: 'Ha importado correctamente su autentificador. Ahora está listo para ser utilizado. ',
      textAreaPlaceholder: 'Frase semilla ',
      title: 'Importar autentificador ',
    },
    list: {
      noAuthenticators: 'Todavía no hay autenticadores ',
      noAuthenticatorsDesc1: 'Pulse ',
      noAuthenticatorsDesc2: 'para añadir su primer autentificador. ',
      scan: 'Escanear',
      title: 'Autenticadores de Bitcoin Vault ',
    },
    options: {
      delete: 'Eliminar el autentificador ',
      export: 'Exportar autentificador ',
      pair: 'Emparejar autentificador ',
      sectionTitle: 'General ',
      title: 'Opciones del autenticador ',
    },
    pair: {
      descPin: 'Utilice este PIN para confirmar el emparejamiento del autenticador en su aplicación de escritorio. ',
      descPublicKey:
        'Puede utilizar esta clave pública para importar su autentificador en la aplicación de escritorio durante el proceso de creación del monedero con la opción GoldWallet. ',
      pin: 'PIN ',
      publicKey: 'Clave pública ',
      title: 'Emparejar el autentificador ',
    },
    publicKey: {
      okButton: 'OK, entiendo ',
      subtitle:
        'Puede utilizar esta clave pública para importar su autentificador a la aplicación de escritorio Electrum Vault durante la creación del monedero 2FA. ',
      title: 'Clave pública ',
    },
    sign: {
      error: 'Ninguno de los autentificadores pudo firmar la transacción ',
    },
  },
  betaVersion: {
    button: 'Acepto el riesgo',
    description:
      'Todavía está en fase de pruebas finales antes de su lanzamiento oficial. La aplicación móvil y todo el contenido que se encuentra en ella se proporcionan "tal cual" y "según disponibilidad". El uso del software se realiza bajo la responsabilidad del usuario. ',
    title: 'Esta es una versión beta\n de GoldWallet ',
  },
  contactCreate: {
    addressLabel: 'Dirección ',
    buttonLabel: 'Añadir nuevo contacto ',
    description: 'Por favor, introduzca el nombre y la dirección\n para su nuevo contacto. ',
    nameCannotContainSpecialCharactersError: 'El nombre no puede contener caracteres especiales. ',
    nameCannotEmpty: 'El nombre no puede ser un campo vacío ',
    nameLabel: 'Nombre ',
    nameMissingAlphanumericCharacterError: 'Al nombre le faltan caracteres alfanuméricos. ',
    screenTitle: 'Añadir nuevo contacto ',
    subtitle: 'Nuevo contacto ',
    successButton: 'Volver a la libreta de direcciones ',
    successDescription: '¡Hurra! Ha añadido con éxito\nsu contacto. ',
    successTitle: 'Éxito ',
  },
  contactDelete: {
    description1: '¿Está seguro de que quiere eliminar ',
    description2: '?',
    header: 'No puede deshacerlo. ',
    no: 'Borrar contacto ',
    success: 'No ',
    successButton: 'Éxito ',
    successDescription: 'Volver a la libreta de direcciones ',
    title: 'Su contacto ha sido eliminado con éxito.',
    yes: 'Ahora puede volver a la Libreta de direcciones. ',
  },
  contactDetails: {
    addressLabel: 'Borrar su contacto ',
    deleteButton: 'Sí ',
    editAddress: 'Dirección ',
    editName: 'Borrar contacto ',
    nameLabel: 'Editar dirección',
    sendCoinsButton: 'Enviar monedas ',
    share: 'Compartir ',
    showQRCodeButton: 'Mostrar código QR ',
  },
  contactList: {
    cancel: 'Cancelar ',
    noContacts: 'No hay contactos ',
    noContactsDesc1: 'No hay contactos para mostrar.\n   Haga clic ',
    noContactsDesc2: 'para añadir su primer contacto. ',
    noResults: 'No hay resultados en la ',
    screenTitle: 'Libreta de direcciones ',
    search: 'Buscar en ',
  },
  electrumServer: {
    connectionError: 'No se puede conectar al servidor de Electrum proporcionado ',
    description:
      'Puede cambiar la dirección del servidor al que se conectará su aplicación. Se recomienda la dirección por defecto. ',
    header: 'Servidor Electrum ',
    host: 'host ',
    port: 'puerto ',
    save: 'Guardar',
    successfullSave:
      'Sus cambios se han guardado correctamente. Puede ser necesario reiniciar para que los cambios surtan efecto. ',
    title: 'Cambiar el servidor Electrum ',
    useDefault: 'Usar por defecto ',
  },
  filterTransactions: {
    clearAll: 'Borrar todo ',
    clearFilters: 'Borrar filtros ',
    filter: 'Filtrar ',
    from: 'Desde ',
    fromAmount: 'Importe de la factura ',
    fromDate: 'Desde la fecha ',
    header: 'Filtrar transacciones ',
    receive: 'Recibir ',
    received: 'Recibido ',
    send: 'Enviar ',
    sent: 'Enviado ',
    status: {
      canceled: 'Cancelado ',
      canceledDone: 'Cancelado-hecho ',
      done: 'Hecho ',
      pending: 'Pendiente ',
    },
    to: 'A ',
    toAmount: 'Hasta la fecha ',
    toDate: 'A la fecha ',
    transactionStatus: 'Estado de la transacción ',
    transactionType: 'Tipo de transacción ',
  },
  message: {
    allDone: '¡Todo hecho! ',
    bePatient: 'Por favor, tenga paciencia, puede tardar un poco. ',
    cancelTxSuccess: 'Ha cancelado su transacción con éxito.\n  Sus monedas están en camino.',
    creatingAuthenticator: 'Creando su autentificador ',
    creatingAuthenticatorDescription:
      'Por favor, tenga paciencia mientras creamos su autentificador.\n Puede tardar un poco. ',
    creatingWallet: 'Creando su monedero ',
    creatingWalletSuccess: 'Ha creado correctamente su billetera.',
    creatingWalletDescription: 'Por favor, tenga paciencia mientras creamos su monedero.\n Puede tardar un poco.',
    generateAddressesError: 'No se pueden generar direcciones ',
    hooray: '¡Hurra! ',
    importingAuthenticator: 'Importando tu autentificador ',
    importingAuthenticatorDescription:
      'Por favor, tenga paciencia mientras importamos su autentificador.\n  Puede tardar un poco. ',
    noTransactions: 'No se han encontrado transacciones en el monedero ',
    noTransactionsDesc: 'Probablemente está intentando importar un monedero que nunca ha sido utilizado ',
    processing: 'Procesando ',
    returnToAuthenticators: 'Volver a los Autenticadores ',
    returnToDashboard: 'Volver al Panel de control ',
    returnToWalletChoose: 'Volver a la selección del tipo de monedero ',
    returnToWalletImport: 'Volver a la importación de monederos ',
    somethingWentWrong: 'Algo ha ido mal ',
    somethingWentWrongWhileCreatingWallet:
      'Algo ha ido mal mientras creábamos su monedero. Por favor, vuelva al Panel e inténtelo de nuevo. ',
    success: 'Éxito ',
    successfullWalletDelete: 'Su monedero ha sido eliminada con éxito. Ahora puede volver al Panel de control.',
    successfullWalletImport: 'Ha importado con éxito su monedero. Ahora está listo para ser utilizado. ',
    wrongMnemonic: 'Frase mnemónica incorrecta ',
    wrongMnemonicDesc:
      'Su frase mnemónica no coincide con ningún monedero admitido. Está intentando importar una frase mnemónica no válida o un monedero que nunca se ha utilizado ',
    goToWalletDetails: 'Ir a los detalles del monedero ',
    successSubscription: '¡Hurra!\n Se ha suscrito con éxito a las notificaciones. ',
  },
  notifications: {
    main: {
      header: 'Notificaciones',
      title: 'Configure sus notificaciones',
      description: 'You can choose which notifications you want to receive.',
    },
    email: {
      header: 'Notificaciones por email',
      description:
        'Puede cambiar su dirección de correo electrónico. Se utiliza para enviarle notificaciones de transacciones de los monederos elegidos.',
      title: 'Monederos',
    },
    push: {
      header: 'Notificaciones push',
      title: 'Monederos',
      description: '',
    },
    emailNotificationsNavigate: 'Notificaciones por email',
    pushNotificationsNavigate: 'Notificaciones push',
    addYourAddress: 'Añada su dirección de correo electrónico ',
    addYourEmailFor: 'Añada su correo electrónico para las notificaciones ',
    addEmail: 'Añadir correo electrónico ',
    addYourAddressDescription: 'Se utiliza para enviarle notificaciones de transacciones de los monederos elegidos. ',
    addYourEmailForDescription:
      'Puede añadir su dirección de correo electrónico. Se utiliza para enviarle notificaciones de transacciones de los monederos elegidos. ',
    change: 'Cambie su correo electrónico ',
    title: 'Configure sus notificaciones ',
    yourEmail: 'Su correo electrónico ',
    delete: 'Eliminar el correo electrónico ',
    invalidAddressError: 'Introduzca una dirección de correo electrónico válida ',
    yourSubscriptions: 'Sus suscripciones ',
    confirmEmail: 'Confirme su dirección de correo electrónico ',
    pleaseEnter: 'Por favor, introduzca el código que le hemos enviado:  ',
    resend: 'Reenviar código ',
    getNotification: 'Recibir notificaciones ',
    chooseWalletsDescription: 'Elija los monederos de los que desea recibir notificaciones de transacciones ',
    chooseWalletsToUnsubscribeDescription:
      'Puede elegir los monederos de los que quiere darse de baja de las notificaciones. ',
    emailAddedSuccessMessage: '¡Hurra!\n Se ha suscrito con éxito a las notificaciones. ',
    goToNotifications: 'Ir a Notificaciones ',
    changeEmailTitle: 'Cambie su correo electrónico ',
    changeEmailDescription:
      'Puede cambiar su dirección de correo electrónico. Se utiliza para enviarle notificaciones de transacciones de los monederos elegidos. ',
    yourCurrentEmail: 'Su correo electrónico actual ',
    theSameAddressError: 'No puede introducir su dirección de correo electrónico actual ',
    newEmail: 'Nuevo correo electrónico ',
    invalidName: 'Nombre del monedero no válido',
    confirmCurrentTitle: 'Confirme su dirección de correo electrónico actual ',
    confirmNewTitle: 'Confirme su nueva dirección de correo electrónico ',
    confirmNewDescription:
      'Confirme ahora su nueva dirección de correo electrónico. Introduzca el código que le hemos enviado  ',
    emailChangedSuccessMessage: '¡Hurra!\n Ha actualizado correctamente su dirección de correo electrónico.',
    updateNotificationPreferences: '¡Hurra!\n Ha actualizado correctamente sus preferencias de notificación.',
    verifyAction: 'Verificar esta acción ',
    verifyActionDescription: 'Para confirmar la solicitud, introduzca el código que hemos enviado a\n',
    deleteEmail: 'Eliminar la dirección de correo electrónico ',
    deleteYourEmail: 'Borrar su correo electrónico ',
    deleteYourEmailDescription: 'su dirección de correo electrónico ',
    deleteEmailSuccessMessage: '¡Hurra!\n Ha eliminado con éxito su dirección de correo electrónico. ',
    codeError: 'Por favor, introduzca un código válido.\n Le quedan {attemptsLeft} intentos.',
    codeFinalError:
      'Ha introducido un código no válido 3 veces.\n Hemos enviado un nuevo código a su dirección de correo electrónico.',
    walletSubscribedSuccessMessage:
      '¡Hurra!\n Ha añadido correctamente su dirección de correo electrónico y se ha suscrito a las notificaciones.',
    no: 'No ',
    yes: 'Sí ',
    notifications: 'Notificaciones ',
    receiveTransactionDescription:
      '¿Desea recibir notificaciones de transacciones de este monedero en su dirección de correo electrónico?  ',
    noteFirst: 'Nota:  ',
    noteSecond: 'Si quiere cambiar su dirección de correo electrónico puede hacerlo más tarde en Configuración. ',
    noSubscriptionDescription: 'No está suscrito a ninguna notificación. ',
    genericError: 'Algo ha ido mal. Lo sentimos. ',
    pushnotificationsSettings: {
      title: 'Permitir notificaciones de la aplicación.',
      label: '',
    },
    description: '',
  },
  onboarding: {
    changePin: 'Cambiar el PIN ',
    confirmNewPin: 'Confirmar nuevo PIN ',
    confirmPassword: 'Confirmar la contraseña de la transacción ',
    confirmPin: 'Confirmar PIN ',
    createNewPin: 'Nuevo PIN ',
    createPassword: 'Crear contraseña de transacción ',
    addNotificationEmailDescription:
      'Si desea recibir notificaciones por correo electrónico, introduzca su dirección de correo electrónico. Le enviaremos información sobre el estado de sus transacciones. Siempre puede cambiarlo más tarde en Configuración. ',
    createPasswordDescription:
      'Su contraseña de transacción se utilizará para verificar todas las transacciones. No podrá cambiarla posteriormente. La contraseña de la transacción debe contener al menos 8 caracteres alfanuméricos. ',
    createPin: 'Crear PIN ',
    createPinDescription:
      'Su PIN se utilizará para iniciar la sesión en la aplicación. Puede cambiarlo más adelante en la sección de configuración. ',
    currentPin: 'PIN actual ',
    failedTimes: 'Intentos fallidos ',
    failedTimesErrorInfo: 'Después de tres intentos fallidos, el acceso se bloqueará para ',
    goBack: 'Retroceder ',
    minutes: 'minutos. ',
    numberOfAttemptsExceeded: 'Se ha superado el número de intentos ',
    onboarding: 'Integración',
    passwordDoesNotMatch: 'La contraseña no coincide. Por favor, introduzca una contraseña válida. ',
    pin: 'PIN ',
    pinDoesNotMatch: 'El PIN no coincide. Por favor, introduzca un PIN válido.  ',
    seconds: 'segundos ',
    successButton: 'Ir al Panel',
    successButtonChangedPin: 'Volver a la configuración ',
    successDescription: '¡Hurra!\n  Ha creado correctamente su PIN. ',
    successDescriptionChangedPin: '¡Hurra! \n  Ha cambiado correctamente su PIN. ',
    tryAgain: 'Inténtelo de nuevo después de',
    resendCodeError:
      'Ha introducido un código no válido 3 veces. \n Hemos enviado un nuevo código a su dirección de correo electrónico.',
    successCompletedDescription: '¡Hurra! \n Ha terminado con éxito su proceso de integración.',
    successCompletedButton: 'Ir a los Monederos',
  },
  receive: {
    details: {
      amount: 'Importe',
      receiveWithAmount: 'Recibir con el importe ',
      receiveWithAmountSubtitle:
        'Introduzca el importe que desea recibir. El código QR se actualizará para incluir ese importe. ',
      share: 'Compartir ',
      shareWalletAddress: 'Compartir la dirección del monedero ',
    },
    header: 'Recibir monedas ',
    label: 'Dirección del monedero',
  },
  scanQrCode: {
    cancel: 'Cancelar ',
    ok: 'Ok ',
    permissionMessage: 'Necesitamos su permiso para usar su cámara ',
    permissionTitle: 'Permiso para usar la cámara ',
  },
  security: {
    jailBrokenPhone:
      'Su dispositivo parece tener jailbreak. Esto puede provocar problemas de seguridad, caídas u otros problemas. No recomendamos usar GoldWallet con un dispositivo con jailbreak. ',
    noPinOrFingerprintSet:
      'Parece que su dispositivo no tiene configurado el PIN o la huella digital. No recomendamos utilizar GoldWallet con un dispositivo no protegido. ',
    rootedPhone:
      'Su dispositivo parece estar rooteado. Esto puede provocar problemas de seguridad, bloqueos u otros problemas. No recomendamos utilizar GoldWallet con un dispositivo rooteado. ',
    title: 'Problema de seguridad ',
  },
  selectLanguage: {
    alertDescription: '¿Seleccionar el idioma y reiniciar la aplicación? ',
    cancel: 'Cancelar ',
    confirm: 'Confirmar ',
    confirmation: 'Confirmación ',
    header: 'Idioma ',
    restartInfo:
      'Al seleccionar un nuevo idioma, puede ser necesario reiniciar GoldWallet para que el cambio surta efecto ',
  },
  send: {
    confirm: {
      availableBalance: 'Saldo disponible después de la transacción ',
      cancelNow: 'Cancelar ahora ',
      pendingBalance: 'Saldo bloqueado después de la transacción ',
      sendNow: 'Enviar ahora ',
    },
    create: {
      amount: 'Importante ',
      fee: 'Tarifa ',
      headerText:
        'Cuando hay un gran número de transacciones pendientes en la red (>1500), la tasa más alta hará que su transacción se procese más rápidamente. Los valores típicos son 1-500 sat/b ',
      setTransactionFee: 'Configurar una tasa de transacción ',
    },
    details: {
      address: 'dirección ',
      address_field_is_not_valid: 'El campo de la dirección no es válido ',
      amount_field_is_not_valid: 'El campo del importe no es válido ',
      amount_is_too_high: 'Hay un máximo de {maxCoinsInput} BTCV que podrá existir, ¡así que no intente enviar más! ',
      amount_is_negative: 'La cantidad no puede ser negativa ',
      amount_field_is_less_than_minSatoshi: 'La cantidad mínima que puede enviar es de 1 Satoshi ',
      amount_placeholder: 'cantidad a enviar (en BTCV) ',
      cancel: 'Cancelar ',
      create: 'Crear factura',
      create_tx_error:
        'Se ha producido un error al crear la transacción. Por favor, asegúrese de que la dirección es válida. ',
      fee: 'Tasa: ',
      fee_field_is_not_valid: 'El campo de la tasa no es válido ',
      fee_placeholder: 'más la tarifa de la transacción (en BTCV) ',
      feeUnit: 'Sat/B ',
      next: 'Siguiente ',
      note: 'Nota (opcional) ',
      note_placeholder: 'nota para uno mismo ',
      remaining_balance: 'Saldo restante ',
      scan: 'Escanear ',
      send: 'Enviar ',
      title: 'crear una transacción ',
      to: 'a ',
      total_exceeds_balance: 'El importe de envío supera el saldo disponible. ',
    },
    error: {
      doubleSpentFunds: 'Está intentando gastar fondos que ya se han gastado. ',
      notExistingFunds: 'Está intentando gastar fondos que no existen. ',
      dust: 'Está intentando enviar una cantidad pequeña ',
      description: 'Antes de crear una transacción, debe añadir un monedero de Bitcoin Vault. ',
      title: 'Error ',
    },
    header: 'Enviar monedas ',
    recovery: {
      confirmFirstSeed: 'Confirm with Cancel Seed Phrase',
      confirmFirstSeedDesc:
        'Open the first PDF document you generated when you created your wallet and write down the Private Key seed phrase in the same order.',
      confirmSecondSeed: 'Confirm with Fast Seed Phrase',
      confirmSecondSeedDesc:
        'Open the second PDF document you generated when you created your wallet and write down the Private Key seed phrase in the same order.',
      confirmSeed: 'Confirm with Cancel Seed Phrase',
      confirmSeedDesc:
        'Open the PDF document you generated when you created your wallet and write down the Private Key seed phrase in the same order.',
      recover: 'Cancel',
      useWalletAddress: 'Utilizar la dirección de este monedero ',
    },
    success: {
      description: 'Ha enviado sus monedas con éxito. ',
      done: 'Hecho ',
      return: 'Volver al Panel',
      title: 'Éxito ',
    },
    transaction: {
      alert: 'Asegura ',
      alertDesc:
        'Esta transacción necesita 144 bloques o unas 24 horas para ser confirmada. Puede cancelarla dentro de este tiempo. ',
      fastSuccess: 'Ha realizado con éxito su transacción rápida. ',
      instant: 'Segura y Rápida ',
      instantDesc: 'Esta transacción será confirmada inmediatamente. Utilícela con extrema precaución. ',
      lightningError:
        'Esta dirección parece ser para una factura de Lightning. Por favor, vaya a su monedero Lightning para realizar el pago de esta factura. ',
      scanInstantKeyDesc:
        'Abra el documento PDF que generó cuando creó su monedero y escanee el código QR de la Clave Privada para enviar la transacción. ',
      scanInstantKeyTitle: 'Escanear la Clave Rápida ',
      type: 'Tipo de transacción ',
      watchOnlyError: 'Los monederos de lectura sólo no pueden enviar transacciones ',
    },
    warning: 'Advertencia: ',
    warningGeneral:
      'Por favor, tenga en cuenta que en el proceso de uso de la función de Transacción Segura, una parte de los fondos que quedan en su monedero puede ser bloqueados. Es un procedimiento normal vinculado a UTXO y a los parámetros de la blockchain del monedero Bitcoin Vault. Sus fondos serán desbloqueados una vez que la transacción sea verificada (después de aproximadamente 24 horas) o cancelada (dentro de 24 horas). ',
  },
  settings: {
    about: 'Acerca de ',
    terms: 'Condiciones y Privacidad ',
    factoryReset: 'Restablecer la configuración de fábrica',
    devInfo: 'Información para desarrolladores',
    developer: 'Desarrollador',
    aboutUs: 'Acerca de nosotros ',
    advancedOptions: 'Opciones avanzadas ',
    Biometrics: 'Permitir la biometría ',
    changePin: 'Cambiar el PIN ',
    electrumServer: 'Servidor Electrum ',
    FaceID: 'Permitir FaceID ',
    fingerprintLogin: 'Inicio de sesión por huella dactilar ',
    general: 'General ',
    header: 'Configuración ',
    language: 'Idioma ',
    notifications: 'Notificaciones ',
    notSupportedFingerPrint: 'Su dispositivo no es compatible con la huella dactilar ',
    security: 'Seguridad ',
    TouchID: 'Permitir huella digital ',
    factory: {
      title: 'Restablecer la configuración de fábrica',
      text:
        '¿Está seguro de que quiere restaurar Gold Wallet a su configuración de fábrica? Todos tus monederos y datos serán borrados. Recuerde que tendrá que importar sus monederos de nuevo.',
      noButton: 'No',
      yesButton: 'Sí',
    },
  },
  tabNavigator: {
    addressBook: 'Libreta de direcciones ',
    authenticators: 'Autenticadores ',
    settings: 'Configuración ',
    wallets: 'Monederos ',
  },
  timeCounter: {
    closeTheApp: 'Cerrar la aplicación ',
    description:
      'Su aplicación se ha bloqueado debido a los intentos fallidos de inicio de sesión. Por favor, espere el tiempo necesario para volver a intentarlo. ',
    title: 'Aplicación bloqueada ',
    tryAgain: 'Inténtelo de nuevo ',
  },
  transactions: {
    details: {
      addNote: 'Añadir nota ',
      addToAddressBook: 'Añadir a la libreta de direcciones ',
      amount: 'Importe ',
      blocked: 'Bloqueado ',
      bytes: 'bytes ',
      confirmations: 'confirmaciones ',
      copy: 'Copiar ',
      copyAndBoriadcast: 'Copiar y emitir más tarde ',
      details: 'Detalles ',
      detailTitle: 'Detalles de la transacción ',
      fee: 'Tarifa: ',
      from: 'Desde ',
      inputs: 'Entradas ',
      noLabel: 'Sin etiqueta ',
      note: 'Nota ',
      numberOfCancelTransactions: 'Número de transacciones canceladas ',
      ouputs: 'Salidas ',
      returnedFee: 'Tasa de devolución: ',
      satoshiPerByte: 'Satoshi por byte ',
      sendCoins: 'Enviar monedas ',
      timePending: 'Tiempo pendiente ',
      title: 'Transacción ',
      to: 'A ',
      toExternalWallet: 'Al monedero externo ',
      toInternalWallet: 'Al monedero interno ',
      totalReturnedFee: 'Tarifa devuelta en total: ',
      transactioFee: 'Tarifa de la transacción ',
      transactionDetails: 'Detalles de la transacción ',
      transactionHex: 'Transacción hex',
      transactionHexDescription: 'Es una transacción hex, firmada y lista para ser emitida a la red ',
      transactionId: 'ID de la transacción ',
      transactionType: 'Tipo de transacción ',
      txSize: 'Tamaño de la transmisión ',
      unblocked: 'Desbloqueado ',
      verify: 'Verificar en coinb.in ',
      viewInBlockRxplorer: 'Ver en el explorador de bloques ',
      walletType: 'Tipo de monedero',
    },
    errors: {
      notEnoughBalance: 'No hay suficiente saldo. Por favor, intente enviar un importe menor. ',
    },
    label: {
      blocked: 'bloqueado ',
      canceled: 'cancelado ',
      canceledDone: 'cancelado - hecho ',
      done: 'hecho ',
      pending: 'pendiente ',
      unblocked: 'desbloqueado ',
    },
    list: {
      conf: 'Confirmaciones ',
    },
    transactionTypeLabel: {
      canceled: 'Cancelado ',
      secure: 'Segura ',
      secureFast: 'Segura y Rápida ',
      standard: 'Estándar',
    },
  },
  unlock: {
    confirmButton: 'Confirme la huella digital para continuar. ',
    enter: 'Introducir PIN ',
    title: 'Desbloquear ',
    touchID: 'Toque el ID para Gold Wallet. ',
  },
  unlockTransaction: {
    description: 'Introduzca la contraseña de la transacción para continuar. ',
    headerText: 'Confirmar la transacción ',
    title: 'Confirmar la Transacción ',
  },
  wallets: {
    add: {
      createWalletButton: 'Crear un nuevo monedero',
      addWalletButton: 'Añadir nuevo monedero ',
      advancedOptions: 'Opciones avanzadas ',
      air: 'Realiza transacciones Seguras, de Cancelación y Seguras y Rápidas. ',
      ar: 'Realiza transacciones Sseguras y de Cancelación. ',
      description: 'Elija el nombre y el tipo de su monedero. ',
      failed: 'Fallo al crear el monedero ',
      importWalletButton: 'Importar monedero ',
      inputLabel: 'Nombre ',
      legacy: 'Realiza los tipos de transacciones por defecto. ',
      legacyHDP2SH: 'Contiene un árbol de direcciones P2SH generado a partir de una única semilla de 12 palabras ',
      legacyHDP2SHTitle: 'Estándar HD P2SH ',
      LegacyHDSegWit:
        'Contiene un árbol de direcciones segwit nativas, generadas a partir de una única semilla de 12 palabras ',
      legacyHDSegWitTitle: 'Estándar HD SegWit ',
      LegacyP2SH: 'Contiene una única dirección P2SH ',
      legacyP2SHTitle: 'Estándar P2SH ',
      legacyTitle: 'Estándar ',
      multipleAddresses: 'Contiene un árbol de direcciones P2SH generado a partir de una única semilla de 12 palabras ',
      publicKeyError: 'La clave pública proporcionada no es válida ',
      segwidAddress:
        'Contiene un árbol de direcciones segwit nativas, generadas a partir de una única semilla de 12 palabras ',
      singleAddress: 'Contiene una única dirección P2SH ',
      subtitle: 'Nombre del monedero ',
      title: 'Añadir nuevo monedero ',
      walletType: 'Tipo de monedero ',
    },
    confirmSeed: {
      header: 'Confirmar frase semilla',
      title: 'Confirme la frase de respaldo',
      description: 'Pulse las palabras en el orden correcto para confirmar su respaldo de seguridad.',
      button: 'Confirmar',
      error: 'El orden de la frase semilla es incorrecto.',
    },
    addSuccess: {
      description:
        'Anote esta frase de la semilla en algún lugar seguro. Es su copia de seguridad en caso de que necesite restaurar su monedero. ',
      okButton: 'OK, lo he apuntado',
      subtitle: '¡Su monedero está listo!\n Ha creado su monedero! ',
      title: 'Añadir nueva billetera ',
    },
    dashboard: {
      allWallets: 'Todos los monederos ',
      availableBalance: 'Saldo disponible ',
      noTransactions: 'No hay transacciones para mostrar ',
      noWallets: 'No hay monederos ',
      noWalletsDesc1: 'No hay monederos para mostrar.\nAñadir su primer monedero. ',
      noWalletsDesc2: 'para añadir su primer monedero. ',
      receive: 'Recibir ',
      recover: 'Cancelar ',
      send: 'Enviar ',
      title: 'Monederos',
      wallet: 'monedero ',
    },
    deleteWallet: {
      description1: '¿Está seguro de que quiere borrar ',
      description2: '? No puede deshacerlo. ',
      header: 'Borrar el monedero',
      no: 'No ',
      title: 'Borrar el monedero ',
      yes: 'Sí ',
    },
    details: {
      deleteWallet: 'Borrar el monedero ',
      details: 'Detalles ',
      edit: 'Editar ',
      exportWallet: 'Exportar monedero ',
      latestTransaction: 'Última transacción ',
      nameEdit: 'Editar nombre ',
      nameLabel: 'Nombre ',
      showWalletXPUB: 'Mostrar monedero XPUB ',
      typeLabel: 'Tipo',
      subscribeWallet: 'Suscribirse a las notificaciones por correo electrónico ',
      unsubscribeWallet: 'Darse de baja de las notificaciones por correo electrónico ',
    },
    errors: {
      duplicatedPublicKey: 'La clave pública ya ha sido añadida ',
      invalidMnemonic: 'Frase mnemónica inválida ',
      invalidMnemonicWordsNumber:
        'Se han proporcionado {receivedWordsNumber} palabras esperadas {expectedWordsNumber} ',
      invalidPrivateKey: 'Clave privada inválida ',
      invalidPublicKey: 'Clave pública inválida ',
      invalidQrCode: 'Código QR inválido ',
      invalidSign: 'No se ha podido firmar la transacción ',
      noIndexForWord: 'No se ha podido encontrar el índice para la palabra: {word} ',
      wrongNetwork:
        'Tiene el monedero en la red {walletNetworkName} mientras que la red de la app es {appNetworkName}. Por favor, contacte con nuestro soporte a través de Telegram. ',
    },
    export: {
      title: 'Exportación del monedero',
    },
    exportWallet: {
      header: 'Exportar monedero',
      title: 'Frase semilla ',
    },
    exportWalletXpub: {
      header: 'Monedero XPUB ',
    },
    import: {
      do_import: 'Importar ',
      error: 'Fallo en la importación. Por favor, asegúrese de que los datos proporcionados son válidos. ',
      explanation:
        'Escriba aquí frase mnemónica, clave privada, WIF, o cualquier cosa que tenga. GoldWallet hará todo lo posible para adivinar el formato correcto e importar su monedero',
      imported: 'Importar ',
      scan_qr: '¿o escanear el código QR en su lugar? ',
      success: 'Éxito ',
      title: 'importar ',
    },
    importWallet: {
      chooseTypeDescription: 'Elija el tipo de monedero que desea importar. ',
      customWords: 'Palabras personalizadas ',
      extendWithCustomWords: 'Ampliar esta semilla con palabras personalizadas ',
      header: 'Importar monedero ',
      import: 'Importar ',
      importARDescription1: 'Introduzca la frase semilla ',
      importARDescription2: 'Escanee el código QR del monedero que desea importar ',
      placeholder: 'Frase semilla ',
      scanCancelPubKey: 'Escanear el código QR de la Clave de Cancelación ',
      scanFastPubKey: 'Escanear el código QR de la Clave Rápida ',
      scanPublicKeyDescription:
        'Abra el primer documento PDF que generó cuando creó el monedero que desea importar y utilice esta aplicación para escanear el código QR de la clave pública. ',
      scanQrCode: 'o escanear el código QR ',
      scanWalletAddress: 'Escanear la dirección del monedero ',
      scanWalletAddressDescription:
        'Escanea el código QR de Dirección Pública para iniciar la integración con GoldWallet. ',
      subtitle:
        'Escriba aquí su frase mnemónica, clave privada, WIF o cualquier cosa que tenga. GoldWallet hará todo lo posible para adivinar el formato correcto e importar su monedero. ',
      title: 'Importar su monedero ',
      unsupportedElectrumVaultMnemonic:
        'Esta semilla es de Electrum Vault y actualmente no está soportada. Será soportada en un futuro próximo. ',
      walletInUseValidationError: 'El monedero ya está en uso. Por favor, introduzca un monedero válido. ',
      allWalletsValidationError: 'No puede introducir el nombre "Todos los monederos" ',
    },
    publicKey: {
      instantDescription:
        'Vaya otra vez a Web Key Generator en otro dispositivo, actualice la página y utilice esta aplicación para escanear el nuevo código QR de la clave pública. Recuerde exportar sus claves en formato PDF. ',
      instantSubtitle: 'Añadir una Clave Rápida ',
      recoveryDescription:
        'Vaya a Web Key Generator en un dispositivo distinto y utilice esta aplicación para escanear el código QR de la Clave Pública. Recuerde exportar sus claves en formato PDF. ',
      recoverySubtitle: 'Añadir Clave de Cancelación ',
      scan: 'Escanear ',
      webKeyGenerator: 'Web Key Generator: ',
    },
    scanQrWif: {
      bad_password: 'Contraseña incorrecta ',
      bad_wif: 'WIF incorrecto ',
      cancel: 'Cancelar ',
      decoding: 'Descifrar ',
      go_back: 'Regresar ',
      imported_legacy: 'Legacy importado ',
      imported_segwit: 'SegWit importado',
      imported_watchonly: 'Sólo de lectura importado',
      imported_wif: 'WIF importado',
      input_password: 'Contraseña de entrada ',
      password_explain: 'Esta es la clave privada encriptada de BIP38 ',
      wallet_already_exists: 'Este monedero ya existe ',
      with_address: 'con la dirección ',
    },
    wallet: {
      latest: 'Última transacción ',
      none: 'Ninguna ',
      pendingBalance: 'Saldo bloqueado ',
    },
    walletModal: {
      btcv: 'BTCV ',
      wallets: 'Monederos ',
    },
  },
  connectionIssue: {
    noInternetTitle: 'No hay conexión a Internet ',
    noInternetDescription: 'Asegúrese de que el WI-FI o los datos móviles están activados y vuelva a intentarlo. ',
    offlineMessageTitle: 'Está offline ',
    offlineMessageDescription: 'Conéctese a Internet para restablecer la funcionalidad completa. ',
    offlineMessageDescription2: 'Conéctese a Internet para seguir utilizando estas funciones. ',
    noNetworkTitle: 'No hay red ',
    noNetworkDescription:
      'Su Internet funciona, pero no está conectado a la red. Por favor, espere un momento e inténtelo de nuevo. ',
    electrumXNotConnected: 'El cliente Electrum no está conectado ',
    couldntConnectToServer: 'No se ha podido conectar al servidor. ',
  },
};
