module.exports = {
  _: {
    bad_password: 'Kata sandi salah, coba lagi',
    cancel: 'Batalkan',
    click: 'Klik',
    confirm: 'Konfirmasi',
    continue: 'Lanjutkan',
    copied: 'Disalin!',
    copy: 'Salin',
    created: 'Dibuat pada',
    delete: 'Hapus',
    details: 'Detail',
    enter_password: 'Masukkan Kata Sandi',
    here: 'DIsini',
    invalid: 'Tidak Valid',
    languageCode: 'en',
    never: 'tidak pernah',
    next: 'Selanjutnya',
    ok: 'Ok',
    or: 'atau',
    satoshi: 'Sat',
    save: 'Simpan',
    scan: 'Pindai',
    storage_is_encrypted: 'Penyimpanan Anda dienkripsi.\nMasukkan kata sandi untuk membuka enkripsi.',
    skip: 'Lewati langkah ini',
  },
  termsConditions: {
    header: 'Syarat dan Ketentuan',
    title: 'Persetujuan Ketentuan',
    readTermsConditions: 'Saya telah membaca Syarat dan Ketentuan',
    readPrivacyPolicy: 'Saya telah membaca Kebijakan Privasi',
    buttons: {
      agree: 'Saya Setuju',
      disagree: 'Saya Tidak Setuju',
    },
    modal: {
      header: 'Apakah Anda yakin?',
      text:
        'Mohon dicatat bahwa bila Anda tidak setuju dengan Syarat dan Ketentuan kami, Anda tidak akan dapat menggunakan aplikasi Gold Wallet. Apakah Anda yakin tidak tidak setuju?',
      noButton: 'Tidak, Saya berubah pikiran',
      yesButton: 'Ya, Saya tidak setuju',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: 'Selalu backup kunci Anda',
    buildWithAwesome: 'Membangun dengan kehebatan:',
    goToOurGithub: 'Kunjungi Github kami',
    header: 'Tentang kami',
    rateGoldWallet: 'Berikan rating untuk Gold Wallet',
    releaseNotes: 'Catatan Rilis',
    runSelfTest: 'Jalankan tes mandiri',
    title: 'Gold Wallet adalah aplikasi dompet Bitcoin Vault gratis dan open source. Dilisensi MIT.',
  },
  advancedOptions: {
    description:
      'Mengaktifkan opsi lanjutan akan memberikan Anda kemungkinan untuk memilik tipe dompet dari daftar di bawah ini:\nP2SH, HD P2SH, HD segwit.',
    title: 'Konfigurasi opsi lanjutan',
  },
  authenticators: {
    add: {
      description:
        'Anda harus menyambungkan Gold Wallet dengan aplikasi desktop Electrum Vault. Aplikasi ini akan bekerja sebagai autentikasi dua faktor.',
      subdescription: 'Anda juga dapat mengimpor autentikator dengan cara memilih opsi dibawah',
      subtitle: 'Buat autentikator baru',
      successDescription:
        'Tuliskan dan simpan frasa benih (seed phrase) ini ditempat yang aman. Frasa ini berfungsi sebagai backup ketika Anda harus memulihkan autentikator Anda. Mohon diingat bahwa autentikator diperlukan untuk mengkonfirmasi transaksi Cepat dan Pembatalan.',
      successTitle: 'Autentikator Anda suduah siap!',
      title: 'Tambahkan autentikator baru',
    },
    delete: {
      subtitle: 'Hapus autentikator Anda',
      success: 'Autentikator Anda telah berhasil dihapus. Anda dapat menambahkan autentikator baru.',
      title: 'Hapus autentikator',
    },
    enterPIN: {
      description: 'Masukkan PIN Anda ke aplikasi desktop Electrum Vault untuk menyelesaikan proses penyambungan.',
      subtitle: 'Masukkan PIN',
    },
    errors: {
      noEmpty: 'Bidang tidak boleh kosong',
    },
    export: {
      title: 'Ekspor Autentikator',
    },
    import: {
      code: 'Kode:',
      desc1:
        'Tuliskan dan simpan frasa benih (seed phrase) ini ditempat yang aman atau pindai kode QR autentikator yang ingin Anda impor.',
      desc2: 'pindai kode QR dengan mengklik "atau pindai kode QR" di bawah ini',
      inUseValidationError: 'Nama harus unik. Mohon masukkan nama yang valid.',
      mnemonicLength: 'Mnemonik harus terdiri dari 12 kata',
      multipleQrCodesDescription:
        'Beberapa transaksi menghasilkan beberapa kode QR. Pastikan bahwa Anda telah memindai semua kode dari aplikasi Electruc Vault.',
      multipleQrCodesTitle: 'Pindai kode QR lain',
      scanNext: 'Pindai selanjutnya',
      subtitle: 'Impor Autentikator Anda',
      success: 'Anda telah berhasil mengimpor autentikator Anda dan sudah siap sudah dipakai.',
      textAreaPlaceholder: 'Frase kode (Seed phrase)',
      title: 'Impor Autentikator',
    },
    list: {
      noAuthenticators: 'Autentikator belum terdaftar',
      noAuthenticatorsDesc1: 'Ketuk',
      noAuthenticatorsDesc2: 'untuk menambahkan autentikator pertama Anda.',
      scan: 'Pindai',
      title: 'Autentikator Bitcoin Vault',
    },
    options: {
      delete: 'Hapus Autentikator ',
      export: 'Ekspor Autentikator',
      pair: 'Sambungkan Autentikator',
      sectionTitle: 'Umum',
      title: 'Opsi Autentikator ',
    },
    pair: {
      descPin: 'Gunakan PIN ini untuk mengkonfirmasi autentikator yang terpasang di aplikasi desktop Anda.',
      descPublicKey:
        'Anda dapat menggunakan Kode Publik ini untuk mengimpor autentikator Anda di aplikasi desktop ketika proses pembuatan dompet dengan menggunakan opsi GoldWallet.',
      pin: 'PIN',
      publicKey: 'Kunci Publik',
      title: 'Sambungkan Autentikator',
    },
    publicKey: {
      okButton: 'OK, Saya mengerti',
      subtitle:
        'Anda dapat menggunakan Kode Publik ini untuk mengimpor autentikator Anda ke aplkasi desktop Electrum Vault ketika proses pembuatan 2FA dompet.',
      title: 'Kunci Publik',
    },
    sign: {
      error: 'Tidak ada autentikator yang dapat menandatangani transaksi ini.',
    },
  },
  betaVersion: {
    button: 'Saya menerima risikonya',
    description:
      'Fitur ini masih dalam proses pengujian akhir sebelum dapat dirilis secara resmi. Aplikasi mobile dan semua konten yang ditemukan dalam aplikasi ini bersifat "apa adanya" dan "seadanya". Risiko penggunaan softwarde sepenuhnya ditanggung oleh pengguna.',
    title: 'Ini adalah versi beta GoldWallet',
  },
  contactCreate: {
    addressLabel: 'Alamat',
    buttonLabel: 'Tambahkan kontak baru',
    description: 'Mohon masukkan nama dan alamat baru untuk kontak baru Anda.',
    nameCannotContainSpecialCharactersError: 'Nama tidak dapat mengandung karakter khusus.',
    nameCannotEmpty: 'Bidang nama tidak boleh kosong.',
    nameLabel: 'Nama',
    nameMissingAlphanumericCharacterError: 'Nama kekurangan karakter alfanumerik.',
    screenTitle: 'Tambahkan kontak baru',
    subtitle: 'Kontak baru',
    successButton: 'Kembali ke buku Alamat',
    successDescription: 'Hore! Anda telah berhasil menambagkan kontak baru',
    successTitle: 'Sukses',
  },
  contactDelete: {
    description1: 'Apakah Anda tetap ingin menghaous kontak?',
    description2: '?\nAnda tidak dapat mengulang/membalikkan proses.',
    header: 'Hapus kontak',
    no: 'Tidak',
    success: 'Sukses',
    successButton: 'Kembali ke buku Alamat',
    successDescription: 'Kontak Anda telah berhasil dihapus. Sekarang Anda dapat kembali ke buku Alamat.',
    title: 'Hapus kontak Anda',
    yes: 'Ya',
  },
  contactDetails: {
    addressLabel: 'Alamat',
    deleteButton: 'Hapus kontak',
    editAddress: 'Ubah alamat',
    editName: 'Ubah nama',
    nameLabel: 'Nama',
    sendCoinsButton: 'Kirim koin',
    share: 'Bagikan',
    showQRCodeButton: 'Tunjukkan kode QR',
  },
  contactList: {
    cancel: 'Batalkan',
    noContacts: 'Tidak ada kontak',
    noContactsDesc1: 'Tidak ada kontak yang dapat ditunjukkan.\nKlik',
    noContactsDesc2: 'Untuk menambahkan kontak pertama Anda.',
    noResults: 'Hasil tidak ditemukan untuk',
    screenTitle: 'Buku Alamat',
    search: 'Cari',
  },
  electrumServer: {
    connectionError: 'Tidak dapat tersambung ke Server Electrum yang tersedia',
    description:
      'Anda dapat merubah alamat server kemana aplikasi Anda akan tersambung. Penggunaan alamat bawaan/default sangat direkomendasikan.',
    header: 'Server Electrum',
    host: 'Host ',
    port: 'Port',
    save: 'Simpan',
    successfullSave:
      'Perubahan Anda telah sukses disimpan. Mohon lakukan restart agar perubahan dapat diimplementasikan dengan baik.',
    title: 'Ubah server electrum',
    useDefault: 'Gunakan default/bawaan',
  },
  filterTransactions: {
    clearAll: 'Bersihkan semua',
    clearFilters: 'Bersihkan filter',
    filter: 'Filter ',
    from: 'Dari',
    fromAmount: 'Dari jumlah',
    fromDate: 'Dari tanggal',
    header: 'Filter transaksi ',
    receive: 'Terima',
    received: 'Diterima',
    send: 'Kirim koin',
    sent: 'Dikirim',
    status: {
      canceled: 'Dibatalkan',
      canceledDone: 'Dibatalkan - selesai',
      done: 'Selesai',
      pending: 'Menunggu',
    },
    to: 'Ke',
    toAmount: 'Ke jumlah',
    toDate: 'Ke tanggal',
    transactionStatus: 'Status Transaksi',
    transactionType: 'Tipe Transaksi',
  },
  message: {
    allDone: 'Selesai!',
    bePatient: 'Mohon bersabar, proses dapat memakan waktu.',
    cancelTxSuccess: 'Anda telah berhasil membatalkan transaksi Anda.\nKoin Anda sedang dalam perjalanan.',
    creatingAuthenticator: 'Autentikator sedang dibuat',
    creatingAuthenticatorDescription:
      'Mohon bersabar sembari kami menyiapkan autentikator Anda. Proses ini dapat memakan waktu.',
    creatingWallet: 'Menyiapkan dompet Anda',
    creatingWalletDescription: 'Mohon bersabar sembari kami menyiapkan dompet Anda. Proses ini dapat memakan waktu.',
    generateAddressesError: 'Alamat tidak dapat dibuat ',
    hooray: 'Hore!',
    importingAuthenticator: 'Autentikator Anda sedang diimpor',
    importingAuthenticatorDescription:
      'Mohon bersabar sembari kami mengimpor autentikator Anda. Proses ini dapat memakan waktu.',
    noTransactions: 'Tidak ada transaksi ditemukan di dompet',
    noTransactionsDesc: 'Nampaknya Anda mencoba untuk mengimpor dompet yang belum pernah digunakan sebelumnya.',
    processing: 'Memproses',
    returnToAuthenticators: 'Kembali ke Autentikator ',
    returnToDashboard: 'Kembali ke Dasbor ',
    returnToWalletChoose: 'Kembali ke seleksi tipe dompet ',
    returnToWalletImport: 'Kembali ke impor dompet ',
    somethingWentWrong: 'Nampaknya ada yang salah',
    somethingWentWrongWhileCreatingWallet:
      'Ada yang salah keika kami mencoba untuk membuat dompet Anda. Mohon kembali ke Dasbor dan coba lagi.',
    success: 'Sukses',
    successfullWalletDelete: 'Dompet Anda telah berhasil dihapus. Anda dapat kembali ke Dasbor.',
    successfullWalletImport: 'Dompet Anda telah berhasil diimpor dan siap digunakan.',
    wrongMnemonic: 'Mnemonik salah',
    wrongMnemonicDesc:
      'Mnemonik Anda tidak cocok dengan dompet manapun. Anda mencoba untuk mengimpor mnemonik yang salah atau dompet yang belum pernah dipakai',
    goToWalletDetails: 'Pergi ke Detail Dompet ',
    successSubscription: 'Hore!\nAnda telah berlangganan notifikasi',
  },
  notifications: {
    addYourAddress: 'Tambahkan alamat email Anda',
    addYourEmailFor: 'Tambahkan alamat email Anda untuk menerima notifikasi',
    addEmail: 'Tambahkan email',
    addYourAddressDescription: 'email digunakan untuk mengirimi Anda notifikasi transaksi dari dompet yang dipilih.',
    addYourEmailForDescription:
      'Anda dapat menambahkan alamat email Anda. Email digunakan untuk mengirimi Anda notifikasi email dari dompet yang dipilih.',
    change: 'Ubah alamat email Anda.',
    title: 'Ubah konfigurasi notifikasi',
    yourEmail: 'Email Anda.',
    description:
      'Anda dapat mengubah Alamat Email Anda. Email digunakan untuk mengirimi Anda notifkasi dari dompet yang dipilih.',
    delete: 'Hapus email',
    invalidAddressError: 'Masukkan alamat email yang valid',
    yourSubscriptions: 'Langganan Anda',
    confirmEmail: 'Konfirmas alamat email',
    pleaseEnter: 'Masukkan kode yang kami kirim ke:',
    resend: 'Kirim kembali kode:',
    getNotification: 'Dapatkan notifikasi',
    chooseWalletsDescription: 'Pilih dompet yang ingin Anda tandai untuk menerima notifikasi transaksi',
    chooseWalletsToUnsubscribeDescription:
      'Anda berhenti berlangganan untuk menerima notifikasi dari dompet yang Anda pilih.',
    emailAddedSuccessMessage: 'Hore!\nAnda telah berhasil menambahkan alamat email.',
    goToNotifications: 'Pergi ke notifikasi',
    changeEmailTitle: 'Ubah email Anda.',
    changeEmailDescription:
      'Anda dapat merubah Alamat Email Anda. Email digunakan untuk mengirimi Anda notifikasi transaksi dari dompet yang dipilih.',
    yourCurrentEmail: 'Email yang terdaftar',
    theSameAddressError: 'Anda tidak dapat memasukkan email yang sudah terdaftar ',
    newEmail: 'Email Baru',
    confirmCurrentTitle: 'Konfirmasi alamat email Anda yang terdaftar sebelumnya',
    confirmNewTitle: 'Konfirmasi alamt email baru Anda',
    confirmNewDescription: 'Sekarang konfirmasi alamat email baru Anda. Mohon masukkan kode yang kami kirimkan ke ',
    emailChangedSuccessMessage: 'Hore! \nAnda telah berhasil memperbarui alamat email Anda.',
    updateNotificationPreferences: 'Hore! \nAnda telah berhasil memperbarui pengaturan notifikasi Anda.',
    verifyAction: 'Verifikasi aksi',
    verifyActionDescription: 'Untuk mengkonfirmasi permintaan, mohon masukkan kode yang kami kirim ke',
    deleteEmail: 'Hapus alamat email',
    deleteYourEmail: 'Hapus email Anda',
    deleteYourEmailDescription: 'Alamat Email Anda',
    deleteEmailSuccessMessage: 'Hore!\nAnda telah berhasil menghapus alamat email.',
    codeError: 'Mohon masukkan kode yang valid.\nAnda memiliki {atemptsLeft} kesempatan tersisa.',
    codeFinalError:
      'Anda telah memasukkan kode yang tidak valid sebanyak 3 kali.\nKami telah mengirimkan kode bary ke alamat email Anda.',
    walletSubscribedSuccessMessage:
      'Hore!\nAnda telah berhasil menambahkah alamat email dan berlangganan ke notifikasi.',
    no: 'Tidak',
    yes: 'Ya',
    notifications: 'Notifikasi',
    receiveTransactionDescription:
      'Apakah Anda ingin menerima notifikasi transaksi dari dompet ini ke alamat email Anda?',
    noteFirst: 'Catatan:',
    noteSecond: 'Apabila Anda ingin mengubah alamat email, Anda dapat melakukannya nanti di Pengaturan.',
    noSubscriptionDescription: 'Anda tidak terdaftar ke notifikasi manapun.',
    genericError: 'Nampaknya ada yang salah.\nKami mohon maaf.',
  },
  onboarding: {
    changePin: 'Ubah PIN',
    confirmNewPin: 'Konfirmasi PIN baru',
    confirmPassword: 'Konfirmasi kata sandi transaksi',
    confirmPin: 'Konfirmasi PIN',
    createNewPin: 'PIN Baru',
    createPassword: 'Buat kata sandi transaksi baru',
    addNotificationEmailDescription:
      'Apabila Anda ingin menerima notifikasi email, mohon masukkan alamat email Anda. Kami akan mengirimi Anda notifikasi mengenai status transaksi. Anda dapat merubahnya nanti di pengaturan.',
    createPasswordDescription:
      'Kata sandi transaksi Anda akan digunakan untuk memverifikasi semua transaksi. Kata sandi transaksi tidak dapat dirubah. Kata sand harus mengandung paling tidak 8 karakter alfanumerik.',
    createPin: 'Buat PIN',
    createPinDescription: 'PIN akan digunakan untuk masuk ke aplikasi. Anda dapat merubahnya bagian Pengaturan.',
    currentPin: 'PIN Terdaftar',
    failedTimes: 'Percobaan gagal',
    failedTimesErrorInfo: 'Setelah tiga percobaan gagal, Anda tidak akan bisa masuk selama:',
    goBack: 'Kembali',
    minutes: 'Menit.',
    numberOfAttemptsExceeded: 'Jumlah percobaan melebihi',
    onboarding: 'Onboarding',
    passwordDoesNotMatch: 'Kata sandi salah. Mohon masukkan kata sandi yang benar.',
    pin: 'PIN',
    pinDoesNotMatch: 'PIN salah. Mohon masukkan PIN yang benar.',
    seconds: 'Detik',
    successButton: 'Pergi ke Dasbor ',
    successButtonChangedPin: 'Kembali ke Pengaturan',
    successDescription: 'Hore!\nPIN Anda telah berhasil dibuat.',
    successDescriptionChangedPin: 'Hore!\nPIN Anda telah berhasil diubah.',
    tryAgain: 'Coba lagi setelah',
    resendCodeError:
      'Anda telah memasukkan PIN yang salah sebanyak 3 kami.\nKami telah mengirimkan kode baru ke alamat email Anda.',
    successCompletedDescription: 'Hore!\nAnda telah berhasil menyelesaikan proses onboarding.',
    successCompletedButton: 'Pergi Ke Dompet ',
  },
  receive: {
    details: {
      amount: 'Jumlah',
      receiveWithAmount: 'Terima dengan jumlah',
      receiveWithAmountSubtitle:
        'Masukkan jumlah yang ingin Anda terima. Kode QR akan diubah untuk memasukkan nilai yang akan ditransfer.',
      share: 'Bagikan',
      shareWalletAddress: 'Bagikan alamat dompet',
    },
    header: 'Terima koin',
    label: 'Alamat dompet ',
  },
  scanQrCode: {
    cancel: 'Batalkan',
    ok: 'Ok',
    permissionMessage: 'Kami membutuhkan izin untuk menggunakan kamera',
    permissionTitle: 'Izin untuk menggunakan kamera',
  },
  security: {
    jailBrokenPhone:
      'Kami mendeteksei bahwa perangkat Anda telah dijailbreak. Hal ini dapat menimbulkan masalah keamanan, crash, atau masalah lain. Kami tidak menyarankan untuk menggunakan GoldWallet di perangkat yang sudah di jailbreak.',
    noPinOrFingerprintSet:
      'PIN atau Kunci Sidik Jari tidak terpasang di perangakt Anda. Kami tidak merekomendasikan penggunaan aplikasi di perangkat yang tidak diamankan.',
    rootedPhone:
      'Kami mendeteksei bahwa perangkat Anda telah diroot. Hal ini dapat menimbulkan masalah keamanan, crash, atau masalah lain. Kami tidak menyarankan untuk menggunakan GoldWallet di perangkat yang sudah di jailbreak.',
    title: 'Masalah keamanan',
  },
  selectLanguage: {
    alertDescription: 'Pilih bahasa dan restart aplikasi?',
    cancel: 'Batalkan',
    confirm: 'Konfirmasi',
    confirmation: 'Konfirmasi',
    header: 'Bahasa',
    restartInfo: 'Restart Aplikasi GoldWallet dibutuhkan setelah Anda memilih bahasa baru untuk aplikasi Anda.',
  },
  send: {
    confirm: {
      availableBalance: 'Saldo tersedia setelah transaksi',
      cancelNow: 'Batalkan sekarang',
      pendingBalance: 'Saldo dibokir setelah transaksi',
      sendNow: 'Kirim sekarang',
    },
    create: {
      amount: 'Jumlah',
      fee: 'Biaya',
      headerText:
        'Ketika terdapat banyak transaksi pending dalam jaringan (jumlah transaksi >1500), Anda dapat memilih untuk membayar biaya transaksi yang lebih tinggi agar transaksi Anda diproses terlebih dahulu. Nilainya standarnya adalah 1-500 sat/b',
      setTransactionFee: 'Atur biaya transaksi',
    },
    details: {
      address: 'alamat ',
      address_field_is_not_valid: 'Bidang alamat tidak valid',
      amount_field_is_not_valid: 'Bidang jumlah tidak valid',
      amount_is_too_high:
        'Secara total hanya akan terdapat {maxCoinsinput} BTCV yang akan beredar, mohon jangan mencoba untuk mengirim lebih banyak!',
      amount_is_negative: 'Nilai tidak dapat negatif',
      amount_field_is_less_than_minSatoshi: 'Jumlah minimal yang dapat Anda kirim adalah 1 Satoshi',
      amount_placeholder: 'Jumlah yang akan dikirim (dalam BTCV)',
      cancel: 'Batalkan',
      create: 'Buat Invoice',
      create_tx_error:
        'Terdapat kesalahan ketika menyiapkan transaksi. Mohon pastikan bahwa alamat yang Anda masukkan valid',
      fee: 'Biaya:',
      fee_field_is_not_valid: 'Bidang biaya tidak valid',
      fee_placeholder: 'tambahan biaya transaksi (dalam BTCV)',
      feeUnit: 'Sat/B',
      next: 'Selanjutnya',
      note: 'Catatan (Opsional)',
      note_placeholder: 'Catatan untuk diri sendiri',
      remaining_balance: 'Saldo tersisa',
      scan: 'Pindai',
      send: 'Kirim',
      title: 'buat transaksi',
      to: 'ke',
      total_exceeds_balance: 'Jumlah yang akan dikirm melebihi saldo yang tersedia',
    },
    error: {
      doubleSpentFunds: 'Anda mencoba untuk menggunakan dana yang telah digunakan sebelumnya.',
      notExistingFunds: 'Anda mencoba untuk menggunaka dana yang tidak ada.',
      dust: 'Anda mencoba mengirim jumlah yang kecil',
      description: 'Sebelum melakukan transaksi, pertama Anda harus menambahkan sebuah Dompet Bitcoin Vault.',
      title: 'Error ',
    },
    header: 'Kirim koin',
    recovery: {
      confirmFirstSeed: 'Konfirmasi dengan Frasa Benih Pembatalan (Cancel Seed Phrase)',
      confirmFirstSeedDesc:
        'Buka dokumen PDF pertama yang dihasilkan ketika Anda membuat dompet dan menuliskan frasa benih Kunci Pribadi dalam urutan yang sama.',
      confirmSecondSeed: 'Konfirmasi dengan Frasa Benih Cepat (Fast Seed Phrase)',
      confirmSecondSeedDesc:
        'Buka dokumen PDF kedua yang dihasilkan ketika Anda membuat dompet dan menuliskan frasa benih Kunci Pribadi dalam urutan yang sama.',
      confirmSeed: 'Konfirmasi dengan Frasa Benih Pembatalan (Cancel Seed Phrase)',
      confirmSeedDesc:
        'Buka dokumen PDF yang dihasilkan ketika Anda membuat dompet dan menuliskan frasa benih Kunci Pribadi dalam urutan yang sama.',
      recover: 'Batalkan',
      useWalletAddress: 'Gunakan alamat milik dompet ini',
    },
    success: {
      description: 'Anda telah berhasil mengirimkan koin.',
      done: 'Selesai',
      return: 'Kembali ke Dasbor ',
      title: 'Sukses',
    },
    transaction: {
      alert: 'Aman',
      alertDesc:
        'Transaksi ini memerlukan konfirmasi sebanyak 144 blok atau sekitar 24 jam. Anda dapat membatalkannya dalam kurun waktu ini.',
      fastSuccess: 'Anda telah berhasil melakukan transaksi cepat.',
      instant: 'Aman Cepat ',
      instantDesc: 'Transaksi ini akan langsung dikonfirmasi. Mohon berhati-hati sebelum memilih opsi ini.',
      lightningError:
        'Alamat ini adalah sebuah alamat untuk Lightning Invoice. Mohon pergi ke Dompet Lightning Anda guna melakukan pembayaran untuk invoice ini. ',
      scanInstantKeyDesc:
        'Buka dokumen PDF yang dihasilkan ketika Anda membuat dompet dan pindai kode QR Kunci Pribadi untuk mengirimkan transaksi.',
      scanInstantKeyTitle: 'Pindai Kunci Cepat',
      type: 'Tipe Transaksi',
      watchOnlyError: 'Dompet Watch-only tidak dapat mengirim transaksi',
    },
    warning: 'Peringatan:',
    warningGeneral:
      'Mohon dicatat bahwa pada saat Anda menggunakan fitur Transaksi Aman, sebagian saldo ang tersisa di dompet Anda mungkin dapat diblokir. Ini adalah prosedur normal yang terikat dengan UTXO dan paramater blockchain dompet Bitcoin Vault. Saldo Anda akan kembali dibuka setelah transaksi berhasil diverifikasi (setelah kurang lebih 24 jam) atau dibatalkan (dalam waktu 24 jam).',
  },
  settings: {
    about: 'Tentang',
    terms: 'Syarat dan Privasi',
    aboutUs: 'Tentang kami',
    advancedOptions: 'Opsi Lanjutan',
    Biometrics: 'Ijinkan Biometrik',
    changePin: 'Ganti PIN',
    electrumServer: 'Server Electrum',
    FaceID: 'Izinkan FaceID',
    fingerprintLogin: 'Masuk dengan Sidik Jari',
    general: 'Umum',
    header: 'Pengaturan',
    language: 'Bahasa',
    notifications: 'Notifikasi',
    notSupportedFingerPrint: 'Perangkat Anda tidak mendukung sidik jari',
    security: 'Keamanan',
    TouchID: 'Izinkan Sidik Jadi',
  },
  tabNavigator: {
    addressBook: 'Buku Alamat',
    authenticators: 'Autentikator ',
    settings: 'Pengaturan',
    wallets: 'Dompet',
  },
  timeCounter: {
    closeTheApp: 'Tutup Aplikasi',
    description:
      'Aplikasi Anda telah diblokir karena adanya beberapa percobaan masuk yang gagal. Mohon tunggu beberapa waktu untuk mencoba kembali.',
    title: 'Aplikasi Diblokir ',
    tryAgain: 'Coba lagi',
  },
  transactions: {
    details: {
      addNote: 'Tambahkan catatan',
      addToAddressBook: 'Tambahkan ke Buku Alamat',
      amount: 'Jumlah',
      blocked: 'Diblokir ',
      bytes: 'bytes',
      confirmations: 'Konfirmasi ',
      copy: 'Salik',
      copyAndBoriadcast: 'Salin dan sebarkan nanti',
      details: 'Detail',
      detailTitle: 'Detail transaksi',
      fee: 'Biaya:',
      from: 'Dari',
      inputs: 'Input ',
      noLabel: 'Tidak ada label',
      note: 'Catatan',
      numberOfCancelTransactions: 'Jumlah Transaksi Batal',
      ouputs: 'Output',
      returnedFee: 'Biaya yang dikembalikan:',
      satoshiPerByte: 'Satoshi per byte',
      sendCoins: 'Kirim koin',
      timePending: 'Waktu pending',
      title: 'Transaksi',
      to: 'Ke',
      toExternalWallet: 'Ke dompet eksternal',
      toInternalWallet: 'ke dompet internal',
      totalReturnedFee: 'Total biaya yang dikembalikan:',
      transactioFee: 'Biaya transaksi',
      transactionDetails: 'Detail transaksi',
      transactionHex: 'Hex Transaksi',
      transactionHexDescription:
        'Ini adalah hex transaksi yang telah ditandatangani dan siap untuk disebarkan di jaringan.',
      transactionId: 'ID Transaksi',
      transactionType: 'Tipe Transaksi',
      txSize: 'Ukuran TX',
      unblocked: 'Blokir Dibuka',
      verify: 'Verfikasi di coinb.in',
      viewInBlockRxplorer: 'Tampilkan di penjelajah blok',
      walletType: 'Tipe Dompet',
    },
    errors: {
      notEnoughBalance: 'Saldo tidak mencukupi. Mohon coba untuk mengirim jumlah yang lebih sedikit.',
    },
    label: {
      blocked: 'Diblokir',
      canceled: 'Dibatalkan',
      canceledDone: 'Dibatalkan - selesai',
      done: 'selesai',
      pending: 'Pending ',
      unblocked: 'Blokir Dibuka',
    },
    list: {
      conf: 'Konfirmasi',
    },
    transactionTypeLabel: {
      canceled: 'Dibatalkan',
      secure: 'Aman',
      secureFast: 'Aman Cepat ',
      standard: 'Standar',
    },
  },
  unlock: {
    confirmButton: 'Konfirmasi Sidik Jari untuk melanjutkan.',
    enter: 'Masukkan PIN',
    title: 'Buka Kunci',
    touchID: 'Touch ID untuk "Gold Wallet"',
  },
  unlockTransaction: {
    description: 'Masukkan Kata Sandi Transaks untuk melanjutkan.',
    headerText: 'Konfirmasi Transaksi',
    title: 'Konfirmasi Transaksi',
  },
  wallets: {
    add: {
      addWalletButton: 'Tambahkan dompet baru',
      advancedOptions: 'Opsi lanjutan',
      air: 'Buat transaksi Aman, Pembatalan, dan Aman Cepat',
      ar: 'Buat transaksi Aman dan Pembatalan.',
      description: 'Pilih nama dan tipe dompet Anda.',
      failed: 'Pembuatan dompet gagal dilakukan',
      importWalletButton: 'Impor Dompet',
      inputLabel: 'Nama ',
      legacy: 'Atur tipe default transaksi.',
      legacyHDP2SH: 'Mengandung tiga alamat P2SH yang dibuat dari satu seed 12-kata',
      legacyHDP2SHTitle: 'HD P2SH Standar',
      LegacyHDSegWit: 'Mengandung pohon dari alamat native segwit yang dihasilkan dari satu seed 12-kata.',
      legacyHDSegWitTitle: 'HD SegWit Standar',
      LegacyP2SH: 'Mengandung satu alamat P2SH',
      legacyP2SHTitle: 'P2SH Standar',
      legacyTitle: 'Standar',
      multipleAddresses: 'Mengandung pohon dari alamat P2SH yang dihasilkan dari satu seed 12-kata',
      publicKeyError: 'Alamat publik tidak valid',
      segwidAddress: 'Mengandung pohon dari alamat native segwit yang dihasilkan dari satu seed 12-kata.',
      singleAddress: 'Mengandung satu alamat P2SH',
      subtitle: 'Nama dompet Anda ',
      title: 'Tambahkan dompet baru',
      walletType: 'Tipe dompet',
    },
    addSuccess: {
      description:
        'Tulis frasa benih ini dan simpan di tempat yang aman. Frasa ini berlaku sebagai backup/cadangan ketika Anda ingin memulihkan dompet Anda.',
      okButton: 'Ok, Saya telah menulis frasa benih.',
      subtitle: 'Dompet Anda sudah siap!\nAnda telah berhasil membuat dompet Anda!',
      title: 'Tambahkan dompet baru',
    },
    dashboard: {
      allWallets: 'Semua dompet',
      availableBalance: 'Saldo Tersedia',
      noTransactions: 'Tidak ada transaksi yang dapat ditunjukkan',
      noWallets: 'Tidak ada dompet ',
      noWalletsDesc1: 'Tidak ada dompet yang dapat ditunjukkan.',
      noWalletsDesc2: 'untuk menambahkan dompet pertama Anda.',
      receive: 'Terima',
      recover: 'Batalkan',
      send: 'Kirim',
      title: 'Dompet ',
      wallet: 'Dompet ',
    },
    deleteWallet: {
      description1: 'Apakah Anda yakin ingin menhapus?',
      description2: '? Anda tidak membalikkan/mengulangi proses.',
      header: 'Hapus dompet ',
      no: 'Tidak',
      title: 'Hapus dompet',
      yes: 'Ya',
    },
    details: {
      deleteWallet: 'Hapus dompet',
      details: 'Detail',
      edit: 'Ubah',
      exportWallet: 'Ekspor Dompet ',
      latestTransaction: 'Transaksi Terakhir ',
      nameEdit: 'Ubah nama',
      nameLabel: 'Nama ',
      showWalletXPUB: 'Tampilkan XPUB Dompet',
      typeLabel: 'Tipe ',
      subscribeWallet: 'Berlangganan ke notifikasi email',
      unsubscribeWallet: 'Berhenti berlangganan ke notifikasi email',
    },
    errors: {
      duplicatedPublicKey: 'Kunci publik telah ditambahkan',
      invalidMnemonic: 'Mnemonik salah',
      invalidMnemonicWordsNumber: 'Dituliskan\n{receivedWordsNumber}\nkata dibutuhkan\n{expectedWordsNumber}\n',
      invalidPrivateKey: 'Kunci Privat Salah',
      invalidPublicKey: 'Kunci Publik Salah',
      invalidQrCode: 'Kode QR Tidak Valid',
      invalidSign: 'Tidak dapat menandatangani transaksi',
      noIndexForWord: 'Tidak dapat menemukan index untuk kata:\n{word}',
      wrongNetwork:
        'Dompet Anda berada dalam jaringan {walletNetworkName} sedangkan aplikasi berada dalam jaringan {appNetworkName}. Mohon hubungi tim bantuan kami melalui Telegram.',
    },
    export: {
      title: 'ekspor dompet ',
    },
    exportWallet: {
      header: 'Ekspor dompet ',
      title: 'Frasa Benih',
    },
    exportWalletXpub: {
      header: 'XPUB Dompet ',
    },
    import: {
      do_import: 'Impor',
      error: 'Dompet gagal diimpor. Mohon pastikan bahwa data yang Anda tuliskan benar.',
      explanation:
        'Mohon tuliskan mnemonik, kunci pribat, WIF, atau apapun yang Anda punya disini. GoldWallet akan melakukan yang terbaik untuk menebak format yang benar dan mengimpor dompet Anda.',
      imported: 'Diimpor',
      scan_qr: 'atau pilih untuk memindai kode QR?',
      success: 'Sukses',
      title: 'Impor',
    },
    importWallet: {
      chooseTypeDescription: 'Pilih tipe dompet yang ingin Anda impor.',
      customWords: 'Kata buatan',
      extendWithCustomWords: 'Perpanjang benih ini dengan kata buatan',
      header: 'Impor dompet',
      import: 'Impor ',
      importARDescription1: 'Masukkan frasa benih',
      importARDescription2: 'pindai kode QR dompet yang ingin Anda impor',
      placeholder: 'Frasa benih',
      scanCancelPubKey: 'Pindai Kode QR Kunci Pembatalan',
      scanFastPubKey: 'Pindai Kode QR Kunci Cepat',
      scanPublicKeyDescription:
        'Buka dokumen PDF pertama yang dihasilkan ketika Anda membuat dompet yang ingin Anda impor dan gunakan aplikasi ini untuk memindai kode QR Kunci Publik.',
      scanQrCode: 'atau pindai kode QR',
      scanWalletAddress: 'Pindai alamat dompet ',
      scanWalletAddressDescription: 'Pindai kode QR Alamat Publik untuk mulai terintegrasi dengan GoldWallet',
      subtitle:
        'Tuliskan mnemonik, kunci privat, WIF, atau apapun yang Anda punya disini. GoldWallet akan melakukan yang terbaik untuk berusaha menebak format yang tepat dan mulai mengimpor dompet Anda.',
      title: 'Impor dompet Anda',
      unsupportedElectrumVaultMnemonic:
        'Benih ini berasal dari Electrum Vault dan untuk saat ini tidak didukung oleh aplikasi. Dukungan terhadap benih ini akan mulai diberikan di masa mendatang.',
      walletInUseValidationError: 'Dompet sudah digunakan. Mohon masukkan dompet yang valid.',
      allWalletsValidationError: 'Anda tidak bisa menggunakan nama "Semua Dompet/All Wallets"',
    },
    publicKey: {
      instantDescription:
        'Mohon sekali lagi kunjungi Generator Kunci web di perangkat yang berbeda, perbarui/refresh halaman dan gunakan aplikasi ini untuk memindai kode QR Kunci Publik baru. Jangan lupa untuk mengekspor kunci Anda dalam bentuk PDF.',
      instantSubtitle: 'Tambahkan Kunci Cepat',
      recoveryDescription:
        'Mohon kunjungi Generator Kunci web di perangkat yang berbeda dan gunakan aplikasi ini untuk memindai kode QR Kunci Publik baru. Jangan lupa untuk mengekspor kunci Anda dalam bentuk PDF.',
      recoverySubtitle: 'Tambahkan Kunci Pembatalan',
      scan: 'Pindai',
      webKeyGenerator: 'Generator Kunci Web:',
    },
    scanQrWif: {
      bad_password: 'Password Salah/Buruk',
      bad_wif: 'WIF Salah/Buruk',
      cancel: 'Batalkan',
      decoding: 'Decoding',
      go_back: 'Kembali',
      imported_legacy: 'Legacy Diimpor',
      imported_segwit: 'SegWit Diimpor',
      imported_watchonly: 'Watch-only Diimpor',
      imported_wif: 'WIF Diimpor ',
      input_password: 'Masukkan Kata Sandi',
      password_explain: 'Ini adalah kunci privat yang dienkripsi BIP38',
      wallet_already_exists: 'Dompet tersebut sudah ada',
      with_address: 'dengan alamat',
    },
    wallet: {
      latest: 'Transaksi Terbaru',
      none: 'Tidak ada ',
      pendingBalance: 'Saldo diblokir',
    },
    walletModal: {
      btcv: 'BTCV',
      wallets: 'Dompet ',
    },
  },
  connectionIssue: {
    noInternetTitle: 'Tidak ada koneksi internet ',
    noInternetDescription: 'Pastikan bahwa WI-FI atau mobile data Anda aktif, dan coba lagi.',
    offlineMessageTitle: 'Anda sedang diluar jaringan/offline',
    offlineMessageDescription: 'Sambungkan perangkat Anda ke internet untuk mengembalikan fungsi penuh aplikasi.',
    offlineMessageDescription2: 'Sambungkan perangkat Anda ke internet untuk kembali menggunakan fungsi ini.',
    noNetworkTitle: 'Tidak ada jaringan.',
    noNetworkDescription:
      'Internet Anda berfungsi, namun Anda tidak terhubung ke jaringan. Mohon tunggu sebentar dan coba lagi.',
    electrumXNotConnected: 'Klien Electrum tidak tersambung ',
    couldntConnectToServer: 'Tidak dapat tersambung ke server.',
  },
};
