module.exports = {
  _: {
    bad_password: '잘못된 패스워드, 다시 시도하십시오',
    cancel: '취소',
    click: '클릭',
    confirm: '확인',
    continue: '계속',
    copied: '복사됨!',
    copy: '복사',
    created: '생성 날짜:',
    delete: '삭제',
    details: '상세 정보',
    enter_password: '패스워드 입력',
    here: '여기',
    invalid: '유효하지 않음',
    languageCode: 'en',
    never: '다시 묻지 않음',
    next: '다음',
    ok: '확인',
    or: '혹은',
    satoshi: 'Sat',
    save: '저장',
    scan: '스캔',
    storage_is_encrypted: '저장소가 암호화되어 있습니다. 암호화를 해제하려면 패스워드가 필요합니다',
    skip: '이 단계 건너뛰기',
  },
  termsConditions: {
    header: '이용약관',
    title: '이용약관 동의',
    readTermsConditions: '이용약관을 읽었습니다',
    readPrivacyPolicy: '개인 정보 보호 정책을 읽었습니다',
    buttons: {
      agree: '동의합니다',
      disagree: '동의하지 않습니다',
    },
    modal: {
      header: '확실합니까?',
      text: '이용 약관에 동의하지 않으면 Gold Wallet 애플리케이션을 사용할 수 없습니다. \n정말 동의하지 않겠습니까?',
      noButton: '아니요, 동의합니다',
      yesButton: '네, 동의하지 않습니다',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: '본인 키를 항상 백업하십시오',
    buildWithAwesome: 'Build with awesome:',
    goToOurGithub: '당사 Github으로 이동',
    header: '소개',
    rateGoldWallet: 'Gold Wallet 평가하기',
    releaseNotes: '릴리스 노트',
    runSelfTest: '자가 테스트 실행',
    title: 'Gold Wallet은 무료이며 오픈 소스 Bitcoin Vault 지갑입니다. MIT 라이선스.',
  },
  advancedOptions: {
    description: '아래의 지갑 유형을 선택할 수 있도록 고급 옵션을 제공합니다:\n P2SH, HD P2SH, HD segwit.',
    title: '고급 옵션 설정',
  },
  authenticators: {
    add: {
      description:
        'Gold Wallet을 데스크톱 애플리케이션인 Electrum Vault와 페어링해야 합니다. 그러면 Gold Wallet을 이중 인증기로 사용할 수 있습니다. ',
      subdescription: '아래 옵션을 선택하면 본인의 인증기를 가져올 수 있습니다.',
      subtitle: '새로운 인증기 생성하기',
      successDescription:
        '이 시드 문구를 안전한 곳에 적어놓으십시오. 인증기를 복구해야 할 경우를 대비한 백업입니다. 인증기가 없으면 고속 거래나 취소 거래가 불가함을 알려드립니다.',
      successTitle: '인증기가 준비됐습니다!',
      title: '새로운 인증기 추가',
    },
    delete: {
      subtitle: '사용자 인증기 삭제',
      success: '사용자의 인증기가 삭제되었습니다. 언제든 새로운 인증기를 생성할 수 있습니다.',
      title: '인증기 삭제',
    },
    enterPIN: {
      description: '페어링 절차를 완료하려면 데스크톱 애플리케이션 Electrum Vault에 이 PIN을 입력하십시오.',
      subtitle: 'PIN을 입력하십시오',
    },
    errors: {
      noEmpty: '필수 입력 항목',
    },
    export: {
      title: '인증기 내보내기',
    },
    import: {
      code: '코드:',
      desc1: '시드 문구를 입력하시거나 가져올 인증기 코드를 스캔하십시오.',
      desc2: 'QR코드를 스캔하려면 아래의 [QR코드 스캔하기]를 클릭하십시오',
      inUseValidationError: '이름은 고유해야 합니다. 유효한 이름을 입력하십시오.',
      mnemonicLength: '니모닉에는 12개의 단어가 있어야 합니다',
      multipleQrCodesDescription:
        '일부 거래는 여러 QR 코드를 생성합니다. Electrum Vault 애플리케이션에서 모든 항목을 스캔해야 합니다.',
      multipleQrCodesTitle: '다른 QR코드 스캔',
      scanNext: '다음 코드 스캔하기',
      subtitle: '사용자 인증기 가져오기',
      success: '성공적으로 사용자의 인증기를 가져왔습니다. 이제 사용할 준비가 됐습니다.',
      textAreaPlaceholder: '시드 문구',
      title: '인증기 가져오기',
    },
    list: {
      noAuthenticators: '아직 인증기 없음',
      noAuthenticatorsDesc1: '탭 하여',
      noAuthenticatorsDesc2: '첫 번째 인증기 추가',
      scan: '스캔하기',
      title: 'Bitcoin Vault 인증기',
    },
    options: {
      delete: '인증기 삭제하기',
      export: '인증기 내보내기',
      pair: '인증기 페어링',
      sectionTitle: '일반',
      title: '인증기 옵션',
    },
    pair: {
      descPin: '이 PIN을 사용하여 데스크톱 애플리케이션에서 인증기 페어링을 확인합니다.',
      descPublicKey:
        '지갑을 생성하는 과정 중에 이 공개 키로 Gold Wallet 옵션을 사용하여 데스크톱 애플리케이션 인증기를 가져올 수 있습니다.',
      pin: 'PIN',
      publicKey: '공개 키',
      title: '인증기 페어링',
    },
    publicKey: {
      okButton: '네, 이해했습니다',
      subtitle:
        '2FA 지갑을 생성하는 동안, 이 공개 키를 사용하여 인증기를 Electrum Vault 데스크톱 애플리케이션으로 가져올 수 있습니다.',
      title: '공개 키',
    },
    sign: {
      error: '거래에 서명할 수 있는 인증기가 없습니다.',
    },
  },
  betaVersion: {
    button: '위험을 감수하겠습니다.',
    description:
      '공식 출시 전, 최종 테스트를 진행하고 있습니다. 모바일 앱 및 모바일 앱에 있는 모든 콘텐츠는 "있는 그대로" 및 "사용 가능한 대로" 제공됩니다. 소프트웨어 사용은 사용자의 책임하에 있습니다.',
    title: '이것은 Gold Wallet 베타버전입니다',
  },
  contactCreate: {
    addressLabel: '주소',
    buttonLabel: '새로운 연락처 추가하기',
    description: '새로운 연락처의 이름과 주소를 \n입력하십시오.',
    nameCannotContainSpecialCharactersError: '이름에 특수 기호를 포함할 수 없습니다.',
    nameCannotEmpty: '이름 필드는 비워둘 수 없습니다',
    nameLabel: '이름',
    nameMissingAlphanumericCharacterError: '이름에는 영숫자가 없습니다.',
    screenTitle: '새로운 연락처 추가',
    subtitle: '새로운 연락처',
    successButton: '주소록으로 돌아가기',
    successDescription: '만세! 성공입니다\n사용자 연락처를 추가했습니다',
    successTitle: '성공',
  },
  contactDelete: {
    description1: '정말 삭제하겠습니까',
    description2: '?\n되돌릴 수 없습니다.',
    header: '연락처 삭제하기',
    no: '아니요',
    success: '성공',
    successButton: '주소록으로 돌아가기',
    successDescription: '사용자 연락처가 성공적으로 삭제되었습니다.\n이제 주소록으로 돌아갈 수 있습니다.',
    title: '연락처 삭제',
    yes: '네',
  },
  contactDetails: {
    addressLabel: '주소',
    deleteButton: '연락처 삭제하기',
    editAddress: '주소 수정',
    editName: '이름 수정',
    nameLabel: '이름',
    sendCoinsButton: '코인 전송',
    share: '공유',
    showQRCodeButton: 'QR코드 표시',
  },
  contactList: {
    cancel: '취소',
    noContacts: '연락처 없음',
    noContactsDesc1: '표시할 연락처 없음 \n  클릭하여',
    noContactsDesc2: '첫 번째 연락처를 추가하십시오',
    noResults: '결과 없음',
    screenTitle: '연락처',
    search: '검색',
  },
  electrumServer: {
    connectionError: '제공된 Electrum 서버에 연결할 수 없습니다',
    description: '사용자 애플리케이션이 연결될 서버의 주소를 변경할 수 있습니다. 기본 주소를 권장합니다.',
    header: 'Electrum 서버',
    host: '호스트',
    port: '포트',
    save: '저장',
    successfullSave:
      '변경 사항이 성공적으로 저장되었습니다. 변경 사항이 적용되려면 시스템을 다시 시작해야 할 수도 있습니다.',
    title: 'Electrum 서버 변경',
    useDefault: '기본값 사용',
  },
  filterTransactions: {
    clearAll: '모두 지우기',
    clearFilters: '필터 지우기',
    filter: '필터',
    from: '발신',
    fromAmount: '전송 금액',
    fromDate: '전송 날짜',
    header: '거래 필터',
    receive: '수신',
    received: '수신됨',
    send: '전송',
    sent: '전송됨',
    status: {
      canceled: '취소됨',
      canceledDone: '취소 완료',
      done: '완료',
      pending: '보류',
    },
    to: '수신',
    toAmount: '전송할 금액',
    toDate: '전송 날짜',
    transactionStatus: '거래 상태',
    transactionType: '거래 유형',
  },
  message: {
    allDone: '모두 완료!',
    bePatient: '잠시만 기다려주십시오. 시간이 다소 소요될 수 있습니다.',
    cancelTxSuccess: '거래를 성공적으로 취소했습니다.\n해당 코인이 반환되고 있습니다.',
    creatingAuthenticator: '사용자 인증기 생성 중',
    creatingAuthenticatorDescription:
      '사용자 인증기를 생성하는 동안 잠시만 기다려 주십시오.\n시간이 다소 소요될 수 있습니다.',
    creatingWallet: '사용자 지갑 생성 중',
    creatingWalletSuccess: '지갑을 성공적으로 생성되었습니다.',
    creatingWalletDescription: '사용자 지갑을 생성하는 동안 잠시만 기다려 주십시오.\n시간이 다소 소요될 수 있습니다.',
    generateAddressesError: '주소를 생성할 수 없습니다',
    hooray: '만세!',
    importingAuthenticator: '사용자 인증기 가져오는 중',
    importingAuthenticatorDescription:
      '사용자 인증기를 가져오는 동안 잠시만 기다려 주십시오.\n시간이 다소 소요될 수 있습니다.',
    noTransactions: '지갑에 거래 내역이 없습니다.',
    noTransactionsDesc: '한 번도 사용한 적 없는 지갑을 가져오려고 시도한 것 같습니다.',
    processing: '처리 중',
    returnToAuthenticators: '인증기로 돌아가기',
    returnToDashboard: '대시보드로 돌아가기',
    returnToWalletChoose: '지갑 유형 선택으로 돌아가기',
    returnToWalletImport: '지갑 가져오기로 돌아가기',
    somethingWentWrong: '문제가 발생했습니다.',
    somethingWentWrongWhileCreatingWallet:
      '지갑을 생성하는 동안 문제가 발생했습니다. 대시보드로 돌아가서 다시 시도하십시오.',
    success: '성공',
    successfullWalletDelete: '지갑이 성공적으로 삭제됐습니다. 이제 대시보드로 돌아갈 수 있습니다.',
    successfullWalletImport: '사용자 지갑을 성공적으로 가져왔습니다. 이제 사용할 수 있습니다.',
    wrongMnemonic: '잘못된 니모닉',
    wrongMnemonicDesc:
      '니모닉이 어떤 지원하는 지갑과도 일치하지 않습니다. 잘못된 니모닉을 입력했거나 한 번도 사용하지 않은 지갑을 가져오려고 합니다.',
    goToWalletDetails: '지갑 상세 정보로 이동',
    successSubscription: '만세!\n알림을 성공적으로 설정했습니다.',
  },
  notifications: {
    addYourAddress: '사용자 이메일 주소를 추가하십시오',
    addYourEmailFor: '알림을 위해 사용자 이메일을 추가하십시오',
    addEmail: '이메일 추가',
    addYourAddressDescription: '선택한 지갑의 거래 알림을 위해 사용됩니다.',
    addYourEmailForDescription: '사용자 이메일 주소를 추가할 수 있습니다. 선택한 지갑의 거래 알림을 위해 사용됩니다.',
    change: '사용자 이메일을 변경하십시오',
    title: '알림을 설정하십시오',
    yourEmail: '사용자 이메일',
    description: '사용자 이메일 주소를 변경할 수 있습니다. 선택한 지갑의 거래 알림을 위해 사용됩니다.',
    delete: '이메일 삭제',
    invalidAddressError: '올바른 이메일 주소를 입력하십시오',
    yourSubscriptions: '가입 내역',
    confirmEmail: '사용자 이메일 주소 확인',
    pleaseEnter: '받은 코드를 입력하십시오:',
    resend: '코드 재전송',
    getNotification: '알림 받기',
    chooseWalletsDescription: '거래 알림을 설정할 지갑을 선택하십시오',
    chooseWalletsToUnsubscribeDescription: '거래 알림 설정을 해제할 지갑을 선택하십시오.',
    emailAddedSuccessMessage: '만세!\n사용자 이메일 주소를 추가했습니다.',
    goToNotifications: '알림으로 이동',
    changeEmailTitle: '사용자 이메일 변경',
    changeEmailDescription:
      '사용자 이메일 주소를 변경할 수 있습니다. 이메일은 선택한 지갑의 거래 알림을 위해 사용됩니다.',
    yourCurrentEmail: '현재 사용자 이메일',
    theSameAddressError: '현재 사용 중인 이메일 주소를 입력할 수 없습니다',
    newEmail: '새로운 이메일',
    confirmCurrentTitle: '현재 사용 중인 사용자 이메일 주소를 확인하십시오',
    confirmNewTitle: '새로운 사용자 이메일 주소를 확인하십시오',
    confirmNewDescription: '새로운 사용자 이메일 주소를 확인하십시오.\n받은 코드를 입력하십시오',
    emailChangedSuccessMessage: '만세!\n사용자 이메일 주소가 성공적으로 업데이트되었습니다.',
    updateNotificationPreferences: '야호!\n알림 기본 설정이 성공적으로 업데이트되었습니다.',
    verifyAction: '이 작업을 확인하십시오',
    verifyActionDescription: '요청을 확인하려면 받은 코드를 입력하십시오',
    deleteEmail: '이메일 주소를 삭제하십시오',
    deleteYourEmail: '사용자 이메일을 삭제하십시오',
    deleteYourEmailDescription: '사용자 이메일 주소',
    deleteEmailSuccessMessage: '만세!\n사용자 이메일 주소를 성공적으로 삭제했습니다.',
    codeError: '유효한 코드를 입력하십시오.\n이제 {attemptsLeft}번 더 시도할 수 있습니다.',
    codeFinalError: '잘못된 코드를 3번 입력했습니다.\n사용자 이메일 주소로 새로운 코드를 보냈습니다.',
    walletSubscribedSuccessMessage: '만세!\n사용자 이메일 주소를 성공적으로 추가했고 알림을 설정했습니다.',
    no: '아니요',
    yes: '네',
    notifications: '알림',
    receiveTransactionDescription: '이 지갑의 거래 알림을 사용자 이메일 주소로 받겠습니까',
    noteFirst: '참고:',
    noteSecond: '사용자 이메일 주소를 변경하려면 나중에 설정에서 변경할 수 있습니다.',
    noSubscriptionDescription: '설정한 알림이 없습니다.',
    genericError: '문제가 발생했습니다. 죄송합니다.',
    pushnotificationsSettings: {
      title: '앱 알림 허용',
      label: '설정',
    },
  },
  onboarding: {
    changePin: 'PIN 변경',
    confirmNewPin: '새로운 PIN 확인',
    confirmPassword: '거래 패스워드 확인',
    confirmPin: 'PIN 확인',
    createNewPin: '새로운 PIN',
    createPassword: '거래 패스워드 생성',
    addNotificationEmailDescription:
      '이메일 알림을 받으려면 이메일 주소를 입력하십시오. 사용자는 거래 상태에 대한 정보를 받을 수 있습니다. 나중에 설정에서 언제든지 변경할 수 있습니다.',
    createPasswordDescription:
      '거래 패스워드로 모든 거래를 승인할 수 있습니다. 해당 패스워드는 변경할 수 없습니다. 거래 패스워드는 최소 8자의 영숫자를 포함해야 합니다.',
    createPin: 'PIN 생성',
    createPinDescription: 'PIN을 사용하여 애플리케이션에 로그인할 수 있습니다. 나중에 설정에서 변경할 수 있습니다.',
    currentPin: '현재 PIN',
    failedTimes: '실패 횟수',
    failedTimesErrorInfo: '세 번의 시도가 실패하면, 다음 시간 동안 입력이 차단됩니다: ',
    goBack: '돌아가기',
    minutes: '분.',
    numberOfAttemptsExceeded: '시도 횟수 초과',
    onboarding: '온보딩',
    passwordDoesNotMatch: '패스워드가 일치하지 않습니다. 올바른 패스워드를 입력하십시오.',
    pin: 'PIN',
    pinDoesNotMatch: 'PIN이 일치하지 않습니다. 올바른 PIN을 입력하십시오.',
    seconds: '초',
    successButton: '대시보드로 이동',
    successButtonChangedPin: '설정으로 이동',
    successDescription: '만세!\n성공적으로 PIN을 생성했습니다.',
    successDescriptionChangedPin: '만세!\n성공적으로 PIN을 변경했습니다.',
    tryAgain: '다음 시간 이후 다시 시도하십시오:',
    resendCodeError: '잘못된 코드를 3번 입력했습니다.\n사용자 이메일 주소로 새로운 코드를 보냈습니다.',
    successCompletedDescription: '만세!\n성공적으로 온보딩 절차를 완료했습니다.',
    successCompletedButton: '지갑으로 이동',
  },
  receive: {
    details: {
      amount: '금액',
      receiveWithAmount: '금액으로 받기',
      receiveWithAmountSubtitle: '받을 금액을 입력하십시오. QR 코드는 금액에 따라 업데이트됩니다.',
      share: '공유',
      shareWalletAddress: '지갑 주소 공유',
    },
    header: '코인 받기',
    label: '지갑 주소',
  },
  scanQrCode: {
    cancel: '취소',
    ok: '확인',
    permissionMessage: '카메라 접근 권한이 필요합니다',
    permissionTitle: '카메라 접근 권한',
  },
  security: {
    jailBrokenPhone:
      '사용자 장치가 탈옥된 것으로 보입니다. 보안 문제, 충돌, 또든 기타 문제가 발생할 수 있습니다. 탈옥된 장치로의 Gold Wallet 사용은 권장하지 않습니다.',
    noPinOrFingerprintSet:
      '사용자 장치에 PIN 또는 지문이 설정되지 않은 것 같습니다. 보안되지 않은 장치로의 Gold Wallet 사용은 권장하지 않습니다.',
    rootedPhone:
      '사용자 장치가 루팅된 것으로 보입니다. 보안 문제, 충돌, 또는 기타 문제가 발생할 수 있습니다. 루팅된 기기로의 Gold Wallet 사용은 권장하지 않습니다.',
    title: '보안 문제',
  },
  selectLanguage: {
    alertDescription: '언어를 선택하고 애플리케이션을 다시 시작하겠습니까?',
    cancel: '취소',
    confirm: '확인',
    confirmation: '확인',
    header: '언어',
    restartInfo: '새로운 언어를 선택할 때, 변경 사항을 적용하려면 GoldWallet을 다시 시작해야 할 수 있습니다',
  },
  send: {
    confirm: {
      availableBalance: '거래 후 사용 가능 잔액',
      cancelNow: '지금 취소',
      pendingBalance: '거래 후 차단된 잔액',
      sendNow: '지금 전송',
    },
    create: {
      amount: '금액',
      fee: '수수료',
      headerText:
        '네트워크에 보류 중인 거래량이 많은 경우(>1500), 높은 수수료를 통해 사용자의 거래를 더 빨리 처리할 수 있습니다. 일반적인 값은 1~500sat/b입니다.',
      setTransactionFee: '거래 수수료 설정',
    },
    details: {
      address: '주소',
      address_field_is_not_valid: '잘못된 주소 필드',
      amount_field_is_not_valid: '잘못된 금액 필드',
      amount_is_too_high: '최대 {maxCoinsInput}BTCV가 있습니다. 해당 금액 이상은 전송할 수 없습니다!',
      amount_is_negative: '금액은 음수일 수 없습니다',
      amount_field_is_less_than_minSatoshi: '최소 전송 금액은 1 Satoshi입니다',
      amount_placeholder: '전송 금액 (BTCV)',
      cancel: '취소',
      create: '인보이스 생성',
      create_tx_error: '거래 생성 오류가 발생했습니다. 올바른 주소인지 확인하십시오.',
      fee: '수수료:',
      fee_field_is_not_valid: '잘못된 수수료 필드',
      fee_placeholder: '추가 거래 수수료(BTCV)',
      feeUnit: 'Sat/B',
      next: '다음',
      note: '노트(선택)',
      note_placeholder: '셀프 노트',
      remaining_balance: '잔액',
      scan: '스캔',
      send: '전송',
      title: '거래 생성',
      to: '수신',
      total_exceeds_balance: '전송 금액이 사용 가능 잔액을 초과합니다.',
    },
    error: {
      doubleSpentFunds: '이미 사용한 잔액을 사용하려고 합니다.',
      notExistingFunds: '존재하지 않는 자금을 사용하려고 합니다.',
      dust: '소액을 전송하려고 합니다',
      description: '거래를 생성하기 전에 먼저 Bitcoin Vault 지갑을 추가해야 합니다.',
      title: '오류',
    },
    header: '코인 전송',
    recovery: {
      confirmFirstSeed: '취소 시드 문구를 사용하여 확인',
      confirmFirstSeedDesc:
        '사용자 지갑을 만들 때 생성한 첫 번째 PDF 문서를 열고 개인 키 시드 문구를 같은 순서로 적습니다.',
      confirmSecondSeed: '고속 거래 시드 문구를 사용하여 확인',
      confirmSecondSeedDesc:
        '지갑 만들 때 생성된 두 번째 PDF 문서를 열고 같은 방식으로 개인 키(Private Key)와 시드 문구를 입력하세요.',
      confirmSeed: '시드 문구 취소 동의하기',
      confirmSeedDesc: '사용자 지갑을 만들 때 생성한 PDF 문서를 열고 개인 키 시드 문구를 같은 순서로 적습니다.',
      recover: '취소',
      useWalletAddress: '이 지갑 주소 사용',
    },
    success: {
      description: '코인을 성공적으로 전송했습니다.',
      done: '완료',
      return: '대시보드로 돌아가기',
      title: '성공',
    },
    transaction: {
      alert: '보안 거래',
      alertDesc: '이 거래가 확인되려면 144블록 또는 약 24시간이 필요합니다. 이 시간 안에 거래를 취소할 수 있습니다.',
      fastSuccess: '고속 거래를 성공적으로 완료했습니다.',
      instant: '보안 고속 거래',
      instantDesc: '이 거래는 즉시 확인될 것입니다. 사용에 각별히 주의해야 합니다.',
      lightningError:
        '이 주소는 Lightning 인보이스 전용 주소로 보입니다. 해당 인보이스의 결제를 진행하려면 Lightning 지갑으로 이동하십시오.',
      scanInstantKeyDesc: '지갑을 만들 때 생성한 PDF 문서를 열고 개인 키 QR 코드를 스캔하여 거래를 전송합니다.',
      scanInstantKeyTitle: '빠른 키 스캔',
      type: '거래 유형',
      watchOnlyError: '읽기 전용 지갑은 거래를 전송할 수 없습니다..',
    },
    warning: '경고:',
    warningGeneral:
      '보안 거래 기능을 사용하는 과정에서 지갑에 남아 있는 자금의 일부가 차단될 수 있습니다. 이것은 UTXO와 Bitcoin Vault 지갑의 블록체인 한도와 연동되는 일반적인 절차입니다. 거래가 확인(약 24시간 후)되거나 취소(24시간 이내)되면 자금의 차단이 해제됩니다.',
  },
  settings: {
    about: '소개',
    terms: '이용약관',
    factoryReset: '공장 초기화',
    aboutUs: '회사 소개',
    advancedOptions: '고급 옵션',
    Biometrics: '생체 인식 허용',
    changePin: 'PIN 변경',
    electrumServer: 'Electrum 서버',
    FaceID: 'FaceID 허용',
    fingerprintLogin: '지문 인식 로그인',
    general: '일반',
    header: '설정',
    language: '언어',
    notifications: '알림',
    notSupportedFingerPrint: '사용자 장치가 지문 인식을 지원하지 않습니다.',
    security: '보안',
    TouchID: '지문 인식 허용',
    factory: {
      title: '공장 초기화',
      text:
        'Gold Wallet을 공장 초기화 하시겠습니까? 사용자의 모든 지갑과 데이터가 모두 삭제됩니다. 사용자의 지갑을 전부 다시 가져와야 한다는 것을 명심하십시오.',
      noButton: '아니요',
      yesButton: '네',
    },
  },
  tabNavigator: {
    addressBook: '주소록',
    authenticators: '인증기',
    settings: '설정',
    wallets: '지갑',
  },
  timeCounter: {
    closeTheApp: '애플리케이션 종료',
    description: '로그인 시도가 실패하여 애플리케이션이 차단되었습니다. 다시 시도하기 위해 필요한 시간을 기다리십시오.',
    title: '애플리케이션 차단됨',
    tryAgain: '다시 시도하십시오',
  },
  transactions: {
    details: {
      addNote: '노트 추가',
      addToAddressBook: '주소록에 추가',
      amount: '금액',
      blocked: '차단됨',
      bytes: 'bytes',
      confirmations: '확인',
      copy: '복사',
      copyAndBoriadcast: '복사 후 나중에 브로드캐스트',
      details: '상세 정보',
      detailTitle: '거래 상세 정보',
      fee: '수수료:',
      from: '발신',
      inputs: '입력',
      noLabel: '레이블 없음',
      note: '노트',
      numberOfCancelTransactions: '취소 거래 수',
      ouputs: '출력',
      returnedFee: '반환된 수수료:',
      satoshiPerByte: 'byte당 Satoshi',
      sendCoins: '코인 전송',
      timePending: '보류 시간',
      title: '거래',
      to: '수신',
      toExternalWallet: '외부 지갑으로',
      toInternalWallet: '내부 지갑으로',
      totalReturnedFee: '총 반환 수수료:',
      transactioFee: '거래 수수료',
      transactionDetails: '거래 상세 정보',
      transactionHex: '거래 16진수',
      transactionHexDescription: '이것은 거래 16진수이며 서명되어 네트워크에 브로드캐스트할 준비가 되었습니다.',
      transactionId: '거래 ID',
      transactionType: '거래 유형',
      txSize: 'TX 크기',
      unblocked: '차단 해제됨',
      verify: 'coinb.in에서 인증',
      viewInBlockRxplorer: '블록 익스플로러에서 보기',
      walletType: '지갑 유형',
    },
    errors: {
      notEnoughBalance: '잔액 부족. 더 적은 금액으로 다시 전송해보십시오.',
    },
    label: {
      blocked: '차단됨',
      canceled: '취소됨',
      canceledDone: '취소됨 - 완료',
      done: '완료',
      pending: '보류',
      unblocked: '차단 해제됨',
    },
    list: {
      conf: '확인',
    },
    transactionTypeLabel: {
      canceled: '취소됨',
      secure: '보안 거래',
      secureFast: '보안 고속 거래',
      standard: '일반 거래',
    },
  },
  unlock: {
    confirmButton: '계속하려면 지문을 확인하십시오.',
    enter: 'PIN 입력',
    title: '차단 해제',
    touchID: '"Gold Wallet" 용 Touch ID ',
  },
  unlockTransaction: {
    description: '계속하려면 거래 패스워드를 입력하십시오.',
    headerText: '거래 확인',
    title: '거래 확인',
  },
  wallets: {
    add: {
      createWalletButton: '새로운 지갑 생성하기',
      advancedOptions: '고급 옵션',
      air: '보안 거래, 취소 거래, 보안 고속 거래를 진행합니다.',
      ar: '보안 거래, 취소 거래를 진행합니다.',
      description: '지갑 이름과 유형을 선택하십시오.',
      failed: '지갑 생성 실패',
      importWalletButton: '지갑 가져오기',
      inputLabel: '이름',
      legacy: '기본 유형의 거래를 진행합니다.',
      legacyHDP2SH: '단일 12단어 시드에서 생성된 P2SH 주소 트리를 포함합니다.',
      legacyHDP2SHTitle: '표준 HD P2SH',
      LegacyHDSegWit: '단일 12단어 시드에서 생성된 네이티브 Segwit 주소 트리를 포함합니다.',
      legacyHDSegWitTitle: '표준 HD SegWit',
      LegacyP2SH: '단일 P2SH 주소를 포함합니다.',
      legacyP2SHTitle: '표준 P2SH',
      legacyTitle: '표준',
      multipleAddresses: '단일 12단어 시드에서 생성된 P2SH 주소 트리를 포함합니다.',
      publicKeyError: '제공된 공개 키가 잘못되었습니다',
      segwidAddress: '단일 12단어 시드에서 생성된 네이티브 segwit 주소 트리를 포함합니다.',
      singleAddress: '단일 P2SH 주소를 포함합니다.',
      subtitle: '지갑 이름 설정',
      title: '새로운 지갑 추가',
      walletType: '지갑 유형',
    },
    confirmSeed: {
      header: '시드 문구 확인',
      title: '백업 문구를 확인하십시오',
      description: '올바른 순서대로 단어를 클릭하여 사용자 백업을 확인하십시오.',
      button: '확인',
      error: '시드 문구 순서가 올바르지 않습니다.',
    },
    addSuccess: {
      description: '이 시드 문구를 안전한 곳에 적어두십시오. 지갑을 복구해야 할 경우를 대비한 백업입니다.',
      okButton: '네, 적어두었습니다.',
      subtitle: '사용자 지갑이 준비되었습니다!\n사용자 지갑을 생성하였습니다!',
      title: '새로운 지갑 추가',
    },
    dashboard: {
      allWallets: '모든 지갑',
      availableBalance: '사용 가능 잔액',
      noTransactions: '표시할 거래 없음',
      noWallets: '지갑 없음',
      noWalletsDesc1: '표시할 지갑 없음.\n첫 지갑 추가하기',
      noWalletsDesc2: '첫 번째 지갑 추가',
      receive: '수신',
      recover: '취소',
      send: '전송',
      title: '지갑',
      wallet: '지갑',
    },
    deleteWallet: {
      description1: '정말 삭제하겠습니까',
      description2: '? 되돌릴 수 없습니다.',
      header: '지갑 삭제',
      no: '아니요',
      title: '사용자 지갑 삭제',
      yes: '네',
    },
    details: {
      deleteWallet: '지갑 삭제',
      details: '상세 정보',
      edit: '수정',
      exportWallet: '지갑 내보내기',
      latestTransaction: '최근 거래',
      nameEdit: '이름 수정',
      nameLabel: '이름',
      showWalletXPUB: '지갑 XPUB 표시',
      typeLabel: '유형',
      subscribeWallet: '이메일 알림 설정',
      unsubscribeWallet: '이메일 알림 설정 해제',
    },
    errors: {
      duplicatedPublicKey: '해당 공개 키는 이미 추가되었습니다',
      invalidMnemonic: '잘못된 니모닉',
      invalidMnemonicWordsNumber: '{receivedWordsNumber}단어 제공됨 {expectedWordsNumber}단어 예상됨',
      invalidPrivateKey: '잘못된 개인 키',
      invalidPublicKey: '잘못된 공개 키',
      invalidQrCode: '잘못된 QR 코드',
      invalidSign: '거래에 서명할 수 없음',
      noIndexForWord: '다음 단어의 인덱스를 찾을 수 없음: {word}',
      wrongNetwork:
        '앱 네트워크가 {appNetworkName}인 반면, 지갑은 {walletNetworkName} 네트워크에 있습니다. Telegram을 통해 저희 서포트 팀에 연락하시기 바랍니다.',
    },
    export: {
      title: '지갑 내보내기',
    },
    exportWallet: {
      header: '지갑 내보내기',
      title: '시드 문구',
    },
    exportWalletXpub: {
      header: '지갑 XPUB ',
    },
    import: {
      do_import: '가져오기',
      error: '가져오기 실패. 올바른 데이터를 입력했는지 확인하십시오.',
      explanation:
        '여기에 니모닉, 개인 키, WIF 등 가지고 있는 모든 것을 입력하십시오. Gold Wallet은 올바른 형식을 추측하고 지갑을 가져오기 위해 최선을 다할 것입니다. ',
      imported: '가져옴',
      scan_qr: '또는 QR 코드를 스캔하겠습니까?',
      success: '성공',
      title: '가져오기',
    },
    importWallet: {
      chooseTypeDescription: '가져오려는 지갑 유형을 선택하십시오..',
      customWords: '커스텀 단어',
      extendWithCustomWords: '커스텀 단어로 이 시드를 확장하십시오',
      header: '지갑 가져오기',
      import: '가져오기',
      importARDescription1: '시드 문구를 입력하십시오',
      importARDescription2: '가져오려는 지갑의 QR 코드를 스캔하십시오',
      placeholder: '시드 문구',
      scanCancelPubKey: '취소 키 QR 코드를 스캔하십시오',
      scanFastPubKey: '빠른 키 QR 코드를 스캔하십시오',
      scanPublicKeyDescription:
        '가져오려는 지갑을 만들 때 생성된 첫 PDF 문서를 열고 이 애플리케이션을 사용하여 공개 키 QR 코드를 스캔하십시오.',
      scanQrCode: '또는 QR 코드 스캔',
      scanWalletAddress: '지갑 주소 스캔',
      scanWalletAddressDescription: 'GoldWallet 통합을 시작하려면 공개 키 QR코드를 스캔하십시오.',
      subtitle:
        '여기에 니모닉, 개인 키, WIF 등 가지고 있는 모든 것을 입력하십시오. Gold Wallet은 올바른 형식을 추측하고 지갑을 가져오기 위해 최선을 다할 것입니다. ',
      title: '사용자 지갑 가져오기',
      unsupportedElectrumVaultMnemonic:
        '이 시드는 Electrum Vault에서 가져왔으며 현재 지원되지 않습니다. 곧 지원될 예정입니다.',
      walletInUseValidationError: '지갑이 이미 사용 중입니다. 올바른 지갑을 입력하십시오.',
      allWalletsValidationError: '"모든 지갑"이라는 이름은 입력할 수 없습니다',
    },
    publicKey: {
      instantDescription:
        '별도의 장치에서 Key Generator 웹으로 다시 이동하여 페이지를 새로 고친 후 이 앱을 사용하여 새로운 공개 키 QR 코드를 스캔하십시오. PDF로 키를 내보내는 것을 잊지 마십시오!',
      instantSubtitle: '빠른 키 추가',
      recoveryDescription:
        '별도의 장치에서 Key Generator 웹으로 이동하고 이 앱을 사용하여 새로운 공개 키 QR 코드를 스캔하십시오. PDF로 키를 내보내는 것을 잊지 마십시오!',
      recoverySubtitle: '취소 키 추가',
      scan: '스캔',
      webKeyGenerator: 'Key Generator 웹:',
    },
    scanQrWif: {
      bad_password: '잘못된 패스워드',
      bad_wif: '잘못된 WIF',
      cancel: '취소',
      decoding: '디코딩',
      go_back: '돌아가기',
      imported_legacy: '가져온 Legacy',
      imported_segwit: '가져온 SegWit',
      imported_watchonly: '가져온 읽기 전용',
      imported_wif: '가져온 WIF',
      input_password: '비밀번호 입력',
      password_explain: '이것은 BIP38로 암호화된 개인 키입니다',
      wallet_already_exists: '이미 해당 지갑이 주소와 ',
      with_address: '함께 있습니다. ',
    },
    wallet: {
      latest: '최근 거래',
      none: '없음',
      pendingBalance: '차단된 잔액',
    },
    walletModal: {
      btcv: 'BTCV',
      wallets: '지갑',
    },
  },
  connectionIssue: {
    noInternetTitle: '인터넷 연결 없음',
    noInternetDescription: 'WI-FI 또는 모바일 데이터가 켜져 있는지 확인한 후 다시 시도하십시오.',
    offlineMessageTitle: '오프라인 상태입니다.',
    offlineMessageDescription: '전체 기능을 복원하려면 인터넷에 연결하십시오.',
    offlineMessageDescription2: '해당 기능을 계속 사용하려면 인터넷에 연결하십시오.',
    noNetworkTitle: '네트워크 없음',
    noNetworkDescription: '인터넷은 작동하지만, 네트워크에 연결되어 있지 않습니다. 잠시 기다린 후 다시 시도하십시오.',
    electrumXNotConnected: 'Electrum 클라이언트가 연결되어 있지 않습니다.',
    couldntConnectToServer: '서버에 연결할 수 없습니다.',
  },
};
