module.exports = {
  _: {
    bad_password: 'Palavra-passe errada, tente novamente',
    cancel: 'Cancelar',
    click: 'Clique',
    confirm: 'Confirmar',
    continue: 'Continuar',
    copied: 'Copiado!',
    copy: 'Copiar',
    created: 'Criado em',
    delete: 'Eliminar',
    details: 'Detalhes',
    enter_password: 'Introduza a palavra-chave',
    here: 'aqui',
    invalid: 'Inválido',
    languageCode: 'en',
    never: 'nunca',
    next: 'Seguinte',
    ok: 'OK',
    or: 'ou',
    satoshi: 'Sat',
    save: 'Guardar',
    scan: 'Scan',
    storage_is_encrypted: 'O seu armazenamento está encriptado. É necessária uma palavra-passe para a desencriptar',
    skip: 'Saltar este passo',
  },
  termsConditions: {
    header: 'Termos e Condições',
    title: 'Aceitar os Termos',
    readTermsConditions: 'Eu li os Termos e Condições',
    readPrivacyPolicy: 'Eu li a Política de Privacidade',
    buttons: {
      agree: 'Eu aceito',
      disagree: 'Eu não aceito',
    },
    modal: {
      header: 'Tem a certeza?',
      text:
        'Note que se não aceitar os nossos Termos e Condições não poderá utilizar a aplicação Gold Wallet.\nTem a certeza de que não quer aceitar?',
      noButton: 'Não, decidi mudar de ideias.',
      yesButton: 'Sim, eu não aceito',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: 'Faça sempre uma cópia de segurança das suas chaves',
    buildWithAwesome: 'Construir com espetacularidade:',
    goToOurGithub: 'Ir ao nosso Github',
    header: 'Sobre nós',
    rateGoldWallet: 'Avaliar a GoldWallet',
    releaseNotes: 'Notas de lançamento',
    runSelfTest: 'Executar o autoteste',
    title: 'A Gold wallet é uma carteira Bitcoin Vault gratuita e de fonte aberta. Licenciada pelo MIT.',
  },
  advancedOptions: {
    description:
      'A ativação de opções avançadas irá  permitir-lhe escolher entre os tipos de carteira na lista abaixo:\nP2SH, HD P2SH, HD segwit. ',
    title: 'Configurar opções avançadas',
  },
  authenticators: {
    add: {
      description:
        'Vai precisar dela para emparelhar a Gold Wallet  com a aplicação desktop para computador Electrum Vault. Servirá como autenticação de dois factores.',
      subdescription: 'Também pode importar o seu autenticador, escolhendo a opção abaixo.',
      subtitle: 'Criar novo autenticador',
      successDescription:
        'Escreva esta frase-semente em algum lugar seguro. É a sua cópia de segurança no caso de necessitar de restaurar o seu autenticador. Lembre-se de que o autenticador é necessário para confirmar as transações Rápidas e de Cancelamento.',
      successTitle: 'O seu autenticador está pronto!',
      title: 'Adicionar novo autenticador',
    },
    delete: {
      subtitle: 'Apague o seu autenticador',
      success: 'O seu autenticador foi eliminado com sucesso. Pode sempre criar um novo.',
      title: 'Eliminar o autenticador',
    },
    enterPIN: {
      description:
        'Introduzir este PIN na aplicação desktop para computador Electrum Vault para terminar o processo de emparelhamento.',
      subtitle: 'Introduzir o PIN',
    },
    errors: {
      noEmpty: 'O campo não pode ficar vazio',
    },
    export: {
      title: 'Autenticador de exportação',
    },
    import: {
      code: 'Código:',
      desc1: 'Escreva a frase-semente ou faça o scan ao código QR do autenticador que pretende importar.',
      desc2: 'faça o scan do código QR clicando em "ou faça o scan do código QR" abaixo',
      inUseValidationError: 'O nome deve ser único. Por favor, introduza um nome válido.',
      mnemonicLength: 'Mnemónica deve ter 12 palavras',
      multipleQrCodesDescription:
        'Algumas transações geram múltiplos códigos QR. Assegure-se de scanear todos eles a partir da aplicação Electrum Vault.',
      multipleQrCodesTitle: 'Fazer o scan de outro código QR',
      scanNext: 'Scan o seguinte',
      subtitle: 'Importe o seu autenticador',
      success: 'Importou com sucesso o seu autenticador. Está agora pronto a ser utilizado.',
      textAreaPlaceholder: 'Frase-semente',
      title: 'Autenticador de importação',
    },
    list: {
      noAuthenticators: 'Ainda sem Autenticadores',
      noAuthenticatorsDesc1: 'Toque',
      noAuthenticatorsDesc2: 'para adicionar o seu primeiro autenticador.',
      scan: 'Scan',
      title: 'Autenticadores Bitcoin Vault',
    },
    options: {
      delete: 'Apagar autenticador',
      export: 'Autenticador de exportação',
      pair: 'Autenticador de pares',
      sectionTitle: 'Geral',
      title: 'Opções de autenticação',
    },
    pair: {
      descPin:
        'Utilize este PIN para confirmar o emparelhamento do autenticador na sua aplicação desktop para computador.',
      descPublicKey:
        'Pode utilizar esta Chave Pública para importar o seu autenticador na aplicação desktop para computador durante o processo de criação da carteira com a opção GoldWallet.',
      pin: 'PIN',
      publicKey: 'Chave Pública',
      title: 'Autenticador de pares',
    },
    publicKey: {
      okButton: 'OK, eu compreendo',
      subtitle:
        'Pode utilizar esta Chave Pública para importar o seu autenticador para a aplicação desktop para computador Electrum Vault durante a criação da carteira 2FA.',
      title: 'Chave Pública',
    },
    sign: {
      error: 'Nenhum dos autenticadores foi capaz de assinar a transação',
    },
  },
  betaVersion: {
    button: 'Eu aceito o risco',
    description:
      'Está ainda a ser submetido a testes finais antes do seu lançamento oficial. A aplicação móvel e todo o conteúdo nela encontrado são fornecidos com base no "como está" e "como disponível". A utilização do software é feita por conta e risco do próprio utilizador.',
    title: 'Esta é uma versão beta\n da GoldWallet',
  },
  contactCreate: {
    addressLabel: 'Endereço',
    buttonLabel: 'Acrescentar novo contacto',
    description: 'Por favor introduza nome e endereço\npara o seu novo contacto.',
    nameCannotContainSpecialCharactersError: 'O nome não pode conter caracteres especiais.',
    nameCannotEmpty: 'O campo do nome não pode estar vazio.',
    nameLabel: 'Nome',
    nameMissingAlphanumericCharacterError: 'Falta um caractere alfanumérico ao nome.',
    screenTitle: 'Adicionar novo contacto',
    subtitle: 'Novo contacto',
    successButton: 'Voltar ao livro de endereços',
    successDescription: 'Viva! Você conseguiu\nadicionou o seu contacto.',
    successTitle: 'Sucesso',
  },
  contactDelete: {
    description1: 'Tem a certeza que quer eliminar',
    description2: '? Não será possível reverter a situação.',
    header: 'Apagar contacto',
    no: 'Não',
    success: 'Sucesso',
    successButton: 'Voltar ao livro de endereços',
    successDescription: 'O seu contacto foi eliminado com sucesso.\n Pode agora regressar à lista de endereços.',
    title: 'Elimine o seu contacto',
    yes: 'Sim',
  },
  contactDetails: {
    addressLabel: 'Endereço',
    deleteButton: 'Eliminar contacto',
    editAddress: 'Editar endereço',
    editName: 'Editar nome',
    nameLabel: 'Nome',
    sendCoinsButton: 'Enviar moedas',
    share: 'Partilhar',
    showQRCodeButton: 'Mostrar código QR',
  },
  contactList: {
    cancel: 'Cancelar',
    noContacts: 'Sem contactos',
    noContactsDesc1: 'Sem contactos para mostrar. \n Clique',
    noContactsDesc2: 'para adicionar o seu primeiro contacto.',
    noResults: 'Não existem resultados para o',
    screenTitle: 'Livro de endereços',
    search: 'Pesquisa',
  },
  electrumServer: {
    connectionError: 'Não se consegue ligar ao servidor Electrum fornecido',
    description:
      'Pode alterar o endereço do servidor a que a sua aplicação se ligará. O endereço predefinido é recomendado.',
    header: 'Servidor Electrum',
    host: 'host',
    port: 'port',
    save: 'Guardar',
    successfullSave:
      'As suas alterações foram guardadas com sucesso. Poderá ser necessário reiniciar para que as alterações tenham efeito.',
    title: 'Mudar servidor Electrum',
    useDefault: 'Usar o predefinido',
  },
  filterTransactions: {
    clearAll: 'Limpar tudo',
    clearFilters: 'Limpar filtros',
    filter: 'Filtrar',
    from: 'De',
    fromAmount: 'Do montante',
    fromDate: 'Da data',
    header: 'Filtrar transações',
    receive: 'Receber',
    received: 'Recebido',
    send: 'Enviar',
    sent: 'Enviado',
    status: {
      canceled: 'Cancelado',
      canceledDone: 'Cancelado - feito',
      done: 'Feito',
      pending: 'Pendente',
    },
    to: 'A',
    toAmount: 'Ao montante',
    toDate: 'Até à data',
    transactionStatus: 'Estado da transação',
    transactionType: 'Tipo de transação',
  },
  message: {
    allDone: 'Tudo feito!',
    bePatient: 'Por favor, seja paciente, pode demorar algum tempo.',
    cancelTxSuccess: 'A sua transação foi cancelada com sucesso.\n As suas moedas estão a caminho.',
    creatingAuthenticator: 'Criar o seu autenticador',
    creatingAuthenticatorDescription:
      'Por favor, seja paciente enquanto criamos o seu autenticador.\n Pode demorar algum tempo.',
    creatingWallet: 'Criar a sua carteira',
    creatingWalletSuccess: 'Criou com sucesso a sua carteira.',
    creatingWalletDescription:
      'Por favor, seja paciente enquanto nós criamos a sua carteira.\n Pode demorar algum tempo.',
    generateAddressesError: 'Não pode gerar endereços',
    hooray: 'Viva!',
    importingAuthenticator: 'Importando o seu autenticador',
    importingAuthenticatorDescription:
      'Por favor, seja paciente enquanto importamos o seu autenticador.\n Pode demorar algum tempo.',
    noTransactions: 'Nenhuma transação encontrada na carteira',
    noTransactionsDesc: 'Provavelmente está a tentar importar uma carteira que nunca foi utilizada',
    processing: 'A processar',
    returnToAuthenticators: 'Voltar aos Autenticadores',
    returnToDashboard: 'Voltar ao Painel de Controlo',
    returnToWalletChoose: 'Voltar à seleção do tipo de carteira',
    returnToWalletImport: 'Voltar à importação de carteiras',
    somethingWentWrong: 'Algo correu mal',
    somethingWentWrongWhileCreatingWallet:
      'Algo correu mal enquanto estávamos a criar a sua carteira. Por favor, volte ao Painel de Controlo e tente novamente.',
    success: 'Sucesso',
    successfullWalletDelete: 'A sua carteira foi apagada com sucesso. Pode agora regressar ao Painel de Controlo.',
    successfullWalletImport: 'A sua carteira foi importada com sucesso. Está agora pronta a ser utilizada.',
    wrongMnemonic: 'Mnemónica errada',
    wrongMnemonicDesc:
      'A sua mnemónica não corresponde a nenhuma carteira suportada. Está a tentar importar uma mnemónica ou carteira inválida que nunca foi utilizada',
    goToWalletDetails: 'Ir para Detalhes da carteira',
    successSubscription: 'Viva!\n Subscreveu com sucesso as notificações.',
  },
  notifications: {
    addYourAddress: 'Adicione o seu endereço de e-mail',
    addYourEmailFor: 'Adicione o seu e-mail para notificações',
    addEmail: 'Adicionar e-mail',
    addYourAddressDescription:
      'É utilizado para lhe enviar notificações de transações a partir das carteiras escolhidas.',
    addYourEmailForDescription:
      'Pode adicionar o seu endereço de e-mail. É utilizado para lhe enviar notificações de transação a partir das carteiras escolhidas.',
    change: 'Altere o seu e-mail',
    title: 'Configure as suas notificações',
    yourEmail: 'O seu e-mail',
    description:
      'Pode alterar o seu endereço de e-mail. É utilizado para lhe enviar notificações de transações a partir das carteiras escolhidas.',
    delete: 'Eliminar e-mail',
    invalidAddressError: 'Introduzir um endereço de e-mail válido',
    yourSubscriptions: 'As suas subscrições',
    confirmEmail: 'Confirme o seu endereço de e-mail',
    pleaseEnter: 'Por favor, introduza o código que enviámos para: ',
    resend: 'Reenviar código',
    getNotification: 'Receber notificações',
    chooseWalletsDescription: 'Escolha carteiras das quais gostaria de receber notificações de transação',
    chooseWalletsToUnsubscribeDescription:
      'Pode escolher as carteiras das quais deseja anular a subscrição das notificações.',
    emailAddedSuccessMessage: 'Viva!\n Adicionou com sucesso o seu endereço de e-mail.',
    goToNotifications: 'Ir para Notificações',
    changeEmailTitle: 'Altere o seu e-mail',
    changeEmailDescription:
      'Pode alterar o seu endereço de e-mail. É utilizado para lhe enviar notificações de transações a partir das carteiras escolhidas.',
    yourCurrentEmail: 'O seu e-mail atual',
    theSameAddressError: 'Não pode introduzir o seu endereço de e-mail atual',
    newEmail: 'Novo e-mail',
    confirmCurrentTitle: 'Confirme o seu endereço de e-mail actual',
    confirmNewTitle: 'Confirme o seu novo endereço de e-mail',
    confirmNewDescription:
      'Agora confirme o seu novo endereço de e-mail. Por favor introduza o código que enviámos para ',
    emailChangedSuccessMessage: 'Viva!\n Atualizou com sucesso o seu endereço de e-mail.',
    updateNotificationPreferences: 'Viva!\n Atualizou com sucesso as suas preferências de notificação.',
    verifyAction: 'Verifique esta ação',
    verifyActionDescription: 'Para confirmar o pedido, por favor introduza o código que enviámos para ',
    deleteEmail: 'Apagar endereço de e-mail',
    deleteYourEmail: 'Elimine o seu endereço de e-mail',
    deleteYourEmailDescription: 'o seu endereço de e-mail',
    deleteEmailSuccessMessage: 'Viva!\n Apagou com sucesso o seu endereço de e-mail.',
    codeError: 'Por favor introduza um código válido.\n Tem mais {attemptsLeft} tentativas.',
    codeFinalError: 'Introduziu um código inválido 3 vezes.\n Enviámos um novo código para o seu endereço de e-mail.',
    walletSubscribedSuccessMessage:
      'Viva!\n Adicionou com sucesso o seu endereço de e-mail e subscreveu as notificações.',
    no: 'Não',
    yes: 'Sim',
    notifications: 'Notificações',
    receiveTransactionDescription:
      'Deseja receber notificações de transacão desta carteira para o seu endereço de e-mail ',
    noteFirst: 'Nota: ',
    noteSecond: 'Se desejar alterar o seu endereço de e-mail, pode fazê-lo mais tarde em Definições.',
    noSubscriptionDescription: 'Não subscreveu nenhuma notificação.',
    genericError: 'Alguma coisa correu mal. Pedimos desculpa.',
    pushnotificationsSettings: {
      title: 'Permitir notificações da aplicação',
      label: 'Definições',
    },
  },
  onboarding: {
    changePin: 'Alterar PIN',
    confirmNewPin: 'Confirmar novo PIN',
    confirmPassword: 'Confirmar palavra-passe de transação',
    confirmPin: 'Confirmar PIN',
    createNewPin: 'Novo PIN',
    createPassword: 'Criar palavra-passe de transação',
    addNotificationEmailDescription:
      'Se desejar receber notificações por e-mail, por favor introduza o seu endereço de e-mail. Iremos enviar-lhe informações sobre o estado das suas transações. Poderá sempre alterá-lo mais tarde em Definições.',
    createPasswordDescription:
      'A sua palavra-passe de transação será utilizada para confirmar todas as transações. Não a poderá alterar mais tarde. A palavra-passe de transação deve conter pelo menos 8 caracteres alfanuméricos.',
    createPin: 'Criar PIN',
    createPinDescription:
      'O seu PIN será utilizado para iniciar a sessão na aplicação. Pode alterá-lo mais tarde na secção Definições.',
    currentPin: 'PIN atual',
    failedTimes: 'Tentativas falhadas',
    failedTimesErrorInfo: 'Após três tentativas falhadas, o acesso será bloqueado por',
    goBack: 'Voltar atrás',
    minutes: 'minutos.',
    numberOfAttemptsExceeded: 'O número de tentativas foi excedido',
    onboarding: 'Integração',
    passwordDoesNotMatch: 'A palavra-passe não corresponde. Por favor introduza uma palavra-passe válida.',
    pin: 'PIN',
    pinDoesNotMatch: 'O PIN não corresponde. Por favor, introduza um PIN válido.',
    seconds: 'segundos',
    successButton: 'Ir para Painel de controlo',
    successButtonChangedPin: 'Voltar a Definições',
    successDescription: 'Viva! \n  Criou com sucesso o seu PIN.',
    successDescriptionChangedPin: 'Viva! \n  Mudou com sucesso o seu PIN.',
    tryAgain: 'Tente novamente depois de',
    resendCodeError: 'Introduziu um código inválido 3 vezes. \n Enviámos um novo código para o seu endereço de e-mail.',
    successCompletedDescription: 'Viva! \n Terminou com sucesso o seu processo de integração.',
    successCompletedButton: 'Ir para Carteiras',
  },
  receive: {
    details: {
      amount: 'Montante',
      receiveWithAmount: 'Receber o montante',
      receiveWithAmountSubtitle:
        'Introduza o montante que gostaria de receber. O código QR será atualizado em conformidade para incluir o montante.',
      share: 'Partilhar',
      shareWalletAddress: 'Partilhar o endereço da carteira',
    },
    header: 'Receber moedas',
    label: 'Endereço da carteira',
  },
  scanQrCode: {
    cancel: 'Cancelar',
    ok: 'Ok',
    permissionMessage: 'Precisamos da sua autorização para utilizar a sua câmara fotográfica',
    permissionTitle: 'Permissão para utilizar a câmara',
  },
  security: {
    jailBrokenPhone:
      'O seu dispositivo parece ter sido desbloqueado/jailbreak. Isto pode ocorrer por problemas de segurança, colisões, ou outros problemas. Não recomendamos a utilização de GoldWallet com o dispositivo desbloqueado/jailbreak.',
    noPinOrFingerprintSet:
      'O seu dispositivo parece não ter um PIN ou um conjunto de impressões digitais. Não recomendamos a utilização da GoldWallet num dispositivo não protegido.',
    rootedPhone:
      'O seu dispositivo parece estar em modo Root. Isto pode ocorrer por problemas de segurança, colisões , ou outros problemas. Não recomendamos a utilização da GoldWallet com o dispositivo modo Root..',
    title: 'Questões de segurança',
  },
  selectLanguage: {
    alertDescription: 'Selecionar a língua e reiniciar a aplicação?',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    confirmation: 'Confirmação',
    header: 'Língua',
    restartInfo:
      'Ao selecionar uma nova língua, poderá ser necessário reiniciar a GoldWallet para que a alteração tenha efeito',
  },
  send: {
    confirm: {
      availableBalance: 'Saldo disponível após a transação',
      cancelNow: 'Cancelar agora',
      pendingBalance: 'Saldo bloqueado após transação',
      sendNow: 'Enviar agora',
    },
    create: {
      amount: 'Montante',
      fee: 'Taxa',
      headerText:
        'Quando há um grande número de transações pendentes na rede (>1500), a taxa mais elevada resultará no processamento mais rápido da sua transação. Os valores típicos são 1-500 sat/b',
      setTransactionFee: 'Definir uma taxa de transação',
    },
    details: {
      address: 'endereço',
      address_field_is_not_valid: 'O campo endereço não é válido',
      amount_field_is_not_valid: 'O campo montante não é válido',
      amount_is_too_high: 'Há um máximo de {maxCoinsInput} BTCV que irá existir, por isso não tente enviar mais!',
      amount_is_negative: 'O montante não pode ser negativo',
      amount_field_is_less_than_minSatoshi: 'O montante mínimo que pode enviar é 1 Satoshi',
      amount_placeholder: 'montante a enviar (em BTCV)',
      cancel: 'Cancelar',
      create: 'Criar Factura',
      create_tx_error: 'Houve um erro ao criar a transação. Por favor, certifique-se de que o endereço é válido.',
      fee: 'Taxa:',
      fee_field_is_not_valid: 'O campo da taxa não é válido',
      fee_placeholder: 'mais a taxa de transação (em BTCV)',
      feeUnit: 'Sat/B',
      next: 'Seguinte',
      note: 'Nota (opcional)',
      note_placeholder: 'nota para si próprio',
      remaining_balance: 'Saldo remanescente',
      scan: 'Scan',
      send: 'Enviar',
      title: 'criar transação',
      to: 'para',
      total_exceeds_balance: 'O montante de envio excede o saldo disponível.',
    },
    error: {
      doubleSpentFunds: 'Está a tentar gastar activos cripto que já foram gastos.',
      notExistingFunds: 'Está a tentar gastar activos cripto que não existem.',
      dust: 'Está a tentar enviar um montante pequeno',
      description: 'Antes de criar uma transação, deve primeiro adicionar uma carteira Bitcoin Vault.',
      title: 'Erro',
    },
    header: 'Enviar moedas',
    recovery: {
      confirmFirstSeed: 'Confirmar com a Frase-Semente de Cancelamento',
      confirmFirstSeedDesc:
        'Abra o primeiro documento PDF que gerou quando criou a sua carteira e escreva a frase-semente da Chave Privada na mesma ordem.',
      confirmSecondSeed: 'Confirmar com a Frase-Semente Rápida',
      confirmSecondSeedDesc:
        'Abra o segundo documento PDF que gerou quando criou a sua carteira e escreva a frase-semente da Chave Privada na mesma ordem.',
      confirmSeed: 'Confirmar com a Frase-Semente de Cancelamento',
      confirmSeedDesc:
        'Abra o documento PDF que gerou quando criou a sua carteira e escreva a frase-semente da Chave Privada na mesma ordem.',
      recover: 'Cancelar',
      useWalletAddress: 'Usar o endereço desta carteira',
    },
    success: {
      description: 'Enviou com sucesso as suas moedas.',
      done: 'Feito',
      return: 'Regressar ao Painel de controlo',
      title: 'Sucesso',
    },
    transaction: {
      alert: 'Seguro',
      alertDesc:
        'Esta transação necessita de 144 blocos ou cerca de 24 horas para ser confirmada. Pode cancelá-la dentro deste prazo.',
      fastSuccess: 'Fez a sua transação rápida com sucesso.',
      instant: 'Rápida e segura',
      instantDesc: 'Esta transação será confirmada de imediato. Utilizar com extrema cautela.',
      lightningError:
        'Este endereço parece ser para uma factura de Lightning. Por favor, dirija-se à sua carteira Lightning a fim de fazer o pagamento desta factura.',
      scanInstantKeyDesc:
        'Abra o documento PDF que gerou quando criou a sua carteira e faça o scan do código QR da Chave Privada para enviar a transação.',
      scanInstantKeyTitle: 'Scan da Chave Rápida',
      type: 'Tipo de transação',
      watchOnlyError: 'Carteiras que unicamente servem para visualização não podem enviar transações',
    },
    warning: 'Advertência: ',
    warningGeneral:
      'Tenha em atenção que no processo de utilização da funcionalidade de Transação Segura, uma parte dos activos deixados na sua carteira podem estar bloqueados. Este é um procedimento normal ligado ao UTXO e aos parâmetros do blockchain da carteira Bitcoin Vault. Os seus activos serão desbloqueados assim que a transação for confirmada (após aproximadamente 24 horas) ou cancelada (dentro de 24 horas)',
  },
  settings: {
    about: 'Sobre',
    terms: 'Termos e Privacidade',
    factoryReset: 'Restaurar as configurações de fábrica',
    aboutUs: 'Sobre nós',
    advancedOptions: 'Opções avançadas',
    Biometrics: 'Permitir a biometria',
    changePin: 'Alterar PIN',
    electrumServer: 'Servidor Electrum ',
    FaceID: 'Permitir FaceID',
    fingerprintLogin: 'Início de sessão com impressão digital',
    general: 'Geral',
    header: 'Definições',
    language: 'Idioma',
    notifications: 'Notificações',
    notSupportedFingerPrint: 'O seu dispositivo não suporta impressões digitais',
    security: 'Segurança',
    TouchID: 'Permitir impressão digital',
    factory: {
      title: 'Restaurar as configurações de fábrica',
      text:
        'Tem a certeza de que quer restaurar a Gold Wallet para as suas configurações de fábrica? Todas as suas carteiras e dados serão apagados. Lembre-se que terá de importar as suas carteiras de novo.',
      noButton: 'Não',
      yesButton: 'Sim',
    },
  },
  tabNavigator: {
    addressBook: 'Livro de endereços',
    authenticators: 'Autenticadores',
    settings: 'Definições',
    wallets: 'Carteiras',
  },
  timeCounter: {
    closeTheApp: 'Fechar a aplicação',
    description:
      'A sua aplicação foi bloqueada devido às tentativas de início de sessão falhadas. Por favor aguarde o tempo necessário para tentar novamente.',
    title: 'Aplicação bloqueada',
    tryAgain: 'Tente novamente',
  },
  transactions: {
    details: {
      addNote: 'Adicionar nota',
      addToAddressBook: 'Adicionar ao livro de endereços',
      amount: 'Montante',
      blocked: 'Bloqueado',
      bytes: 'bytes',
      confirmations: 'confirmações',
      copy: 'Copiar',
      copyAndBoriadcast: 'Copiar e transmitir mais tarde',
      details: 'Detalhes',
      detailTitle: 'Detalhes da transação',
      fee: 'Taxa:',
      from: 'De',
      inputs: 'Entradas',
      noLabel: 'Sem etiqueta',
      note: 'Nota',
      numberOfCancelTransactions: 'Número de transações canceladas',
      ouputs: 'Saídas',
      returnedFee: 'Taxa devolvida:',
      satoshiPerByte: 'Satoshi por byte',
      sendCoins: 'Enviar moedas',
      timePending: 'Tempo pendente',
      title: 'Transação',
      to: 'Para',
      toExternalWallet: 'Para a carteira externa',
      toInternalWallet: 'Para a carteira interna',
      totalReturnedFee: 'Taxa total devolvida:',
      transactioFee: 'Taxa de transação',
      transactionDetails: 'Detalhes da transação',
      transactionHex: 'Transação hex',
      transactionHexDescription: 'Esta é uma transação hex, assinada e pronta a ser transmitida para a rede',
      transactionId: 'Identificação (ID) da transação',
      transactionType: 'Tipo de transação',
      txSize: 'Tamanho TX',
      unblocked: 'Desbloqueado',
      verify: 'Verificar em coinb.in',
      viewInBlockRxplorer: 'Ver no block explorer',
      walletType: 'Tipo de carteira',
    },
    errors: {
      notEnoughBalance: 'Não há saldo suficiente. Por favor, tente enviar uma quantia menor.',
    },
    label: {
      blocked: 'bloqueado',
      canceled: 'cancelado',
      canceledDone: 'cancelado - feito',
      done: 'feito',
      pending: 'pendente',
      unblocked: 'desbloqueado',
    },
    list: {
      conf: 'Confirmações',
    },
    transactionTypeLabel: {
      canceled: 'Cancelado',
      secure: 'Segura',
      secureFast: 'Segura e Rápida',
      standard: 'Padrão',
    },
  },
  unlock: {
    confirmButton: 'Confirmar impressão digital para continuar.',
    enter: 'Introduzir PIN',
    title: 'Desbloquear',
    touchID: 'Touch ID para a "Gold Wallet".',
  },
  unlockTransaction: {
    description: 'Introduza a sua palavra-passe de transação para prosseguir.',
    headerText: 'Confirmar transação',
    title: 'Confirmar Transação',
  },
  wallets: {
    add: {
      createWalletButton: 'Criar nova carteira',
      addWalletButton: 'Adicionar nova carteira',
      advancedOptions: 'Opções avançadas',
      air: 'Faz transações Seguras, de Cancelamento, Seguras e Rápidas.',
      ar: 'Faz transações Seguras e de Cancelamento.',
      description: 'Escolha o nome e o tipo da sua carteira.',
      failed: 'Falha na criação da carteira',
      importWalletButton: 'Importar carteira',
      inputLabel: 'Nome',
      legacy: 'Faz tipos de transações padrão.',
      legacyHDP2SH: 'Contém uma árvore de endereços P2SH gerados a partir de uma única semente de 12 palavras',
      legacyHDP2SHTitle: 'Padrão HD P2SH',
      LegacyHDSegWit:
        'Contém uma árvore de endereços de segwit nativos, gerada a partir de uma única semente de 12 palavras',
      legacyHDSegWitTitle: 'SegWit HD padrão',
      LegacyP2SH: 'Contém um único endereço P2SH',
      legacyP2SHTitle: 'Padrão P2SH',
      legacyTitle: 'Padrão',
      multipleAddresses: 'Contém uma árvore de endereços P2SH gerada a partir de uma única semente de 12 palavras',
      publicKeyError: 'A chave pública fornecida é inválida',
      segwidAddress:
        'Contém uma árvore de endereços de segwit nativos, gerada a partir de uma única semente de 12 palavras',
      singleAddress: 'Contém um único endereço P2SH',
      subtitle: 'Dê um nome à sua carteira',
      title: 'Adicionar nova carteira',
      walletType: 'Tipo de carteira',
    },
    confirmSeed: {
      header: 'Confirmar a frase semente',
      title: 'Confirme a frase da cópia de segurança',
      description: 'Clique nas palavras na ordem correta para confirmar a sua cópia de segurança.',
      button: 'Confirmar',
      error: 'El orden de la frase semilla es incorrecto.',
    },
    addSuccess: {
      description:
        'Escreva esta frase-semente em algum lugar seguro. É a sua cópia de segurança para o caso de necessitar de restaurar a sua carteira.',
      okButton: 'OK, eu escrevi isto',
      subtitle: 'A sua carteira está pronta!\n Criou a sua carteira!',
      title: 'Adicionar nova carteira',
    },
    dashboard: {
      allWallets: 'Todas as carteiras',
      availableBalance: 'Saldo disponível',
      noTransactions: 'Não há transações a mostrar.',
      noWallets: 'Sem carteiras',
      noWalletsDesc1: 'Não há carteiras para mostrar.\nAdicione a sua primeira carteira.',
      noWalletsDesc2: 'para adicionar a sua primeira carteira.',
      receive: 'Receber',
      recover: 'Cancelar',
      send: 'Enviar',
      title: 'Carteiras',
      wallet: 'carteira',
    },
    deleteWallet: {
      description1: 'Tem a certeza que quer apagar',
      description2: '? Não será possível reverter a situação.',
      header: 'Eliminar a carteira',
      no: 'Não',
      title: 'Eliminar a sua carteira',
      yes: 'Sim',
    },
    details: {
      deleteWallet: 'Eliminar carteira',
      details: 'Detalhes',
      edit: 'Editar',
      exportWallet: 'Exportar carteira',
      latestTransaction: 'Última transação',
      nameEdit: 'Editar nome',
      nameLabel: 'Nome',
      showWalletXPUB: 'Mostrar carteira XPUB',
      typeLabel: 'Tipo',
      subscribeWallet: 'Subscrever as notificações por e-mail',
      unsubscribeWallet: 'Anular a subscrição de notificações por e-mail',
    },
    errors: {
      duplicatedPublicKey: 'A chave pública já foi acrescentada',
      invalidMnemonic: 'Mnemónica inválida',
      invalidMnemonicWordsNumber: 'Palavras fornecidas {receivedWordsNumber} palavras esperadas {expectedWordsNumber}',
      invalidPrivateKey: 'Chave privada inválida',
      invalidPublicKey: 'Chave pública inválida',
      invalidQrCode: 'Código QR inválido',
      invalidSign: 'Não foi possível assinar a transação',
      noIndexForWord: 'Não foi possível encontrar índice por palavra: {word}',
      wrongNetwork:
        'Tem a carteira na rede {walletNetworkName} enquanto que a rede da aplicação é {appNetworkName}. Por favor contacte o nosso suporte através do Telegram.',
    },
    export: {
      title: 'exportar carteira',
    },
    exportWallet: {
      header: 'Exportar carteira',
      title: 'Frase-semente',
    },
    exportWalletXpub: {
      header: 'Carteira XPUB',
    },
    import: {
      do_import: 'Importar',
      error: 'Falha na importação. Por favor, certifique-se de que os dados fornecidos são válidos.',
      explanation:
        'Escreva aqui a sua mnemónica, chave privada, WIF, ou qualquer coisa que tenha. GoldWallet fará o seu melhor para adivinhar o formato correto e importar a sua carteira',
      imported: 'Importado',
      scan_qr: 'ou faça o scan do código QR em vez disto?',
      success: 'Sucesso',
      title: 'importar',
    },
    importWallet: {
      chooseTypeDescription: 'Escolha o tipo de carteira que pretende importar.',
      customWords: 'Palavras personalizadas',
      extendWithCustomWords: 'Prolongar esta semente com palavras personalizadas',
      header: 'Carteira de importação',
      import: 'Importar',
      importARDescription1: 'Introduzir a frase-semente',
      importARDescription2: 'faça o scan do código QR da carteira que pretende importar',
      placeholder: 'Frase-semente',
      scanCancelPubKey: 'Fazer o scan do código QR da Chave de Cancelamento',
      scanFastPubKey: 'Fazer o scan do código QR da Chave Rápida',
      scanPublicKeyDescription:
        'Abra o primeiro documento PDF que gerou quando criou a carteira que pretende importar e utilize esta aplicação para fazer o scan do código QR da Chave Pública.',
      scanQrCode: 'ou scan de código QR',
      scanWalletAddress: 'Scan endereço da carteira',
      scanWalletAddressDescription:
        'Faça o scan do código QR do endereço público para iniciar a integração com a GoldWallet.',
      subtitle:
        'Escreva aqui a sua mnemónica, chave privada, WIF ou qualquer coisa que tenha. GoldWallet fará o seu melhor para adivinhar o formato correto e importar a sua carteira.',
      title: 'Importar a sua carteira',
      unsupportedElectrumVaultMnemonic:
        'Esta semente é da Electrum Vault e não é atualmente suportada. Será suportada num futuro próximo.',
      walletInUseValidationError: 'A carteira já está a ser utilizada. Por favor, introduza uma carteira válida.',
      allWalletsValidationError: 'Não é possível introduzir o nome "Todas as carteiras".',
    },
    publicKey: {
      instantDescription:
        'Vá novamente para ao Key Generator no site num dispositivo à parte, atualize a página e utilize esta aplicação para fazer o scan do novo código QR da Chave Pública. Lembre-se de exportar as suas chaves como um PDF!',
      instantSubtitle: 'Adicionar a Chave Rápida',
      recoveryDescription:
        'Vá para o ao Key Generator no site num dispositivo à parte e utilize esta aplicação para fazer o scan do código QR da Chave Pública. Lembre-se de exportar as suas chaves como um PDF!',
      recoverySubtitle: 'Adicionar a Chave de Cancelamento',
      scan: 'Scan',
      webKeyGenerator: 'Key Generator no site:',
    },
    scanQrWif: {
      bad_password: 'Palavra-passe incorrecta',
      bad_wif: 'WIF incorreta',
      cancel: 'Cancelar',
      decoding: 'Descodificação',
      go_back: 'Voltar',
      imported_legacy: 'Legacy Importado',
      imported_segwit: 'SegWit importado',
      imported_watchonly: 'Somente para visualização importado',
      imported_wif: 'WIF importado',
      input_password: 'Palavra-passe de entrada',
      password_explain: 'Esta é a chave privada encriptada BIP38',
      wallet_already_exists: 'Tal carteira já existe',
      with_address: 'com o endereço',
    },
    wallet: {
      latest: 'Última transação',
      none: 'Nenhum',
      pendingBalance: 'Saldo bloqueado',
    },
    walletModal: {
      btcv: 'BTCV',
      wallets: 'Carteiras',
    },
  },
  connectionIssue: {
    noInternetTitle: 'Sem ligação à Internet',
    noInternetDescription: 'Certifique-se de que a WI-FI ou os dados móveis estão ligados, depois tente novamente.',
    offlineMessageTitle: 'Está offline',
    offlineMessageDescription: 'Ligue-se à Internet para restaurar a funcionalidade total.',
    offlineMessageDescription2: 'Ligar-se à Internet para continuar a utilizar estas funções.',
    noNetworkTitle: 'Sem ligação à rede',
    noNetworkDescription:
      'A sua Internet funciona, mas você não está ligado à rede. Por favor aguarde um momento e tente novamente.',
    electrumXNotConnected: 'O cliente Electrum não está ligado',
    couldntConnectToServer: 'Não foi possível a ligação ao servidor.',
  },
};
