module.exports = {
  _: {
    bad_password: 'Kötü şifre, tekrar deneyin',
    cancel: 'İptal',
    click: 'Tıklayın',
    confirm: 'Onayla',
    continue: 'Devam',
    copied: 'Kopyalandı!',
    copy: 'Kopyala',
    created: 'Oluşturuldu',
    delete: 'Sil',
    details: 'Detaylar',
    enter_password: 'Şifreyi Gir',
    here: 'burada',
    invalid: 'Geçersiz',
    languageCode: 'en',
    never: 'hiç',
    next: 'İleri',
    ok: 'Tamam',
    or: 'veya',
    satoshi: 'Sat',
    save: 'Kaydet',
    scan: 'Tara',
    storage_is_encrypted: 'Deponuz şifre korumalı. Açmak için şifre gerekli',
    skip: 'Bu adımı atla',
    add: 'Ekle',
    undo: 'Geri al',
    yes: 'Evet',
    no: 'Hayır',
  },
  order: {
    first: 'birinci',
    second: 'ikinci',
    third: 'üçüncü',
    fourth: 'dördüncü',
    fifth: 'beşinci',
    sixth: 'altıncı',
  },
  time: {
    days: 'Gün',
    hours: 'Saat',
    minutes: 'Dakika',
  },
  airdrop: {
    title: 'Airdrop',
    dateOfAirdrop: 'Airdrop tarihi:',
    readableCommunityGoals: {
      first: 'Birinci hedef',
      second: 'İkinci hedef',
      third: 'Üçüncü hedef',
      fourth: 'Dördüncü hedef',
    },
    readableGoals: {
      first: 'Birinci hedefiniz',
      second: 'İkinci hedefiniz',
      third: 'Üçüncü hedefiniz',
      fourth: 'Dördüncü hedefiniz',
    },
    community: {
      header: 'Airdrop ödülleri',
      name: 'Topluluk',
      description: 'Ödülleri ve topluluğun gelişimini görün',
      carouselItemHeader: 'Topluluğun gelişimi',
      wallet: 'cüzdan',
      wallets: 'cüzdanlar',
      airdropParticipants: 'Airdrop katılımcıları',
      goal: '{order} hedef:',
      unlockToIncrease: "Airdrop'u {reward}$ seviyesine çıkarmak için kilidi açın",
      thresholdWallets: '{threshold} cüzdanlar',
    },
    circularWalletBalance: {
      yourBalance: 'Bakiyeniz',
    },
    createWallet: {
      doYouWantToTakePart: "Airdrop'a katılmak istiyor musunuz?",
      title: 'Airdrop şu an aktif!',
    },
    dashboard: {
      createNewWallet: 'Yeni cüzdan oluşturun',
      desc1: 'Süre dolmadan cüzdanlarınızı ekleyin.',
      desc1WithWallets: 'Gelişiminizi izleyin ve daha fazla cüzdan kaydedin.',
      desc2: "Airdrop'a katılmak için bir cüzdan oluşturun veya ekleyin.",
      cantConnectToServerLine1: 'Sunucuya bağlanılamadı.',
      cantConnectToServerLine2: 'Birkaç dakika içerisinde tekrar deneyin.',
      loading1: 'Sunucu bekleniyor.',
      loading2: 'Birkaç saniye sürebilir.',
      availableWallets: 'Mevcut cüzdanlar',
      registeredWallets: 'Kayıtlı cüzdanlar',
    },
    itIsAlive: {
      subtitle: 'Airdrop şu an aktif!',
      description: "İlk BTCV airdrop'umuz burada.\nÖdül almak için göz atın!",
      notNow: 'Şimdi değil',
      learnMore: 'Daha fazla öğren',
    },
    requirements: {
      soundsGreat: 'Harika!',
      subtitle: "Bitcoin Vault'un bir parçası olduğunuz için teşekkür ederiz",
      description:
        'Bizimle birlikte olduğunuzdan dolayı sizi ödüllendirmek için {airdropTotalDollarsToShare}$ değerinde BTCV paylaşmak istiyoruz!',
      listHeader: 'Airdrop için gereksinimler:',
      points: {
        '0': 'Herhangi bir BTCV Cüzdanı',
        '1': 'En az {airdropMinimumBTCVRequired} BTCV cüzdanda depolandı*',
      },
      rewardExplanation: '*Ödülünüz genel havuzda kaç koininiz olduğuna bağlıdır.',
      termsAndConditions: {
        read: 'Oku',
        termsAndConditions: 'Hüküm ve Koşullar',
      },
    },
    walletsCarousel: {
      shrimp: '',
      crab: 'Crab',
      shark: '',
      whale: '',
      yourNextGoal: 'Sizin {order}:',
      avatarTeaser: '{goalName} olun: {goalThreshold} {unit}',
      youReachedGoal: 'Hedefe ulaştınız:',
    },
    finished: {
      subtitle: 'Airdrop bitti!',
      stayTuned: '{period} içerisinde daha fazlası için takipte kalın',
      shareIt: 'Başkalarıyla paylaşın',
      checkOutData: 'Daha fazla bilgi edinmek istiyor musunuz?',
      readFullReport: 'Tam raporumuzu okuyun',
      medium: 'Medium',
      registeredWallets: 'Kayıtlı cüzdanlar',
    },
    createWalletSuccess: {
      success: 'Yaşasın!\nAirdrop için başarılı bir şekilde kayıt oldunuz!',
      successWithNotifications:
        'Yaşasın!\nBildirimlere başarılı bir şekilde abone oldunuz ve Airdrop için kayıt oldunuz!',
      shareIt: 'Başkalarıyla paylaşın ve ödül olarak {rewardValue} BTCV kazanın!*',
      maxReward: "*Bir cüzdan için maksimum ödül {rewardValue} BTCV'dir.",
      successCompletedButton: "{routeName}'e git",
    },
  },
  termsConditions: {
    header: 'Hüküm & Koşullar',
    title: 'Koşulların Kabulü',
    text: '',
    readTermsConditions: 'Hüküm & Koşulları okudum',
    readPrivacyPolicy: 'Gizlilik Politikasını okudum',
    buttons: {
      agree: 'Kabul ediyorum',
      disagree: 'Reddediyorum',
    },
    modal: {
      header: 'Emin misiniz?',
      text:
        'Hüküm & Koşulları reddederseniz\n Gold Wallet uygulamasını \nkullanamayacağınızı hatırlatırız. \nReddetmek istediğinize emin \nmisiniz?',
      noButton: 'Hayır, fikrimi değiştirdim',
      yesButton: 'Evet, reddediyorum',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: 'Her zaman anahtarlarınızı \nyedekleyiniz',
    buildWithAwesome: 'Harikaların gerçekleştiği yer:',
    goToOurGithub: "GitHub'a gidin",
    header: 'Hakkımızda',
    rateGoldWallet: "GoldWallet'ı oylayın",
    releaseNotes: 'Piyasaya giriş notları',
    runSelfTest: 'Testi çalıştır',
    title: 'Gold Wallet ücretsiz ve açık \nkaynak bir Bitcoin Vault cüzdanıdır.\nMIT Lisanslı.',
  },
  developer: {
    config: 'Yerel Konfigürasyon',
    firebase: 'Firebase',
    FCMToken: 'FCMToken',
    copied: 'Kopyalandı',
    header: 'Geliştirici',
    api: 'API',
    environment: 'Ortam',
  },
  advancedOptions: {
    description:
      'Gelişmiş özelliklere izin vererek aşağıdaki cüzdan tiplerinden birini seçebilirsiniz:\nP2SH, HD P2SH, HD segwit.',
    title: 'Gelişmiş seçenekleri düzenle',
  },
  authenticators: {
    add: {
      description:
        "Gold Wallet'ı Electrum Vault \nmasaüstü uygulamasıyla \neşleştirmek için gerekir. İki faktörlü kimlik doğrulayıcı görevi \nyapacaktır.",
      subdescription: 'Aşağıdaki seçeneği seçerek kimlik \ndoğrulayıcınızı içe aktarabilirsiniz.',
      subtitle: 'Yeni bir kimlik doğrulayıcı oluştur',
      successDescription:
        'Anahtar kelimelerinizi güvenli bir \nnot edin. Doğrulayıcınızı yeniden kurmanız gerekirse buna ihtiyacınız olacak. Hızlı onay ve İptal işlemleri için kimlik doğrulayıcı gerektiğini unutmayın.',
      successTitle: 'Kimlik doğrulayıcınız hazır!',
      title: 'Yeni bir kimlik doğrulayıcı ekle',
    },
    delete: {
      subtitle: 'Kimlik doğrulayıcınızı silin',
      success: 'Kimlik doğrulayıcınız başarılı bir \nşekilde silindi. Yenisini istediğiniz \nzaman oluşturabilirsiniz.',
      title: 'Kimlik doğrulayıcıyı sil',
    },
    enterPIN: {
      description: "Eşleştirme işlemini bitirmek için \nPIN'i Electrum Vault masaüstü \nuygulamasına girin.",
      subtitle: "PIN'i girin",
    },
    errors: {
      noEmpty: 'Bu alan boş bırakılamaz',
    },
    export: {
      title: 'Kimlik doğrulayıcıyı dışa aktar',
    },
    import: {
      code: 'Kod:',
      desc1: 'Anahtar kelimelerinizi yazın veya \niçe aktarmak istediğiniz kimlik \ndoğrulayıcının QR kodunu tarayın.',
      desc2: 'Aşağıdaki "QR kodunu tara"ya \ntıklayarak QR kodunu tarayın.',
      inUseValidationError: 'İsim özgün olmalı. Lütfen geçerli\nbir isim girin.',
      mnemonicLength: 'Anımsatıcı dizi 12 kelimeden \noluşmalıdır',
      multipleQrCodesDescription:
        'Bazı işlemler birden fazla QR kod \noluşturmaktadır. Electrum Vault \nuygulamasından hepsini \ntaradığınızdan emin olun.',
      multipleQrCodesTitle: 'Başka bir QR kod tara',
      scanNext: 'Sonrakini tara',
      subtitle: 'Kimlik doğrulayıcınızı içe aktarın',
      success: 'Kimlik doğrulayıcınızı başarıyla \niçe aktardınız. Artık kullanıma hazır.',
      textAreaPlaceholder: 'Anahtar kelime dizisi',
      title: 'Kimlik doğrulayıcıyı içe aktar',
    },
    list: {
      noAuthenticators: 'Kimlik doğrulayıcı yok',
      noAuthenticatorsDesc1: 'Dokunun',
      noAuthenticatorsDesc2: 'ilk kimlik doğrulayıcınızı eklemek \niçin',
      scan: 'Tara',
      title: 'Bitcoin Vault kimlik doğrulayıcıları',
    },
    options: {
      delete: 'Kimlik doğrulayıcıyı sil',
      export: 'Kimlik doğrulayıcıyı dışa aktar',
      pair: 'Kimlik doğrulayıcıyı eşleştir',
      sectionTitle: 'Genel',
      title: 'Kimlik doğrulayıcı seçenekleri',
    },
    pair: {
      descPin: "Masaüstü uygulamanızda kimlik \ndoğrulayıcı eşleştirmesini \nonaylamak için bu PIN'i kullanın.",
      descPublicKey:
        'Cüzdan oluşturma işlemi sırasında GoldWallet seçeneğiyle masaüstü \nuygulamasında kimlik doğrulayıcınızı içe aktarırken bu Genel Anahtarı kullanabilirsiniz.',
      pin: 'PIN',
      publicKey: 'Genel Anahtar',
      title: 'Eşleşme doğrulayıcı',
    },
    publicKey: {
      okButton: 'Tamam, anladım',
      subtitle:
        '2FA cüzdan oluştururken Electrum \nVault masaüstü uygulamasında \nkimlik doğrulayıcınızı içe aktarırken bu Genel Anahtarı kullanabilirsiniz.',
      title: 'Genel Anahtar',
    },
    sign: {
      error: 'Kimlik doğrulayıcılardan hiçbiri \nişlemi imzalayamadı',
    },
  },
  betaVersion: {
    button: 'Riski kabul ediyorum',
    description:
      'Resmi paylaşım tarihinden önce \nson testler yapılıyor. Mobil uygulama ve tüm içeriği "olduğu gibi" ve "mevcut olduğu gibi" esasına göre paylaşılmıştır. Yazılımın kullanımı kullanıcının kendi sorumluluğundadır.',
    title: "Bu GoldWallet'ın bir beta \nversiyonudur.",
  },
  contactCreate: {
    addressLabel: 'Adres',
    buttonLabel: 'Yeni bağlantı ekle',
    description: 'Yeni bağlantınız için isim ve adres \nekleyin.',
    nameCannotContainSpecialCharactersError: 'İsimde özel karakter bulunamaz.',
    nameCannotEmpty: 'İsim boş bırakılamaz',
    nameLabel: 'İsim',
    nameMissingAlphanumericCharacterError: 'İsimde alfanümerik karakter \nbulunmuyor',
    screenTitle: 'Yeni bağlantı ekle',
    subtitle: 'Yeni bağlantı',
    successButton: 'Adres defterine dön',
    successDescription: 'İşte bu! Bağlantınızı başarıyla \neklediniz.',
    successTitle: 'Başarı',
  },
  contactDelete: {
    description1: 'Silmek istediğinize emin misiniz',
    description2: '?\nİşlemi geri alamayacaksınız.',
    header: 'Bağlantıyı sil',
    no: 'Hayır',
    success: 'Başarı',
    successButton: 'Adres defterine dön',
    successDescription: 'Bağlantınız başarıyla silindi.\nAdres defterine dönebilirsiniz.',
    title: 'Bağlantınızı silin',
    yes: 'Evet',
  },
  contactDetails: {
    addressLabel: 'Adres',
    deleteButton: 'Bağlantıyı sil',
    editAddress: 'Bağlantıyı düzenle',
    editName: 'İsmi düzenle',
    nameLabel: 'İsim',
    sendCoinsButton: 'Coin gönder',
    share: 'Paylaş',
    showQRCodeButton: 'QR kodu göster',
  },
  contactList: {
    cancel: 'İptal et',
    noContacts: 'Bağlantı yok',
    noContactsDesc1: 'Gösterilecek bağlantı yok.\nTıklayın',
    noContactsDesc2: 'ilk bağlantınızı eklemek için.',
    noResults: 'Sonuç yok',
    screenTitle: 'Adres defteri',
    search: 'Ara',
  },
  electrumServer: {
    connectionError: 'Electrum sunucusuna \nbağlanılamıyor',
    description: 'Uygulamanızın bağlanacağı \nsunucunun adresini değiştirebilirsiniz. Varsayılan adres önerilir.',
    header: 'Electrum sunucusu',
    host: 'host',
    port: 'port',
    save: 'Kaydet',
    successfullSave:
      'Değişiklikleriniz başarıyla \nkaydedilmiştir. Değişikliklerin uygulanması için yeniden başlatma gerekebilir.',
    title: 'Electrum sunucusunu değiştir',
    useDefault: 'Varsayılanı kullan',
  },
  filterTransactions: {
    clearAll: 'Hepsini temizle',
    clearFilters: 'Filtreleri temizle',
    filter: 'Filtrele',
    from: 'Nereden',
    fromAmount: 'Ne kadardan',
    fromDate: 'Ne zamandan',
    header: 'İşlemleri filtrele',
    receive: 'Al',
    received: 'Alındı',
    send: 'Gönder',
    sent: 'Gönderildi',
    status: {
      canceled: 'İptal edildi',
      canceledDone: 'İptal edildi - gerçekleştirildi',
      done: 'Gerçekleştirildi',
      pending: 'Beklemede',
    },
    to: 'Nereye',
    toAmount: 'Ne kadara',
    toDate: 'Ne zamana',
    transactionStatus: 'İşlem durumu',
    transactionType: 'İşlem türü',
  },
  message: {
    allDone: 'Tamamı gerçekleştirildi!',
    bePatient: 'Lütfen bekleyin, bu biraz zaman \nalabilir',
    cancelTxSuccess: "İşleminizi başarıyla iptal ettiniz. \nCoin'leriniz yolda.",
    creatingAuthenticator: 'Kimlik doğrulayıcınız oluşturuluyor',
    creatingAuthenticatorDescription:
      'Kimlik doğrulayıcınız \noluşturulurken lütfen bekleyin. \nBu biraz zaman alabilir.',
    creatingWallet: 'Cüzdanınız oluşturuluyor',
    creatingWalletSuccess: 'Cüzdanınızı başarıyla oluşturdunuz.',
    creatingWalletDescription: 'Cüzdanınız oluşturulurken lütfen\nbekleyin. Bu biraz zaman alabilir.',
    generateAddressesError: 'Adresler oluşturulamadı',
    hooray: 'İşte bu!',
    importingAuthenticator: 'Kimlik doğrulayıcınız içe aktarılıyor',
    importingAuthenticatorDescription:
      'Kimlik doğrulayıcınız içe aktarılırken lütfen bekleyin. Bu biraz zaman alabilir.',
    noTransactions: 'Cüzdanda hiçbir işlem bulunamadı',
    noTransactionsDesc: 'Muhtemelen hiç kullanılmamış\nbir cüzdanı içe aktarmaya çalışıyorsunuz.',
    processing: 'İşleniyor',
    returnToAuthenticators: 'Kimlik doğrulayıcılara dön',
    returnToDashboard: 'Panoya dön',
    returnToWalletChoose: 'Cüzdan türü seçimine dön',
    returnToWalletImport: 'Cüzdanı içe aktarmaya dön',
    somethingWentWrong: 'Bir şeyler yanlış gitti',
    somethingWentWrongWhileCreatingWallet:
      'Cüzdanınız oluşturulurken bir \nşeyler yanlış gitti. Lütfen panoya dönüp tekrar deneyin.',
    success: 'Başarılı',
    successfullWalletDelete: 'Cüzdanınız başarılı bir şekilde \nsilindi. Şimdi Panoya dönebilirsiniz.',
    successfullWalletImport: 'Cüzdanınızı başarılı bir şekilde\niçe aktardınız. Artık kullanıma hazır.',
    wrongMnemonic: 'Yanlış anımsatıcı',
    wrongMnemonicDesc:
      'Anımsatıcınız desteklenen hiçbir\ncüzdanla uyuşmuyor. Geçersiz bir anımsatıcıyı veya hiç kullanılmamış bir cüzdanı içe aktarmaya çalışıyorsunuz. ',
    goToWalletDetails: 'Cüzdan Detaylarına git',
    successSubscription: 'İşte bu! \nBildirimler için başarıyla abone oldunuz.',
  },
  notifications: {
    main: {
      header: 'Bildirimler',
      title: 'Bildirimlerinizi ayarlayın',
      description: 'Almak istediğiniz bildirimleri seçebilirsiniz.',
    },
    email: {
      header: 'Email bildirimleri',
      description:
        'Email adresinizi değiştirebilirsiniz. Size seçili cüzdanlardan işlem bildirimleri göndermek için kullanılır.',
      title: 'Cüzdanlar',
    },
    push: {
      header: 'Anlık bildirimler',
      title: 'Cüzdanlar',
      description:
        'Anlık bildirim ayarlarınızı değiştirebilirsiniz. Size seçili cüzdanlardan işlem bildirimleri göndermek için kullanılır.',
    },
    emailNotificationsNavigate: 'Email bildirimleri',
    pushNotificationsNavigate: 'Anlık bildirimler',
    addYourAddress: 'Email adresinizi ekleyin',
    addYourEmailFor: 'Bildirimler için email adresinizi\nekleyin',
    addEmail: 'Email ekleyin',
    addYourAddressDescription: 'Size seçili cüzdanlardan işlem\nbildirimleri göndermek için kullanılır.',
    addYourEmailForDescription:
      'Email adresinizi ekleyebilirsiniz.\nSize seçili cüzdanlardan işlem bildirimleri göndermek için kullanılır.',
    change: "Email'inizi değiştirin",
    title: 'Bildirimlerinizi konfigüre edin',
    yourEmail: "Email'iniz",
    delete: "Email'i sil",
    invalidAddressError: 'Geçerli bir email adresi girin',
    yourSubscriptions: 'Abonelikleriniz',
    confirmEmail: 'Email adresinizi onaylayın',
    pleaseEnter: 'Şuraya gönderdiğimiz kodu girin:',
    resend: 'Kodu tekrar gönder',
    getNotification: 'Bildirim al',
    chooseWalletsDescription: 'İşlem bildirimleri almak istediğiniz\ncüzdanları seçin',
    chooseWalletsToUnsubscribeDescription: 'Bildirim aboneliğinden çıkmak\nistediğiniz cüzdanları seçebilirsiniz.',
    emailAddedSuccessMessage: 'İşte bu! \nEmail adresinizi başarılı bir şekilde eklediniz.',
    goToNotifications: 'Bildirimlere git',
    changeEmailTitle: "Email'inizi değiştirin",
    changeEmailDescription:
      'Email adresinizi değiştirebilirsiniz.\nSize seçili cüzdanlardan işlem bildirimleri göndermek için kullanılır.',
    yourCurrentEmail: "Mevcut email'iniz",
    theSameAddressError: 'Mevcut email adresinizi \ngiremezsiniz',
    newEmail: 'Yeni email',
    invalidName: 'Geçersiz cüzdan adı',
    confirmCurrentTitle: 'Mevcut email adresinizi onaylayın',
    confirmNewTitle: 'Yeni email adresinizi onaylayın',
    confirmNewDescription: 'Şimdi yeni email adresinizi \nonaylayın. Şuraya gönderdiğimiz kodu girin',
    emailChangedSuccessMessage: 'İşte bu!\nEmail adresinizi başarılı bir şekilde güncellediniz.',
    updateNotificationPreferences: 'İşte bu!\nBildirim tercihlerinizi başarılı bir şekilde güncellediniz.',
    verifyAction: 'Bu eylemi doğrula',
    verifyActionDescription: 'Talebi onaylamak için lütfen şuraya gönderdiğimiz kodu girin',
    deleteEmail: 'Email adresini sil',
    deleteYourEmail: "Email'inizi silin",
    deleteYourEmailDescription: 'email adresiniz',
    deleteEmailSuccessMessage: 'İşte bu!\nEmail adresinizi başarılı bir şekilde sildiniz.',
    codeError: 'Lütfen geçerli bir kod girin. \n{attemptsLeft} hakkınız kaldı.',
    codeFinalError: '3 kere geçersiz bir kod girdiniz.\nEmail adresinize yeni bir kod gönderdik.',
    walletSubscribedSuccessMessage:
      'İşte bu!\nBaşarılı bir şekilde email adresinizi eklediniz ve bildirimlere abone oldunuz.',
    no: 'Hayır',
    yes: 'Evet',
    notifications: 'Bildirimler',
    receiveTransactionDescription: 'Email adresinize bu cüzdandan \nişlem bildirimleri gelmesini istiyor musunuz',
    noteFirst: 'Not:',
    noteSecond: 'Email adresinizi değiştirmek \nisterseniz bu işlemi sonradan Ayarlardan yapabilirsiniz.',
    noSubscriptionDescription: 'Hiçbir bildirim aboneliğiniz \nbulunmuyor.',
    genericError: 'Bir şeyler yanlış gitti. Üzgünüz.',
    pushnotificationsSettings: {
      title: 'Uygulama bildirimlerine izin ver',
      label: 'Ayarlar',
    },
    description:
      'Email adresinizi değiştirebilirsiniz.\nSize seçili cüzdanlardan işlem bildirimleri göndermek için kullanılır.',
  },
  onboarding: {
    changePin: "PIN'i değiştirin",
    confirmNewPin: "Yeni PIN'i onaylayın",
    confirmPassword: 'İşlem şifresini onaylayın',
    confirmPin: "PIN'i onaylayın",
    createNewPin: 'Yeni PIN',
    createPassword: 'İşlem şifresi oluştur',
    addNotificationEmailDescription:
      'Email bildirimleri almak \nistiyorsanız lütfen email adresinizi girin. İşlem durumlarınızla ilgili size bilgi göndereceğiz. İsterseniz sonradan Ayarlardan değişiklik yapabilirsiniz.',
    createPasswordDescription:
      'İşlem Şifreniz tüm işlemleri \ndoğrulamak için kullanılacaktır. Sonradan değiştiremezsiniz. Şifre en az 8 alfanümerik karakterden oluşmalıdır.',
    createPin: 'PIN oluştur',
    createPinDescription:
      "PIN'iniz uygulamaya giriş yapmak\niçin kullanılacaktır. Sonradan Ayarlar kısmından değiştirebilirsiniz.",
    currentPin: 'Mevcut PIN',
    failedTimes: 'Başarısız denemeler',
    failedTimesErrorInfo: 'Üç başarısız denemeden sonra erişim bloke edilecektir',
    goBack: 'Geri dön',
    minutes: 'dakika.',
    numberOfAttemptsExceeded: 'Deneme sayısı şunu geçti',
    onboarding: 'Karşılama',
    passwordDoesNotMatch: 'Şifreler uyuşmuyor. Lütfen geçerli\nbir şifre girin.',
    pin: 'PIN',
    pinDoesNotMatch: 'PIN uyuşmuyor. Lütfen geçerli bir\nPIN girin.',
    seconds: 'saniye',
    successButton: 'Panoya git',
    successButtonChangedPin: 'Ayarlara dön',
    successDescription: "İşte bu!\nPIN'inizi başarılı bir şekilde oluşturdunuz.",
    successDescriptionChangedPin: "İşte bu!\nPIN'inizi başarılı bir şekilde değiştirdiniz.",
    tryAgain: 'Sonra tekrar deneyin',
    resendCodeError: '3 kere geçersiz bir kod girdiniz.\nEmail adresinize yeni bir kod gönderdik.',
    successCompletedDescription: 'İşte bu!\nKarşılama işlemlerinizi başarıyla tamamladınız.',
    successCompletedButton: 'Cüzdanlara git',
  },
  receive: {
    details: {
      amount: 'Tutar',
      receiveWithAmount: 'Bu tutarı al',
      receiveWithAmountSubtitle: 'Almak istediğiniz tutarı girin. QR\nkodu bu tutarı kapsayacak şekilde güncellenecek.',
      share: 'Paylaş',
      shareWalletAddress: 'Cüzdan adresini paylaş',
    },
    header: 'Coin al',
    label: 'Cüzdan adresi',
  },
  scanQrCode: {
    cancel: 'İptal et',
    ok: 'Tamam',
    permissionMessage: 'Kameranıza erişmek için izniniz\ngerekiyor',
    permissionTitle: 'Kameraya erişim izni',
  },
  security: {
    jailBrokenPhone:
      'Cihazınızın kısıtlamaları kaldırılmış\ngörünüyor. Bu birtakım güvenlik sorunlarına, çökmelere veya başka sorunlara yol açabilir. Kısıtlamaları kaldırılmış bir cihazda GoldWallet kullanımını tavsiye etmiyoruz.',
    noPinOrFingerprintSet:
      'Cihazınızda PIN veya parmak izi \nokuyucu olmadığı görünüyor. Güvenli olmayan bir cihazda GoldWallet kullanımını tavsiye etmiyoruz.',
    rootedPhone:
      'Cihazınızın ayarları değiştirilmiş\ngörünüyor. Bu birtakım güvenlik sorunlarına, çökmelere veya başka sorunlara yol açabilir. Ayarları değiştirilmiş bir cihazda GoldWallet kullanımını tavsiye etmiyoruz.',
    title: 'Güvenlik sorunu',
  },
  selectLanguage: {
    alertDescription: 'Dili seçip uygulamayı yeniden \nbaşlatmak istiyor musunuz?',
    cancel: 'İptal et',
    confirm: 'Onayla',
    confirmation: 'Onay',
    header: 'Dil',
    restartInfo: "Yeni bir dil seçerken değişikliklerin\nuygulanması için GoldWallet'ı yeniden başlatmanız gerekebilir",
  },
  send: {
    confirm: {
      availableBalance: 'İşlemden sonraki mevcut bakiye',
      cancelNow: 'Şimdi iptal et',
      pendingBalance: 'İşlemden sonraki bloke bakiye',
      sendNow: 'Şimdi gönder',
    },
    create: {
      amount: 'Tutar',
      fee: 'Ücret',
      headerText:
        "Ağda çok sayıda bekleyen işlem \nolduğunda (>1500), daha yüksek işlem ücreti işleminizin daha çabuk gerçekleştirilmesini sağlar. Tipik değerler 1-500 sat/b'dir.",
      setTransactionFee: 'Bir işlem ücreti belirle',
    },
    details: {
      address: 'adres',
      address_field_is_not_valid: 'Adres geçerli değil',
      amount_field_is_not_valid: 'Tutar geçerli değil',
      amount_is_too_high: 'Toplamda {maxCoinsInput} kadar\nBTCV olabilir, daha fazlasını göndermeye çalışmayın!',
      amount_is_negative: 'Tutar negatif olamaz',
      amount_field_is_less_than_minSatoshi: "Gönderebileceğiniz minimum tutar\n1 Satoshi'dir.",
      amount_placeholder: 'gönderilecek tutar (BTCV olarak)',
      cancel: 'İptal',
      create: 'Fatura oluştur',
      create_tx_error: 'İşlem oluşturulurken bir sorun\nmeydana geldi. Lütfen bu adresin geçerli olduğundan emin olun.',
      fee: 'Ücret:',
      fee_field_is_not_valid: 'Ücret alanı geçerli değil',
      fee_placeholder: 'artı işlem ücreti  (BTCV olarak)',
      feeUnit: 'Sat/B',
      next: 'İleri',
      note: 'Not (opsiyonel)',
      note_placeholder: 'hatırlatıcı',
      remaining_balance: 'Kalan bakiye',
      scan: 'Tara',
      send: 'Gönder',
      title: 'işlem oluştur',
      to: 'nereye',
      total_exceeds_balance: 'Gönderim tutarı mevcut bakiyeden daha büyük.',
    },
    error: {
      doubleSpentFunds: 'Zaten harcamış olduğunuz fonları\nharcamaya çalışıyorsunuz.',
      notExistingFunds: 'Var olmayan bir parayı harcamaya\nçalışıyorsunuz.',
      dust: 'Küçük bir tutara karşılık gönderim \nyapmaya çalışıyorsunuz.',
      description: 'Bir işlem oluşturmadan önce\nBitcoin Vault cüzdanı eklemelisiniz.',
      title: 'Hata',
    },
    header: 'Coin gönder',
    recovery: {
      confirmFirstSeed: 'Anahtar Kelime Dizisi İptal ile \nonaylayın',
      confirmFirstSeedDesc:
        'Cüzdanınızı oluşturduğunuzda\noluşturulan ilk PDF belgesini açıp Özel Anahtar anahtar kelime dizisini aynı sırayla yazın.',
      confirmSecondSeed: 'Hızlı Anahtar Kelime Dizisi ile \nonaylayın',
      confirmSecondSeedDesc:
        'Cüzdanınızı oluşturduğunuzda\noluşturulan ikinci PDF belgesini açıp Özel Anahtar anahtar kelime dizisini aynı sırayla yazın.',
      confirmSeed: 'Anahtar Kelime Dizisi İptal ile \nonaylayın',
      confirmSeedDesc:
        'Cüzdanınızı oluşturduğunuzda\noluşturulan PDF belgesini açıp Özel Anahtar anahtar kelime dizisini aynı sırayla yazın.',
      recover: 'İptal',
      useWalletAddress: 'Bu cüzdanın adresini kullan',
    },
    success: {
      description: "Coin'lerinizi başarılı bir şekilde\ngönderdiniz.",
      done: 'Tamamlandı',
      return: 'Panoya dön',
      title: 'Başarılı',
    },
    transaction: {
      alert: 'Güvenli',
      alertDesc: 'İşlemin onaylanması için 144 blok\nveya 24 saat geçmesi gerekli. Bu süre içinde iptal edebilirsiniz.',
      fastSuccess: 'Hızlı işlemini başarılı bir şekilde\ngerçekleştirdiniz.',
      instant: 'Güvenli Hızlı',
      instantDesc: 'Bu işlem hemen onaylanacaktır.\nÇok dikkatli kullanın.',
      lightningError:
        'Bu adres bir Lightning faturası\niçin gibi görünüyor. Bu fatura için ödeme yapmak için lütfen Lightning cüzdanınıza gidin.',
      scanInstantKeyDesc:
        'İşlemi göndermek için cüzdanınızı oluşturduğunuzda \noluşturulan PDF belgesini açıp Özel Anahtar QR kodunu tarayın.',
      scanInstantKeyTitle: 'Hızlı Anahtarı tarayın.',
      type: 'İşlem Türü',
      watchOnlyError: 'Yalnızca görüntülenebilir \ncüzdanlardan işlem yapılamaz',
    },
    warning: 'Uyarı:',
    warningGeneral:
      'Lütfen Güvenli İşlem özelliğini\nkullanırken cüzdanınızda kalan miktarın bir kısmının bloke edilebileceğini unutmayın. Bu UTXO ve Bitcoin Vault cüzdanının blockchain parametreleriyle ilgili normal bir prosedürdür. İşlem onaylandıktan (yaklaşık 24 saat sonra) veya iptal edildikten (24 saat içinde) sonra bloke kalkacaktır.',
  },
  settings: {
    about: 'Hakkında',
    terms: 'Hüküm & Koşullar',
    factoryReset: 'Fabrika ayarlarına sıfırla',
    devInfo: 'Geliştirici bilgileri',
    developer: 'Geliştirici',
    aboutUs: 'Hakkımızda',
    advancedOptions: 'Hakkımızda',
    Biometrics: 'Biyometriğe izin ver',
    changePin: "PIN'i değiştir",
    electrumServer: 'Electrum sunucusu',
    FaceID: "FaceID'ye izin ver",
    fingerprintLogin: 'Parmak iziyle giriş',
    general: 'Genel',
    header: 'Ayarlar',
    language: 'Dil',
    notifications: 'Bildirimler',
    notSupportedFingerPrint: 'Cihazınız parmak izini \ndesteklemiyor',
    security: 'Güvenlik',
    TouchID: 'Parmak izine izin ver',
    factory: {
      title: 'Fabrika ayarlarına sıfırla',
      text:
        'Gold Wallet ı fabrika ayarlarına sıfırlamak istediğinizden emin misiniz? Tüm cüzdanlarınız ve verileriniz silinecektir. Cüzdanlarınızı tekrar içe aktarmanız gerekeceğini belirtiriz.',
      noButton: 'Hayır',
      yesButton: 'Evet',
    },
  },
  tabNavigator: {
    addressBook: 'Adres defteri',
    authenticators: 'Kimlik doğrulayıcılar',
    settings: 'Ayarlar',
    wallets: 'Cüzdanlar',
  },
  timeCounter: {
    closeTheApp: 'Uygulamayı kapat',
    description:
      'Başarısız giriş denemelerinden \ndolayı uygulamanız bloke edilmiştir. Tekrar denemek için gerekli sürenin bitmesini bekleyin.',
    title: 'Uygulama bloke edildi',
    tryAgain: 'Tekrar deneyin',
  },
  transactions: {
    details: {
      addNote: 'Not ekle',
      addToAddressBook: 'Adres defterine ekle',
      amount: 'Tutar',
      blocked: 'Bloke edildi',
      bytes: 'bytes',
      confirmations: 'onaylar',
      copy: 'Kopyala',
      copyAndBoriadcast: 'Kopyala ve sonra paylaş',
      details: 'Detaylar',
      detailTitle: 'İşlem detayları',
      fee: 'Ücret:',
      from: 'Nereden',
      inputs: 'Girdiler',
      noLabel: 'Etiket yok',
      note: 'Not',
      numberOfCancelTransactions: 'İptal olan işlem sayısı',
      ouputs: 'Çıktılar',
      returnedFee: 'İade edilen ücret:',
      satoshiPerByte: 'Byte başına Satoshi',
      sendCoins: 'Coin gönder',
      timePending: 'Kalan süre',
      title: 'İşlem',
      to: 'Nereye',
      toExternalWallet: 'Harici cüzdana',
      toInternalWallet: 'Dahili cüzdana',
      totalReturnedFee: 'Toplam iade edilen ücret:',
      transactioFee: 'İşlem ücreti',
      transactionDetails: 'İşlem detayları',
      transactionHex: "İşlem hex'i",
      transactionHexDescription: "Bu işlem hex'i imzalanmış ve ağla \npaylaşılmaya hazırdır",
      transactionId: 'İşlem Kimliği',
      transactionType: 'İşlem türü',
      txSize: 'TX boyutu',
      unblocked: 'Bloke kaldırıldı',
      verify: 'coinb.in üzerinden doğrula',
      viewInBlockRxplorer: 'Block gezgininde görüntüle',
      walletType: 'Cüzdan türü',
    },
    errors: {
      notEnoughBalance: 'Yetersiz bakiye. Lütfen daha küçük\nbir tutar göndermeyi deneyin.',
    },
    label: {
      blocked: 'bloke edildi',
      canceled: 'iptal edildi',
      canceledDone: 'İptal edildi - gerçekleştirildi',
      done: 'gerçekleştirildi',
      pending: 'beklemede',
      unblocked: 'bloke kaldırıldı',
    },
    list: {
      conf: 'Onaylar',
    },
    transactionTypeLabel: {
      canceled: 'İptal edildi',
      secure: 'Güvenli',
      secureFast: 'Güvenli Hızlı',
      standard: 'Standart',
    },
  },
  unlock: {
    confirmButton: 'Devam etmek için parmak izini\nonaylayın.',
    enter: "PIN'i girin",
    title: 'Kilidi aç',
    touchID: '"Gold Wallet" için Touch ID',
  },
  unlockTransaction: {
    description: 'Devam etmek için İşlem Şifrenizi\ngirin.',
    headerText: 'İşlemi onayla',
    title: 'İşlemi Onayla',
  },
  wallets: {
    add: {
      createWalletButton: 'Yeni cüzdan oluştur',
      addWalletButton: 'Yeni cüzdan ekle',
      advancedOptions: 'Gelişmiş seçenekler',
      air: 'Güvenli, İptal ve Güvenli ve Hızlı \nişlemleri yapar.',
      ar: 'Güvenli ve İptal işlemleri yapar.',
      description: 'Cüzdanınızın ismini ve türünü \nseçin.',
      failed: 'Cüzdan oluşturulamadı',
      importWalletButton: 'Cüzdanı içe aktar',
      inputLabel: 'İsim',
      legacy: 'İşlemler için varsayılan türler \noluşturur.',
      legacyHDP2SH: 'Tek bir 12 kelimelik anahtar \ndizisinden oluşturulan bir P2SH adresleri ağacı içerir.',
      legacyHDP2SHTitle: 'Standart HD P2SH',
      LegacyHDSegWit: 'Tek bir 12 kelimelik anahtar \ndizisinden oluşturulan native segwit adresleri ağacı içerir.',
      legacyHDSegWitTitle: 'Standart HD SegWit',
      LegacyP2SH: 'Tek bir P2SH adresi içerir',
      legacyP2SHTitle: 'Standart P2SH',
      legacyTitle: 'Standart',
      multipleAddresses: 'Tek bir 12 kelimelik anahtar\ndizisinden oluşturulan P2SH adresleri ağacı içerir',
      publicKeyError: 'Girilen genel anahtar geçersiz',
      segwidAddress: 'Tek bir 12 kelimelik anahtar \ndizisinden oluşturulan native segwit adresleri ağacı içerir.',
      singleAddress: 'Tek bir P2SH adresi içerir.',
      subtitle: 'Cüzdanınıza isim verin',
      title: 'Yeni cüzdan ekleyin',
      walletType: 'Cüzdan türü',
    },
    confirmSeed: {
      header: 'Anahtar kelime dizisini onayla',
      title: 'Yedek kelime dizisini onaylayın',
      description: 'Yedeklemeyi onaylamak için kelimelere doğru sırada tıklayın',
      button: 'Onayla',
      error: 'Anahtar kelime dizisinin sırası yanlış.',
    },
    addSuccess: {
      description:
        'Bu anahtar kelime dizisini güvenli\nbir yere yazın. Cüzdanınızı sıfırlamanız gerekirse buna ihtiyacınız olacak.',
      okButton: 'Tamam, yazdım',
      subtitle: 'Cüzdanınız hazır!\nCüzdanınızı oluşturdunuz!',
      title: 'Yeni cüzdan ekleyin',
    },
    dashboard: {
      allWallets: 'Tüm cüzdanlar',
      availableBalance: 'Mevcut bakiye',
      noTransactions: 'Gösterilecek işlem yok.',
      noWallets: 'Cüzdan yok',
      noWalletsDesc1: 'Gösterilecek cüzdan yok.\nİlk cüzdanınızı ekleyin.',
      noWalletsDesc2: 'ilk cüzdanınıza eklenecek.',
      receive: 'Al',
      recover: 'İptal',
      send: 'Gönder',
      title: 'Cüzdanlar',
      wallet: 'cüzdan',
    },
    deleteWallet: {
      description1: 'Silmek istediğinize emin misiniz',
      description2: '? Bu işlemi geri alamayacaksınız.',
      header: 'Cüzdanı sil',
      no: 'Hayır',
      title: 'Cüzdanı sil',
      yes: 'Evet',
    },
    details: {
      deleteWallet: 'Cüzdanı sil',
      details: 'Detaylar',
      edit: 'Düzenle',
      exportWallet: 'Cüzdanı dışa aktar',
      latestTransaction: 'Son işlem',
      nameEdit: 'İsmi düzenle',
      nameLabel: 'İsim',
      showWalletXPUB: "Cüzdan XPUB'sini göster",
      typeLabel: 'Tür',
      subscribeWallet: 'Email bildirimlerine abone ol',
      unsubscribeWallet: 'Email bildirimleri aboneliğinden çık',
    },
    errors: {
      duplicatedPublicKey: 'Genel anahtar zaten eklendi',
      invalidMnemonic: 'Geçersiz anımsatıcı',
      invalidMnemonicWordsNumber: 'Girilen {receivedWordsNumber} istenen kelime sayısı {expectedWordsNumber}',
      invalidPrivateKey: 'Geçersiz özel anahtar',
      invalidPublicKey: 'Geçersiz genel anahtar',
      invalidQrCode: 'Geçersiz QR kodu',
      invalidSign: 'İşlem imzalanamadı',
      noIndexForWord: 'Bu kelime için index bulunamadı: \n{word}',
      wrongNetwork:
        'Uygulama ağı {appNetworkName}\nolduğu halde {walletNetworkName} ağında cüzdanınız bulunuyor. Lütfen Telegram üzerinden Destek ekibimizle görüşün.',
    },
    export: {
      title: 'cüzdan dışa aktarma',
    },
    exportWallet: {
      header: 'Cüzdanı dışa aktar',
      title: 'Anahtar kelime dizisi',
    },
    exportWalletXpub: {
      header: 'Cüzdan XPUB',
    },
    import: {
      do_import: 'İçeri aktar',
      error: 'İçe aktarma başarısız. Lütfen girilen bilgilerin doğruluğunu kontrol edin.',
      explanation:
        "Buraya anımsatıcınızı, özel \nanahtarınızı, WIF'inizi veya elinizdeki başka bir veriyi yazın. GoldWallet doğru formatı tahmin edip cüzdanınızı içe aktarmak için elinden geleni yapacak.",
      imported: 'İçe aktarıldı',
      scan_qr: 'veya bunun yerine QR kodu \ntarayın?',
      success: 'Başarılı',
      title: 'içe aktarma',
    },
    importWallet: {
      chooseTypeDescription: 'İçe aktarmak istediğiniz cüzdan\ntürünü seçin.',
      customWords: 'Özel kelimeler',
      extendWithCustomWords: 'Bu kelime dizisini özel kelimelerle\nuzat',
      header: 'Cüzdanı içe aktar',
      import: 'İçe aktarın',
      importARDescription1: 'Anahtar kelime dizisini girin',
      importARDescription2: 'İçe aktarmak istediğiniz cüzdanın QR kodunu tarayın',
      placeholder: 'Anahtar kelime dizisi',
      scanCancelPubKey: 'İptal Anahtar QR kodunu tarayın',
      scanFastPubKey: 'Hızlı Anahtar QR kodunu tarayın',
      scanPublicKeyDescription:
        'İçe aktarmak istediğiniz cüzdanı \noluşturduğunuzda oluşan ilk PDF belgesini açıp bu uygulamayı kullanarak Genel Anahtar QR kodunu tarayın.',
      scanQrCode: 'veya QR kodunu tarayın',
      scanWalletAddress: 'Cüzdan adresini tarayın',
      scanWalletAddressDescription: "GoldWallet'la entegrasyonu \nbaşlatmak için Genel Adres QR kodunu tarayın.",
      subtitle:
        "Buraya anımsatıcınızı, özel \nanahtarınızı, WIF'inizi veya elinizdeki başka bir veriyi yazın. GoldWallet doğru formatı tahmin edip cüzdanınızı içe aktarmak için elinden geleni yapacak.",
      title: 'Cüzdanınızı içe aktarın',
      unsupportedElectrumVaultMnemonic:
        "Bu anahtar kelime dizisi Electrum\nVault'tan ve şu anda desteklenmiyor. Yakın gelecekte desteklenecektir.",
      walletInUseValidationError: 'Cüzdan zaten kullanımda. Lütfen\ngeçerli bir cüzdan girin.',
      allWalletsValidationError: '"Tüm cüzdanlar" ismini \ngiremezsiniz.',
    },
    publicKey: {
      instantDescription:
        'Başka bir cihazdan tekrar web \nAnahtar Oluşturucuya gidin, sayfayı yenileyin ve yeni Genel Anahtar QR kodunu taramak için bu uygulamayı kullanın. Anahtarlarınızı PDF olarak dışa aktarmayı unutmayın!',
      instantSubtitle: 'Hızlı Anahtar ekle',
      recoveryDescription:
        'Başka bir cihazdan tekrar web \nAnahtar Oluşturucuya gidip Genel Anahtar QR kodunu taramak için bu uygulamayı kullanın. Anahtarlarınızı PDF olarak dışa aktarmayı unutmayın!',
      recoverySubtitle: 'İptal Anahtarı Ekle',
      scan: 'Tara',
      webKeyGenerator: 'Web Anahtar Oluşturucu',
    },
    scanQrWif: {
      bad_password: 'Kötü şifre',
      bad_wif: 'Kötü WIF',
      cancel: 'İptal',
      decoding: 'Tekrar kodlanıyor',
      go_back: 'Geri Dön',
      imported_legacy: 'İçe aktarılan Legacy',
      imported_segwit: 'İçe aktarılan SegWit',
      imported_watchonly: 'İçe aktarılan yalnızca \ngörüntülenebilenler',
      imported_wif: 'İçe aktarılan WIF',
      input_password: 'Şifre girişi',
      password_explain: 'Bu BIP38 şifreli özel bir anahtardır',
      wallet_already_exists: 'Böyle bir cüzdan zaten var',
      with_address: 'adresiyle',
    },
    wallet: {
      latest: 'Son işlem',
      none: 'Yok',
      pendingBalance: 'Bloke bakiye',
    },
    walletModal: {
      btcv: 'BTCV',
      wallets: 'Cüzdanlar',
    },
  },
  connectionIssue: {
    noInternetTitle: 'İnternet bağlantısı yok',
    noInternetDescription: 'WI-FI veya mobil verinin açık\nolduğundan emin olup tekrar deneyin.',
    offlineMessageTitle: 'Çevrim dışısınız.',
    offlineMessageDescription: 'Tam işlevsellik için internete\nbağlanın.',
    offlineMessageDescription2: 'Bu işlevleri kullanmaya devam\netmek için internete bağlanın.',
    noNetworkTitle: 'Ağ yok',
    noNetworkDescription: 'İnternetiniz çalışıyor fakat ağa \nbağlı değilsiniz. Lütfen biraz bekleyip tekrar deneyin.',
    electrumXNotConnected: 'Electrum müşterisi bağlı değil',
    couldntConnectToServer: 'Sunucuya bağlanılamadı.',
  },
};
