module.exports = {
  _: {
    bad_password: 'Mật khẩu không hợp lệ, hãy thử lại',
    cancel: 'Huỷ bỏ',
    click: 'Nhấp chuột',
    confirm: 'Xác nhận',
    continue: 'Tiếp tục',
    copied: 'Đã sao chép!',
    copy: 'Sao chép',
    created: 'Được tạo ra',
    delete: 'Xóa',
    details: 'Chi tiết',
    enter_password: 'Nhập mật khẩu',
    here: 'Ở đây',
    invalid: 'Không hợp lệ',
    languageCode: 'en',
    never: 'Không bao giờ',
    next: 'Kế tiếp',
    ok: 'OK',
    or: 'hoặc là',
    satoshi: 'Sat',
    save: 'Lưu',
    scan: 'Quét',
    storage_is_encrypted: 'Bộ nhớ của bạn đã được mã hóa. Cần mật khẩu được để giải mã nó',
    skip: 'Bỏ qua bước này',
    add: 'Thêm',
    undo: 'Hoàn tác',
    yes: 'Có',
    no: 'Không',
  },
  order: {
    first: 'đầu tiên',
    second: 'thứ hai',
    third: 'thứ ba',
    fourth: 'thứ tư',
    fifth: 'thứ 5',
    sixth: 'thứ sáu',
  },
  time: {
    days: 'Ngày',
    hours: 'Giờ',
    minutes: 'Phút',
  },
  airdrop: {
    title: 'Airdrop',
    dateOfAirdrop: 'Mốc thời gian của Airdrop:',
    readableCommunityGoals: {
      first: 'Mục tiêu đầu tiên',
      second: 'Mục tiêu thứ hai',
      third: 'Mục tiêu thứ ba',
      fourth: 'Mục tiêu thứ tư',
    },
    readableGoals: {
      first: 'Mục tiêu đầu tiên của bạn',
      second: 'Mục tiêu thứ hai của bạn',
      third: 'Mục tiêu thứ ba của bạn',
      fourth: 'Mục tiêu thứ tư của bạn',
    },
    community: {
      header: 'Phần thưởng Airdrop',
      name: 'Cộng Đồng',
      description: 'Kiểm tra mức phần thưởng và tiến độ của Cộng Đồng',
      carouselItemHeader: 'Tiến độ của Cộng Đồng',
      wallet: 'ví',
      wallets: 'các ví',
      airdropParticipants: 'Người tham dự Airdrop',
      goal: 'Mục tiêu {order}:',
      unlockToIncrease: 'Mở khoá để tăng Airdrop lên ${reward}',
      thresholdWallets: '{threshold} ví',
    },
    circularWalletBalance: {
      yourBalance: 'Số dư của bạn',
    },
    createWallet: {
      doYouWantToTakePart: 'Bạn có muốn tham gia Airdrop?',
      title: 'Airdrop đã chính thức lên sóng!',
    },
    dashboard: {
      createNewWallet: 'Tạo ví mới',
      desc1: 'Thêm ví của bạn trước khi hết thời gian.',
      desc1WithWallets: 'Theo dõi quá trình của bạn và đăng ký thêm nhiều ví hơn nữa.',
      desc2: 'Tạo hoặc thêm một ví vào Airdrop.',
      cantConnectToServerLine1: 'Không thể kết nối tới máy chủ.',
      cantConnectToServerLine2: 'Vui lòng thử lại trong vài phút nữa.',
      loading1: 'Đang đợi máy chủ.',
      loading2: 'Quá trình sẽ mất vài giây.',
      availableWallets: 'Các ví khả dụng',
      registeredWallets: 'Các ví đã đăng ký',
    },
    itIsAlive: {
      subtitle: 'Airdrop đã chính thức lên sóng!',
      description: 'Airdrop BTCV đầu tiên của chúng tôi đã có mặt tại đây.\nHãy tìm hiểu để nhận phần thưởng!',
      notNow: 'Không phải lúc này',
      learnMore: 'Tìm hiểu thêm',
    },
    requirements: {
      soundsGreat: 'Thật tuyệt vời!',
      subtitle: 'Xin chân thành cám ơn vì đã trở thành một phần của Bitcoin Vault',
      description:
        'Chúng tôi muốn dành tặng ${airdropTotalDollarsToShare} bằng BTCV cho bạn bởi sự gắn bó với chúng tôi!',
      listHeader: 'Các yêu cầu dành cho Airdrop:',
      points: {
        '0': 'Bất kỳ Ví BTCV nào',
        '1': 'Có ít nhất {airdropMinimumBTCVRequired} BTCV được lưu trữ trong ví*',
      },
      rewardExplanation: '*Phần thưởng của bạn tuỳ thuộc vào số lượng coin bạn sở hữu trong general pool (pool chung).',
      termsAndConditions: {
        read: 'Đọc',
        termsAndConditions: 'Các điều khoản và điều kiện',
      },
    },
    walletsCarousel: {
      shrimp: '',
      crab: 'Crab',
      shark: '',
      whale: '',
      yourNextGoal: '{order} của bạn:',
      avatarTeaser: 'Trở thành một {goalName}: {goalThreshold} {unit}',
      youReachedGoal: 'Bạn đạt được mục tiêu:',
    },
    finished: {
      subtitle: 'Airdrop đã kết thúc!',
      stayTuned: 'Hãy tiếp tục theo dõi để biết thêm chi tiết trong {period}',
      shareIt: 'Chia sẻ với bạn bè',
      checkOutData: 'Muốn biết thêm thông tin?',
      readFullReport: 'Hãy đọc báo cáo đầy đủ của chúng tôi trên',
      medium: 'Medium',
      registeredWallets: 'Các ví đã đăng ký',
    },
    createWalletSuccess: {
      success: 'Hooray! \n  Bạn đã thành công đăng ký Airdrop!',
      successWithNotifications: 'Hooray! \n  Bạn đã thành công đăng ký nhận thông báo và đăng ký Airdrop!',
      shareIt: 'Hãy chia sẻ với bạn bè và nhận phần thưởng là {rewardValue} BTCV!*',
      maxReward: '*Mức phần thưởng tối đa dành cho một ví là {rewardValue} BTCV.',
      successCompletedButton: 'Đi tới {routeName}',
    },
  },
  termsConditions: {
    header: 'Điều khoản và điều kiện',
    title: 'Đồng ý với các điều khoản',
    text: '',
    readTermsConditions: 'Tôi đã đọc Điều khoản & Điều kiện',
    readPrivacyPolicy: 'Tôi đã đọc Chính sách quyền riêng tư',
    buttons: {
      agree: 'tôi đồng ý',
      disagree: 'tôi không đồng ý',
    },
    modal: {
      header: 'Bạn có chắc không?',
      text:
        'Lưu ý rằng nếu bạn không đồng ý với Điều khoản & Điều kiện của chúng tôi, bạn sẽ không thể sử dụng ứng dụng Gold Wallet.\nBạn có chắc chắn muốn từ chối không? ',
      noButton: 'Không, tôi đã đổi ý',
      yesButton: 'Vâng, tôi không đồng ý',
    },
  },
  aboutUs: {
    alwaysBackupYourKeys: 'Luôn sao lưu chìa khóa của bạn',
    buildWithAwesome: 'Xây dựng một cách tuyệt vời:',
    goToOurGithub: 'Truy cập Github của chúng tôi',
    header: 'Về chúng tôi',
    rateGoldWallet: 'Xếp hạng GoldWallet',
    releaseNotes: 'Ghi chú phát hành',
    runSelfTest: 'Chạy tự kiểm tra',
    title: 'Gold Wallet là một ví Bitcoin Vault mã nguồn mở miễn phí. MIT được cấp phép.',
  },
  developer: {
    config: 'Local Config',
    firebase: 'Firebase',
    FCMToken: 'FCMToken',
    copied: 'Đã sao chép',
    header: 'Lập Trình Viên',
    api: 'API',
    environment: 'Môi trường',
  },
  advancedOptions: {
    description:
      '"Bật tùy chọn Nâng cao sẽ cho phép bạn chọn từ các loại ví được liệt kê bên dưới:\n  P2SH, HD P2SH, HD segwit. "',
    title: 'Cài đặt cấu hình các tùy chọn nâng cao',
  },
  authenticators: {
    add: {
      description:
        'Bạn sẽ cần nó để ghép nối Gold Wallet với ứng dụng máy tính để bàn Electrum Vault. Nó sẽ sử dụng như xác thực hai yếu tố.',
      subdescription: 'Bạn cũng có thể nhập trình xác thực của mình bằng cách chọn tùy chọn bên dưới.',
      subtitle: 'Tạo trình xác thực mới',
      successDescription:
        'Viết lại cụm từ hạt giống này ở một nơi an toàn. Đó là bản sao lưu của bạn trong trường hợp bạn cần khôi phục trình xác thực của mình. Hãy nhớ rằng trình xác thực là cần thiết để xác nhận các giao dịch Nhanh và Hủy.',
      successTitle: 'Trình xác thực của bạn đã sẵn sàng!',
      title: 'Thêm trình xác thực mới',
    },
    delete: {
      subtitle: 'Xóa trình xác thực của bạn',
      success: 'Trình xác thực của bạn đã được xóa thành công. Bạn luôn có thể tạo một cái mới.',
      title: 'Xóa trình xác thực',
    },
    enterPIN: {
      description: 'Nhập mã PIN này vào ứng dụng Electrum Vault trên máy tính để kết thúc quá trình ghép nối.',
      subtitle: 'Nhập PIN',
    },
    errors: {
      noEmpty: 'Trường không được để trống',
    },
    export: {
      title: 'Xuất trình xác thực',
    },
    import: {
      code: 'Mã:',
      desc1: 'Viết ra cụm từ hạt giống hoặc quét mã QR của trình xác thực mà bạn muốn nhập.',
      desc2: 'quét mã QR bằng cách nhấp vào “hoặc quét mã QR” bên dưới',
      inUseValidationError: 'Tên phải là duy nhất. Xin vui lòng nhập vào một tên hợp lệ.',
      mnemonicLength: 'Ghi nhớ nên có 12 từ',
      multipleQrCodesDescription:
        'Một số giao dịch tạo ra nhiều mã QR. Đảm bảo quét tất cả chúng từ ứng dụng Electrum Vault.',
      multipleQrCodesTitle: 'Quét mã QR khác',
      scanNext: 'Quét tiếp theo',
      subtitle: 'Nhập trình xác thực của bạn',
      success: 'Bạn đã nhập thành công trình xác thực của mình. Bây giờ nó đã sẵn sàng để sử dụng.',
      textAreaPlaceholder: 'Cụm từ hạt giống',
      title: 'Nhập trình xác thực',
    },
    list: {
      noAuthenticators: 'Chưa có Trình xác thực',
      noAuthenticatorsDesc1: 'Nhấn vào',
      noAuthenticatorsDesc2: 'để thêm trình xác thực đầu tiên của bạn.',
      scan: 'Quét',
      title: 'Trình xác thực Bitcoin Vault',
    },
    options: {
      delete: 'Xóa trình xác thực',
      export: 'Xuất trình xác thực',
      pair: 'Ghép nối trình xác thực',
      sectionTitle: 'Chung',
      title: 'Tùy chọn trình xác thực',
    },
    pair: {
      descPin: 'Sử dụng mã PIN này để xác nhận ghép nối trình xác thực trên ứng dụng máy tính để bàn của bạn.',
      descPublicKey:
        'Bạn có thể sử dụng Khóa công khai này để nhập trình xác thực của mình vào ứng dụng trên máy tính để bàn trong quá trình tạo ví với tùy chọn GoldWallet.',
      pin: 'PIN',
      publicKey: 'Khóa công khai',
      title: 'Ghép nối trình xác thực',
    },
    publicKey: {
      okButton: 'Vâng tôi hiểu',
      subtitle:
        'Bạn có thể sử dụng Khóa công khai này để nhập trình xác thực của mình vào ứng dụng máy tính để bàn Electrum Vault trong quá trình tạo ví 2FA.',
      title: 'Khóa công khai',
    },
    sign: {
      error: 'Không ai trong số những người xác thực có thể ký giao dịch',
    },
  },
  betaVersion: {
    button: 'Tôi chấp nhận rủi ro',
    description:
      'Nó vẫn đang trong quá trình thử nghiệm cuối cùng trước khi phát hành chính thức. Ứng dụng dành cho thiết bị di động và tất cả nội dung được tìm thấy trên đó được cung cấp trên cơ sở “nguyên trạng” và “sẵn có”. Người dùng tự chịu rủi ro khi sử dụng phần mềm.',
    title: 'Đây là phiên bản beta của GoldWallet ',
  },
  contactCreate: {
    addressLabel: 'Địa chỉ',
    buttonLabel: 'Thêm liên hệ mới',
    description: 'Vui lòng nhập tên và địa chỉ\n  cho liên hệ mới của bạn. ',
    nameCannotContainSpecialCharactersError: 'Tên không được chứa các ký tự đặc biệt.',
    nameCannotEmpty: 'Tên không được để trống trường',
    nameLabel: 'Tên',
    nameMissingAlphanumericCharacterError: 'Tên bị thiếu ký tự chữ và số.',
    screenTitle: 'Thêm liên hệ mới',
    subtitle: 'Địa chỉ liên lạc mới',
    successButton: 'Quay lại sổ địa chỉ',
    successDescription: 'Hoan hô! Bạn \n  đã thêm liên hệ của bạn thành công',
    successTitle: 'Thành công',
  },
  contactDelete: {
    description1: 'Bạn có chắc chắn muốn xóa',
    description2: '?\n  Bạn không thể hoàn tác nó. ',
    header: 'Xóa liên lạc',
    no: 'Không',
    success: 'Thành công',
    successButton: 'Quay lại sổ địa chỉ',
    successDescription: 'Địa chỉ liên hệ của bạn đã được xóa thành công.\n Bây giờ bạn có thể quay lại Sổ địa chỉ. ',
    title: 'Xóa liên hệ của bạn',
    yes: 'Đúng',
  },
  contactDetails: {
    addressLabel: 'Địa chỉ',
    deleteButton: 'Xóa liên lạc',
    editAddress: 'Sửa địa chỉ',
    editName: 'Chỉnh sửa tên',
    nameLabel: 'Tên',
    sendCoinsButton: 'Gửi tiền xu',
    share: 'Chia sẻ',
    showQRCodeButton: 'đang hiện QR',
  },
  contactList: {
    cancel: 'Hủy bỏ',
    noContacts: 'Không có danh bạ',
    noContactsDesc1: 'Không có danh bạ để hiển thị.\nNhấp chuột',
    noContactsDesc2: 'Thêm danh bạ đầu tiên của bạn.',
    noResults: 'Không có kết quả cho',
    screenTitle: 'Sổ địa chỉ',
    search: 'Tìm kiếm',
  },
  electrumServer: {
    connectionError: 'Không thể kết nối đến máy chủ do Electrum cung cấp',
    description:
      'Bạn có thể thay đổi địa chỉ của máy chủ ứng dụng của bạn sẽ kết nối đến. Địa chỉ mặc định được khuyên dùng',
    header: 'máy chủ Electrum',
    host: 'tổ chức',
    port: 'Hải cảng',
    save: 'Lưu',
    successfullSave:
      'Thay đổi của bạn đã được lưu thành công. Khởi động lại có thể được yêu cầu để thay đổi có hiệu lực.',
    title: 'Thay đổi electrum máy chủ',
    useDefault: 'sử dụng mặc định',
  },
  filterTransactions: {
    clearAll: 'Làm sạch tất cả',
    clearFilters: 'Dọn sạch các bộ lọc',
    filter: 'Bộ lọc',
    from: 'Từ',
    fromAmount: 'Từ số lượng',
    fromDate: 'Từ ngày',
    header: 'Lọc giao dịch ',
    receive: 'Nhận được',
    received: 'Nhận',
    send: 'Gửi',
    sent: 'Đã gửi',
    status: {
      canceled: 'Bị hủy bỏ',
      canceledDone: 'Hủy-hoàn thành',
      done: 'Hoàn thành',
      pending: 'Đang chờ xử lý',
    },
    to: 'Đến',
    toAmount: 'đến số lượng',
    toDate: 'đến ngày',
    transactionStatus: 'Trạng thái giao dịch',
    transactionType: 'Loại giao dịch',
  },
  message: {
    allDone: 'Tất cả đã được hoàn thành!',
    bePatient: 'Vui lòng kiên nhẫn, điều này có thể mất một ít thời gian.',
    cancelTxSuccess: 'Bạn đã hủy thành công giao dịch của mình.\nTiền xu của bạn đang được gửi.',
    creatingAuthenticator: 'Tạo xác trình thực của bạn',
    creatingAuthenticatorDescription:
      'Xin hãy kiên nhẫn trong khi chúng tôi tạo ra xác thực cho bạn.\nNó có thể mất một thời gian.',
    creatingWallet: 'Tạo ví của bạn',
    creatingWalletSuccess: 'Bạn đã tạo ví thành công. ',
    creatingWalletDescription: 'Xin hãy kiên nhẫn trong khi chúng tôi tạo ví cho bạn.\nNó có thể mất một thời gian.',
    generateAddressesError: 'không thể tạo địa chỉ',
    hooray: 'Hoan hô!',
    importingAuthenticator: 'Nhập khẩu xác thực của bạn',
    importingAuthenticatorDescription:
      'Xin hãy kiên nhẫn trong khi chúng tôi nhập khẩu xác thực của bạn.\nNó có thể mất một thời gian.',
    noTransactions: 'Không tìm thấy trên ví giao dịch',
    noTransactionsDesc: 'Bạn có lẽ đang cố gắng để nhập khẩu của một ví mà nó chưa bao giờ được sử dụng',
    processing: 'Đang thực hiện',
    returnToAuthenticators: 'Quay trở lại trình xác thực',
    returnToDashboard: 'Quay trở lại Bảng Điều khiển',
    returnToWalletChoose: 'Quay trở lại lựa chọn loại ví',
    returnToWalletImport: 'Quay trở lại nhập ví',
    somethingWentWrong: 'Có gì đó đã bị sai',
    somethingWentWrongWhileCreatingWallet:
      'Có cái gì đó đã bị sai trong khi chúng tôi tạo ra ví cho bạn. Hãy quay trở lại Bảng điều khiển và thử lại.',
    success: 'Thành công',
    successfullWalletDelete: 'Ví của bạn đã được xóa thành công. Bây giờ bạn có thể trở lại Bảng điều khiển.',
    successfullWalletImport: 'Bạn đã nhập thành công ví của bạn. Nó bây giờ đã sẵn sàng để sử dụng.',
    wrongMnemonic: 'Ghi nhớ sai',
    wrongMnemonicDesc:
      'ghi nhớ của bạn không phù hợp với bất kỳ ví nào được hỗ trợ. Bạn đang cố gắng để nhập khẩu một ví ghi nhớ không hợp lệ hoặc ví chưa bao giờ được sử dụng',
    goToWalletDetails: 'Đi tới Chi tiết Ví',
    successSubscription: 'Hoan hô!\nBạn đã đăng ký thành công để thông báo.',
  },
  notifications: {
    main: {
      header: 'Thông báo',
      title: 'Thiết lập cấu hình thông báo của bạn',
      description: 'Bạn có thể chọn thông báo muốn nhận.',
    },
    email: {
      header: 'Thông báo email',
      description:
        'Bạn có thể thay đổi địa chỉ email của mình. Nó được sử dụng nhằm gửi thông báo các giao dịch từ ví được chọn.',
      title: 'Ví',
    },
    push: {
      header: 'Thông báo đẩy',
      title: 'Ví',
      description:
        'Bạn có thể thay đổi cài đặt thông báo đẩy. Nó được sử dụng nhằm gửi thông báo các giao dịch của bạn từ ví được chọn.',
    },
    emailNotificationsNavigate: 'Thông báo email',
    pushNotificationsNavigate: 'Thông báo đẩy',
    addYourAddress: 'Thêm địa chỉ email của bạn',
    addYourEmailFor: 'Thêm email của bạn để thông báo',
    addEmail: 'Thêm email',
    addYourAddressDescription: 'Nó được sử dụng để gửi thông báo giao dịch từ ví chọn.',
    addYourEmailForDescription:
      'Bạn có thể thêm địa chỉ email của bạn. Nó được sử dụng để gửi thông báo giao dịch từ ví chọn.',
    change: 'Thay đổi email của bạn',
    title: 'Cấu hình thông báo của bạn',
    yourEmail: 'Email của bạn',
    delete: 'Xóa email',
    invalidAddressError: 'Nhập địa chỉ email hợp lệ',
    yourSubscriptions: 'Đăng ký của bạn',
    confirmEmail: 'Xác nhận địa chỉ email của bạn',
    pleaseEnter: 'Vui lòng nhập mã chúng tôi gửi đến:',
    resend: 'Gửi lại mã',
    getNotification: 'Nhận thông báo',
    chooseWalletsDescription: 'Chọn ví mà từ đó bạn muốn nhận thông báo giao dịch',
    chooseWalletsToUnsubscribeDescription: 'Bạn có thể chọn ví từ mà bạn muốn huỷ đăng ký thông báo.',
    emailAddedSuccessMessage: 'Hoan hô!\nBạn đã thêm thành công địa chỉ email của bạn.',
    goToNotifications: 'Đến Thông báo',
    changeEmailTitle: 'Thay đổi email của bạn',
    changeEmailDescription:
      'Bạn có thể thay đổi địa chỉ email của mình. Nó được sử dụng để gửi cho bạn thông báo giao dịch từ các ví đã chọn.',
    yourCurrentEmail: 'email hiện tại của bạn',
    theSameAddressError: 'Bạn không thể nhập địa chỉ email hiện tại của bạn',
    newEmail: 'Email mới',
    invalidName: 'Tên ví không khả dụng',
    confirmCurrentTitle: 'Xác nhận địa chỉ email hiện tại của bạn',
    confirmNewTitle: 'Xác nhận địa chỉ email mới của bạn',
    confirmNewDescription: 'Bây giờ xác nhận địa chỉ email mới của bạn. Vui lòng nhập mã chúng tôi gửi đến',
    emailChangedSuccessMessage: 'Hoan hô!\nBạn đã cập nhật thành công địa chỉ email của bạn.',
    updateNotificationPreferences: 'Hoan hô!\nBạn đã cập nhật thành công tùy chọn thông báo.',
    verifyAction: 'Xác nhận hành động này',
    verifyActionDescription: 'Để xác nhận yêu cầu, vui lòng nhập mã chúng tôi gửi đến',
    deleteEmail: 'Xóa địa chỉ email',
    deleteYourEmail: 'Xóa email của bạn',
    deleteYourEmailDescription: 'địa chỉ email của bạn',
    deleteEmailSuccessMessage: 'Hoan hô!\nBạn đã xóa thành công địa chỉ email của mình.',
    codeError: 'Vui lòng nhập mã hợp lệ.\nBạn còn lại {attemptsLeft} lần thử.',
    codeFinalError: 'Bạn đã nhập một mã không hợp lệ 3 lần.\nChúng tôi đã gửi một mã mới đến địa chỉ email của bạn.',
    walletSubscribedSuccessMessage: 'Hoan hô!\nBạn đã thêm thành công địa chỉ email của bạn và đăng ký các thông báo.',
    no: 'Không',
    yes: 'Đồng ý',
    notifications: 'Thông báo',
    receiveTransactionDescription: 'Bạn có muốn nhận thông báo giao dịch từ ví này đến hộp email email của bạn',
    noteFirst: 'Ghi chú:',
    noteSecond: 'Nếu bạn muốn thay đổi địa chỉ email của bạn, bạn có thể làm điều đó sau trong Cài đặt.',
    noSubscriptionDescription: 'Bạn chưa đăng ký bất kỳ thông báo.',
    genericError: 'Có cái gì đó đã sai. Chúng tôi xin lỗi.',
    pushnotificationsSettings: {
      title: 'Cho phép ứng dụng gửi thông báo.',
      label: 'Cài đặt',
    },
    description:
      'Bạn có thể thay đổi địa chỉ email của bạn. Nó được sử dụng để gửi thông báo giao dịch từ ví được chọn.',
  },
  onboarding: {
    changePin: 'Thay đổi pin',
    confirmNewPin: 'Xác nhận mã PIN mới',
    confirmPassword: 'Xác nhận mật khẩu giao dịch ',
    confirmPin: 'Xác nhận mã PIN',
    createNewPin: 'Mã Pin mới',
    createPassword: 'Tạo mật khẩu giao dịch',
    addNotificationEmailDescription:
      'Nếu bạn muốn nhận thông báo email, vui lòng nhập địa chỉ email của bạn. Chúng tôi sẽ gửi cho bạn thông tin về trạng thái giao dịch của bạn. Bạn luôn có thể thay đổi nó sau này trong Cài đặt.',
    createPasswordDescription:
      'Mật khẩu giao dịch của bạn sẽ được sử dụng để xác minh tất cả các giao dịch. Bạn không thể thay đổi nó sau này. Mật khẩu giao dịch phải chứa ít nhất 8 ký tự và số.',
    createPin: 'Tạo mã PIN',
    createPinDescription:
      'Mã PIN của bạn sẽ được sử dụng để đăng nhập vào ứng dụng. Bạn có thể thay đổi nó sau này trong phần Cài đặt.',
    currentPin: 'Mã PIN hiện tại',
    failedTimes: 'Nhiều lần thất bại',
    failedTimesErrorInfo: 'Sau ba lần thất bại, việc nhập vào sẽ bị chặn cho',
    goBack: 'Quay lại',
    minutes: 'phút.',
    numberOfAttemptsExceeded: 'Số lần vượt quá',
    onboarding: 'Tích hợp',
    passwordDoesNotMatch: 'Mật khẩu không hợp lệ. Vui lòng nhập một mật khẩu hợp lệ.',
    pin: 'PIN',
    pinDoesNotMatch: 'PIN không phù hợp. Vui lòng nhập mã PIN hợp lệ.',
    seconds: 'Giây',
    successButton: 'Đi đến bảng điều khiển',
    successButtonChangedPin: 'Quay lại Cài đặt',
    successDescription: 'Hoan hô!\nBạn đã tạo thành số PIN của bạn.',
    successDescriptionChangedPin: 'Hoan hô!\nBạn đã thay đổi thành công mã PIN của bạn.',
    tryAgain: 'Vui lòng thử lại sau',
    resendCodeError: 'Bạn đã nhập một mã không hợp lệ 3 lần.\nChúng tôi đã gửi một mã mới đến địa chỉ email của bạn.',
    successCompletedDescription: 'Hoan hô!\nBạn đã hoàn thành quy trình tham gia hệ thống của bạn.',
    successCompletedButton: 'Đi đến Ví',
  },
  receive: {
    details: {
      amount: 'Số tiền',
      receiveWithAmount: 'Nhận với số lượng',
      receiveWithAmountSubtitle: 'Nhập số tiền mà bạn muốn nhận. Mã QR sẽ cập nhật phù hợp để đưa số tiền.',
      share: 'Chia sẻ',
      shareWalletAddress: 'Chia sẻ địa chỉ ví ',
    },
    header: 'Nhận tiền xu',
    label: 'địa chỉ Ví',
  },
  scanQrCode: {
    cancel: 'hủy bỏ',
    ok: 'Đồng ý',
    permissionMessage: 'Chúng tôi cần sự cho phép của bạn để sử dụng máy ảnh của bạn',
    permissionTitle: 'Cho phép sử dụng máy ảnh ',
  },
  security: {
    jailBrokenPhone:
      'Điện thoại của bạn dường như được bẻ khóa. Này có thể xảy ra vấn đề an ninh, treo máy, hoặc các vấn đề khác. Chúng tôi không khuyên bạn sử dụng GoldWallet với thiết bị bẻ khóa.',
    noPinOrFingerprintSet:
      'Điện thoại của bạn dường như không có một bộ mã PIN hoặc dấu vân tay. Chúng tôi không khuyên bạn sử dụng GoldWallet với một thiết bị không bảo đảm.',
    rootedPhone:
      'Điện thoại của bạn dường như đã được bẻ khóa. Điều này có thể xảy ra vấn đề an ninh, treo máy, hoặc các vấn đề khác. Chúng tôi không khuyên bạn sử dụng GoldWallet với thiết bị bẻ khóa.',
    title: 'Vấn đề an ninh',
  },
  selectLanguage: {
    alertDescription: 'Chọn ngôn ngữ và khởi động lại ứng dụng?',
    cancel: 'hủy bỏ',
    confirm: 'Xác nhận',
    confirmation: 'Xác nhận',
    header: 'Ngôn ngữ',
    restartInfo: 'Khi lựa chọn một ngôn ngữ mới, khởi động lại GoldWallet thể được yêu cầu để thay đổi có hiệu lực',
  },
  send: {
    confirm: {
      availableBalance: 'số dư có sẵn sau khi giao dịch',
      cancelNow: 'Hủy bây giờ',
      pendingBalance: 'Số dư bị chặn sau khi giao dịch',
      sendNow: 'Gửi ngay bây giờ',
    },
    create: {
      amount: 'Số lượng',
      fee: 'Phí',
      headerText:
        'Khi có một số lượng lớn các giao dịch đang chờ xử lý trên mạng (> 1500), phí cao hơn sẽ cho kết quả giao dịch của bạn đang được xử lý nhanh hơn. Các giá trị điển hình là 1-500 sat/b',
      setTransactionFee: 'Đặt một khoản phí giao dịch',
    },
    details: {
      address: 'Địa chỉ',
      address_field_is_not_valid: 'Trường địa chỉ không hợp lệ',
      amount_field_is_not_valid: 'Số lượng không hợp lệ',
      amount_is_too_high: 'Có tối đa {maxCoinsInput} BTCV đang tồn tại, vì vậy đừng cố gắng gửi nhiều hơn!',
      amount_is_negative: 'Số tiền không thể phủ định',
      amount_field_is_less_than_minSatoshi: 'Số tiền tối thiểu bạn có thể gửi là 1 Satoshi',
      amount_placeholder: 'số tiền gửi (trong BTCV)',
      cancel: 'hủy bỏ',
      create: 'Tạo hóa đơn',
      create_tx_error: 'Có lỗi khi tạo giao dịch. Xin chắc chắn rằng địa chỉ là hợp lệ.',
      fee: 'Phí:',
      fee_field_is_not_valid: 'Trường phí không hợp lệ',
      fee_placeholder: 'Cộng với phí giao dịch (trong BTCV)',
      feeUnit: 'Sat/B',
      next: 'Kế tiếp',
      note: 'Lưu ý (không bắt buộc)',
      note_placeholder: 'Tự ghi nhận',
      remaining_balance: 'số dư còn lại',
      scan: 'Quét',
      send: 'Gửi',
      title: 'tạo giao dịch',
      to: 'đến',
      total_exceeds_balance: 'Lượng gửi vượt quá số dư có sẵn.',
    },
    error: {
      doubleSpentFunds: 'Bạn đang cố gắng sử dụng quỹ đã được chi tiêu.',
      notExistingFunds: 'Bạn đang cố gắng sử dụng quỹ mà không tồn tại.',
      dust: 'Bạn đang cố gắng để gửi cho một số tiền nhỏ',
      description: 'Trước khi tạo một giao dịch, trước tiên bạn phải thêm một chiếc ví Bitcoin Vault.',
      title: 'Lỗi',
    },
    header: 'Gửi tiền xu',
    recovery: {
      confirmFirstSeed: 'Xác nhận với Hủy cụm từ Hạt Giống',
      confirmFirstSeedDesc:
        'Mở tài liệu PDF đầu tiên bạn đã tạo khi bạn đã tạo ví và ghi lại các cụm từ Khóa Riêng Tư của mình theo thứ tự.',
      confirmSecondSeed: 'Xác nhận với Nhanh cụm từ Hạt Giống',
      confirmSecondSeedDesc:
        'Mở tài liệu PDF thứ hai bạn đã tạo khi bạn đã tạo ví và ghi lại các cụm từ Khóa Riêng Tư của mình theo thứ tự.',
      confirmSeed: 'Xác nhận với Hủy cụm từ Hạt Giống',
      confirmSeedDesc:
        'Mở tài liệu PDF bạn tạo ra khi bạn đã tạo ví và ghi của bạn xuống các cụm từ Khóa riêng tư theo thứ tự.',
      recover: 'Hủy bỏ',
      useWalletAddress: 'Sử dụng địa chỉ của chiếc ví này',
    },
    success: {
      description: 'Quý vị đã gửi thành công tiền xu của bạn.',
      done: 'Hoàn thành',
      return: 'Quay trở lại Bảng Điều khiển',
      title: 'Thành công',
    },
    transaction: {
      alert: 'An toàn',
      alertDesc:
        'Giao dịch này cần 144 khối tương đương khoảng 24 giờ để được xác nhận. Bạn có thể hủy nó trong thời gian này.',
      fastSuccess: 'Bạn đã thực hiện thành công giao dịch nhanh chóng của bạn.',
      instant: 'Nhanh chóng An toàn',
      instantDesc: 'Giao dịch này sẽ được xác nhận ngay lập tức. Hãy sử dụng thận trọng.',
      lightningError:
        'Địa chỉ này dường như là một hóa đơn Lightning. Xin vui lòng, đi đến ví Lightning của bạn để thực hiện thanh toán cho hóa đơn này.',
      scanInstantKeyDesc:
        'Mở tài liệu PDF bạn đã tạo khi bạn tạo ví của mình và quét mã QR Khóa riêng tư để gửi giao dịch.',
      scanInstantKeyTitle: 'Quét Khóa nhanh',
      type: 'Loại giao dịch',
      watchOnlyError: 'Xem giao dịch chỉ ví không thể gửi',
    },
    warning: 'Cảnh báo:',
    warningGeneral:
      'Xin lưu ý rằng trong quá trình sử dụng các tính năng giao dịch an toàn, một phần của quỹ còn lại trong ví của bạn có thể bị chặn. Đây là một thủ tục bình thường liên quan đến UTXO và các thông số blockchain của chiếc ví Bitcoin Vault. Tiền của bạn sẽ được bỏ chặn khi giao dịch được xác minh (sau khoảng 24 giờ) hoặc hủy bỏ (trong vòng 24 giờ).',
  },
  settings: {
    about: 'Trong khoảng',
    terms: 'Điều khoản & Bảo mật',
    factoryReset: 'Khôi phục cài đặt gốc',
    devInfo: 'Thông tin về Lập Trình Viên',
    developer: 'Lập Trình Viên',
    aboutUs: 'Về chúng tôi',
    advancedOptions: 'tùy chọn nâng cao',
    Biometrics: 'cho phép sinh trắc học',
    changePin: 'Thay đổi pin',
    electrumServer: 'máy chủ Electrum',
    FaceID: 'cho phép FaceID',
    fingerprintLogin: 'Đăng nhập vân tay ',
    general: 'Chung',
    header: 'Cài đặt',
    language: 'Ngôn ngữ',
    notifications: 'Thông báo',
    notSupportedFingerPrint: 'Điện thoại của bạn không hỗ trợ dấu vân tay',
    security: 'Bảo vệ',
    TouchID: 'Cho phép vân tay',
    factory: {
      title: 'Khôi phục cài đặt gốc',
      text:
        'Bạn có chắc chắn muốn khôi phục Gold Wallet về cài đặt gốc? Tất cả thông tin ví và dữ liệu của bạn sẽ bị xoá. Hãy nhớ rằng bạn sẽ phải nhập ví của mình lại từ đầu.',
      noButton: 'Không',
      yesButton: 'Đúng',
    },
  },
  tabNavigator: {
    addressBook: 'Sổ địa chỉ',
    authenticators: 'Trình xác thực',
    settings: 'Cài đặt',
    wallets: 'Ví',
  },
  timeCounter: {
    closeTheApp: 'Đóng ứng dụng',
    description:
      'Ứng dụng của bạn đã bị chặn do sự nỗ lực đăng nhập không thành công. Xin vui lòng chờ thời gian cần thiết để thử lại.',
    title: 'Ứng dụng bị chặn',
    tryAgain: 'Thử lại',
  },
  transactions: {
    details: {
      addNote: 'Thêm ghi chú',
      addToAddressBook: 'Thêm vào Sổ địa chỉ',
      amount: 'Số tiền',
      blocked: 'Bị chặn',
      bytes: 'bytes',
      confirmations: 'Xác nhận',
      copy: 'Bản sao',
      copyAndBoriadcast: 'Sao chép và phát sóng sau đó',
      details: 'Chi tiết',
      detailTitle: 'Chi tiết giao dịch',
      fee: 'Phí:',
      from: 'Từ',
      inputs: 'Đầu vào',
      noLabel: 'Không nhãn hiệu',
      note: 'Ghi chú',
      numberOfCancelTransactions: 'Số lần Hủy giao dịch',
      ouputs: 'Kết quả đầu ra',
      returnedFee: 'Phí trả về:',
      satoshiPerByte: 'Satoshi mỗi byte',
      sendCoins: 'Gửi tiền xu',
      timePending: 'Thời gian chờ xử lý',
      title: 'Giao dịch',
      to: 'Đến',
      toExternalWallet: 'Đến ví bên ngoài',
      toInternalWallet: 'Đến ví nội bộ',
      totalReturnedFee: 'Tổng số phí hoàn lại:',
      transactioFee: 'Phí giao dịch',
      transactionDetails: 'Chi tiết giao dịch',
      transactionHex: 'hex giao dịch',
      transactionHexDescription: 'Đây là hex giao dịch, ký kết và sẵn sàng để được phát sóng vào mạng',
      transactionId: 'ID giao dịch',
      transactionType: 'Loại giao dịch',
      txSize: 'kích thước TX',
      unblocked: 'Mở chặn',
      verify: 'Xác minh trên coinb.in',
      viewInBlockRxplorer: 'Xem trong trình duyệt block',
      walletType: 'Loại Ví',
    },
    errors: {
      notEnoughBalance: 'Không đủ số dư. Xin vui lòng, cố gắng gửi một số lượng nhỏ hơn.',
    },
    label: {
      blocked: 'Bị chặn',
      canceled: 'Bị hủy bỏ',
      canceledDone: 'Hủy - Hoàn thành',
      done: 'Hoàn thành',
      pending: 'Đang chờ xử lý',
      unblocked: 'Mở chặn',
    },
    list: {
      conf: 'Xác nhận',
    },
    transactionTypeLabel: {
      canceled: 'Bị hủy bỏ',
      secure: 'An toàn',
      secureFast: 'Nhanh chóng An toàn',
      standard: 'Tiêu chuẩn',
    },
  },
  unlock: {
    confirmButton: 'Xác nhận dấu vân tay để tiếp tục.',
    enter: 'Nhập PIN',
    title: 'Mở khóa',
    touchID: 'Mã vẫn tay cho "Gold Wallet"',
  },
  unlockTransaction: {
    description: 'Nhập mật khẩu giao dịch để tiến hành.',
    headerText: 'Xác nhận giao dịch',
    title: 'Xác nhận giao dịch',
  },
  wallets: {
    add: {
      createWalletButton: 'Tạo ví mới',
      addWalletButton: 'Thêm ví mới',
      advancedOptions: 'Tùy chọn nâng cao',
      air: 'Thực hiện giao dịch An toàn, Hủy, và Nhanh An toàn',
      ar: 'Thực hiện giao dịch An toàn và giao dịch Hủy',
      description: 'Chọn tên và loại ví của bạn',
      failed: 'Không tạo được ví',
      importWalletButton: 'Nhập ví',
      inputLabel: 'Tên',
      legacy: 'Thực hiện các kiểu giao dịch mặc định ',
      legacyHDP2SH: 'Chứa một cây địa chỉ P2SH được tạo ra từ một hạt giống 12 từ duy nhất',
      legacyHDP2SHTitle: 'Chuẩn HD P2SH',
      LegacyHDSegWit: 'Có một cây địa chỉ segwit bản xứ, được tạo ra từ một hạt giống 12 từ duy nhất',
      legacyHDSegWitTitle: 'Chuẩn HD SegWit',
      LegacyP2SH: 'Chứa một địa chỉ P2SH đơn',
      legacyP2SHTitle: 'chuẩn P2SH',
      legacyTitle: 'Tiêu chuẩn',
      multipleAddresses: 'Nó chứa một cây địa chỉ P2SH tạo ra từ một hạt giống 12 từ duy nhất',
      publicKeyError: 'Khóa công khai được cung cấp không hợp lệ',
      segwidAddress: 'Nó chứa một cây địa chỉ segwit bản xứ, được tạo ra từ một hạt giống 12 từ duy nhất',
      singleAddress: 'Nó chứa một địa chỉ P2SH đơn',
      subtitle: 'Đặt tên cho ví của bạn',
      title: 'Thêm ví mới',
      walletType: 'Loại Ví',
    },
    confirmSeed: {
      header: 'Xác nhận cụm từ hạt giống',
      title: 'Xác nhận giai đoạn sao lưu',
      description: 'Nhấp chọn các từ theo đúng thứ tự để xác nhận bản sao lưu của bạn.',
      button: 'Xác nhận',
      error: 'Thứ tự của cụm từ hạt giống không chính xác.',
    },
    addSuccess: {
      description:
        'Viết xuống cụm từhạt giống này ở nôi an toàn. Đó là bản sao lưu của bạn trong trường hợp bạn cần khôi phục lại ví của mình.',
      okButton: 'OK, tôi đã viết ra.',
      subtitle: 'Ví của bạn đã sẵn sàng!\nBạn đã tạo ví của mình!',
      title: 'Thêm ví mới',
    },
    dashboard: {
      allWallets: 'Tất cả các ví',
      availableBalance: 'Số dư có sẵn',
      noTransactions: 'Không có giao dịch để hiển thị.',
      noWallets: 'không có ví',
      noWalletsDesc1: 'Không có ví để hiển thị.\nThêm ví đầu tiên của bạn.',
      noWalletsDesc2: 'Thêm ví đầu tiên của bạn.',
      receive: 'Nhận được',
      recover: 'Hủy bỏ',
      send: 'Gửi',
      title: 'Ví',
      wallet: 'Ví tiền',
    },
    deleteWallet: {
      description1: 'Bạn có chắc chắn muốn xóa',
      description2: '? Bạn không thể hoàn tác nó.',
      header: 'Xóa ví của bạn',
      no: 'Không',
      title: 'Xóa ví của bạn',
      yes: 'Đúng',
    },
    details: {
      deleteWallet: 'Xóa ví của bạn',
      details: 'Chi tiết',
      edit: 'Biên tập',
      exportWallet: 'Xuất ví',
      latestTransaction: 'Giao dịch mới nhất',
      nameEdit: 'Chỉnh sửa tên',
      nameLabel: 'Tên',
      showWalletXPUB: 'Hiện ví XPUB',
      typeLabel: 'Loại',
      subscribeWallet: 'Theo dõi thông báo qua email',
      unsubscribeWallet: 'Hủy đăng ký nhận các thông báo email',
    },
    errors: {
      duplicatedPublicKey: 'Khóa công khai đã được thêm',
      invalidMnemonic: 'Ghi nhớ không hợp lệ',
      invalidMnemonicWordsNumber: 'Cung cấp {receivedWordsNumber} từ dự kiến {expectedWordsNumber}',
      invalidPrivateKey: 'Khóa riêng tư không hợp lệ',
      invalidPublicKey: 'Khóa công khai không hợp lệ',
      invalidQrCode: 'Mã QR không hợp lệ ',
      invalidSign: 'Không thể đăng nhập giao dịch',
      noIndexForWord: 'Không thể tìm thấy chỉ số từ: {word}',
      wrongNetwork:
        'Bạn có ví trên mạng {walletNetworkName} trong khi mạng ứng dụng là {appNetworkName}. Vui lòng liên hệ hỗ trợ của chúng tôi trên Telegram.',
    },
    export: {
      title: 'Xuất ví',
    },
    exportWallet: {
      header: 'xuất ví',
      title: 'Cm từ hạt giống',
    },
    exportWalletXpub: {
      header: 'Ví XPUB',
    },
    import: {
      do_import: 'Nhập',
      error: 'Thất bại trong việc nhập. Xin vui lòng chắc chắn rằng các dữ liệu được cung cấp là hợp lệ.',
      explanation:
        'Viết ở đây ghi nhớ, khóa riêng tư, WIF, hoặc bất cứ điều gì bạn đã có. GoldWallet sẽ làm hết sức mình để đoán đúng định dạng và nhập ví của bạn',
      imported: 'Đã được nhập',
      scan_qr: 'Hoặc quét mã QR để thay thế?',
      success: 'Thành công',
      title: 'Nhập',
    },
    importWallet: {
      chooseTypeDescription: 'Chọn loại ví bạn muốn nhập.',
      customWords: 'Từ ngữ tùy chỉnh',
      extendWithCustomWords: 'Mở rộng hạt giống này với các từ tùy chỉnh',
      header: 'Nhập ví',
      import: 'Nhập',
      importARDescription1: 'Nhập cụm từ hạt giống',
      importARDescription2: 'Quét mã QR của ví mà bạn muốn nhập',
      placeholder: 'Cụm từ hạt giống',
      scanCancelPubKey: 'Quét mã QR Cancel Key (Huỷ Khoá)',
      scanFastPubKey: 'Quét mã QR Fast Key (Khóa Nhanh)',
      scanPublicKeyDescription:
        'Mở tài liệu PDF đầu tiên bạn đã tạo khi bạn tạo ví mà bạn muốn nhập và sử dụng ứng dụng này để quét mã QR Khóa Riêng Tư.',
      scanQrCode: 'hoặc quyét mã QR.',
      scanWalletAddress: 'Quét địa chỉ ví',
      scanWalletAddressDescription: 'Quét Địa chỉ Mã QR Công Khai để bắt đầu tích hợp với GoldWallet.',
      subtitle:
        'Viết ở đây để ghi nhớ, khóa riêng tư, WIF hoặc bất cứ điều gì bạn ghi nhớ. GoldWallet sẽ làm hết sức mình để đoán đúng định dạng và nhập ví.',
      title: 'Nhập ví của bạn',
      unsupportedElectrumVaultMnemonic:
        'Hạt giống này là từ Electrum Vault và hiện chưa được hỗ trợ. Sẽ được hỗ trợ trong tương lai gần.',
      walletInUseValidationError: 'Ví đã được sử dụng. Vui lòng nhập một ví khác hợp lệ.',
      allWalletsValidationError: 'Bạn không thể nhập tên "Tất cả các ví"',
    },
    publicKey: {
      instantDescription:
        'Tới trang web Trình Tạo Khóa trên một thiết bị riêng biệt một lần nữa, làm mới trang và sử dụng ứng dụng này để quét mã QR Khóa Riêng Tư mới. Hãy nhớ xuất các khóa của bạn dưới dạng tệp PDF!',
      instantSubtitle: 'Thêm Fast Key (Chìa Khoá Nhanh)',
      recoveryDescription:
        'Tới trang web Trình Tạo Khóa trên một thiết bị riêng biệt một lần nữa và sử dụng ứng dụng này để quét mã QR Khóa Riêng Tư mới. Hãy nhớ xuất các khóa của bạn  dưới dạng PDF!',
      recoverySubtitle: 'Thêm Khóa Hủy',
      scan: 'Quét',
      webKeyGenerator: 'Web Trình tạo khóa:',
    },
    scanQrWif: {
      bad_password: 'Mật khẩu không an toàn',
      bad_wif: 'WIF xấu',
      cancel: 'Hủy bỏ',
      decoding: 'Giải mã',
      go_back: 'Quay lại',
      imported_legacy: 'Nhập Legacy',
      imported_segwit: 'Nhập SegWit',
      imported_watchonly: 'Nhập Chỉ-xem',
      imported_wif: 'Nhập WIF',
      input_password: 'Nhập mật khẩu',
      password_explain: 'Đây là chìa khoá mã hoá bí mật BIP38',
      wallet_already_exists: 'Ví này đã tồn tại',
      with_address: 'Với địa chỉ',
    },
    wallet: {
      latest: 'Giao dịch mới nhất',
      none: 'Không có',
      pendingBalance: 'Số dư bị chặn sau khi giao dịch',
    },
    walletModal: {
      btcv: 'BTCV',
      wallets: 'Ví',
    },
  },
  connectionIssue: {
    noInternetTitle: 'Không có kết nối Internet',
    noInternetDescription: 'Đảm bảo rằng Wi-Fi hoặc dữ liệu di động được bật lên, sau đó thử lại.',
    offlineMessageTitle: 'Bạn đang ngoại tuyến',
    offlineMessageDescription: 'Kết nối với internet để khôi phục lại đầy đủ chức năng.',
    offlineMessageDescription2: 'Kết nối với internet để tiếp tục sử dụng các chức năng này.',
    noNetworkTitle: 'Không có mạng',
    noNetworkDescription:
      'Internet của bạn vẫn hoạt động, nhưng bạn không kết nối vào mạng. Xin hãy chờ một lát và thử lại.',
    electrumXNotConnected: 'Khách hàng của Electrum không được kết nối',
    couldntConnectToServer: 'Không thể kết nối đến máy chủ.',
  },
};
