name: Lint

on:
  push:
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/lint.yml"
  pull_request:
    branches: [master]
    paths:
      - "go.sum"
      - "go.mod"
      - "**.go"
      - ".github/workflows/lint.yml"

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup go version
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
