name: "Lint PR"

on:
  push:
    branches: [ $default-branch, $protected-branches, main, develop, stage ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [$default-branch, main, develop, stage]
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
