name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create GitHub release
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
        branch: master
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
          conventional-changelog-conventionalcommits
      env:
        GITHUB_TOKEN: ${{ secrets.TS_GH_TOKEN }}
